<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class alertsraised */

require_once( 'DB/DataObject.php' );;

class alertsraised_object extends DB_DataObject
{
	var $__table='alertsraised';
		//This is a Structures/DataGrid object
	var $idalertsraised;
	var $username;
	var $idalerts;
	var $cleared;
	var $lastupdate;
	var $raisedtimestamp;
	var $idstockalert;
};
?>