<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

class candlesticksoccured extends generictable 
{
	/*char * */ var $pretty_name = '';
	/*char * */ var $pretty_plural = '';
	/*char * */ var $pageheader = '';
	/*char * */ var $pagefooter = '';
         private $observers;
	/*char * */ var $data; //data passed in by other calls
/********************************************************
 *
 *	This section is the table columns
 *
 *******************************************************/
         var          /*int *//* int */ $idcandlesticksoccured;
		 /*Index */
         var          /*char* *//* datetime */ $createddate;
		 /*Record Created Date */
         var          /*int *//* int */ $createduser;
		 /*Record Created by User */
         var          /*char* *//* timestamp */ $updateddate;
		 /*Record updated date */
         var          /*int *//* int */ $updateduser;
		 /*Record Updated by user */
         var          /*char* *//* varchar */ $symbol;
		 /*Stock Symbol */
         var          /*char* *//* date */ $date;
		 /*Date in stockprices */
         var          /*char* *//* varchar */ $candlestick;
		 /*Candlestick Identified for this date */
         function __construct()
         {
         	$this->querytablename = 'candlesticksoccured';
         	$this->classname = 'candlesticksoccured';
         	$this->fieldspec['idcandlesticksoccured']['metadata_id'] = '9084';
         	$this->fieldspec['idcandlesticksoccured']['table_name'] = 'candlesticksoccured';
         	$this->fieldspec['idcandlesticksoccured']['column_name'] = 'idcandlesticksoccured';
         	$this->fieldspec['idcandlesticksoccured']['pretty_name'] = 'Index';
         	$this->fieldspec['idcandlesticksoccured']['abstract_data_type'] = 'int';
         	$this->fieldspec['idcandlesticksoccured']['db_data_type'] = 'int';
         	$this->fieldspec['idcandlesticksoccured']['field_null'] = 'YES';
         	$this->fieldspec['idcandlesticksoccured']['field_key'] = '';
         	$this->fieldspec['idcandlesticksoccured']['extra_sql'] = ' ';
         	$this->fieldspec['idcandlesticksoccured']['html_form_type'] = 'int';
         	$this->fieldspec['idcandlesticksoccured']['html_form_options'] = '';
         	$this->fieldspec['idcandlesticksoccured']['html_link_options'] = '';
         	$this->fieldspec['idcandlesticksoccured']['html_form_explanation'] = 'Index';
         	$this->fieldspec['idcandlesticksoccured']['help_text'] = '';
         	$this->fieldspec['idcandlesticksoccured']['mandatory_p'] = 'N';
         	$this->fieldspec['idcandlesticksoccured']['sort_key'] = '0';
         	$this->fieldspec['idcandlesticksoccured']['form_sort_key'] = '0';
         	$this->fieldspec['idcandlesticksoccured']['form_number'] = '1';
         	$this->fieldspec['idcandlesticksoccured']['default_value'] = '';
         	$this->fieldspec['idcandlesticksoccured']['field_toupper'] = 'NO';
         	$this->fieldspec['idcandlesticksoccured']['validationprocname'] = '';
         	$this->fieldspec['idcandlesticksoccured']['minlength'] = '1';
         	$this->fieldspec['idcandlesticksoccured']['maxlength'] = '11';
         	$this->fieldspec['idcandlesticksoccured']['c_size'] = '11';
         	$this->fieldspec['idcandlesticksoccured']['prikey'] = 'Y';
         	$this->fieldspec['idcandlesticksoccured']['noedit'] = 'Y';
         	$this->fieldspec['idcandlesticksoccured']['nodisplay'] = 'Y';
         	$this->fieldspec['idcandlesticksoccured']['c_unsigned'] = 'N';
         	$this->fieldspec['idcandlesticksoccured']['c_zerofill'] = 'N';
         	$this->fieldspec['idcandlesticksoccured']['c_auto_increment'] = 'Y';
         	$this->fieldspec['idcandlesticksoccured']['foreign_table'] = '';
         	$this->fieldspec['idcandlesticksoccured']['foreign_key'] = '';
         	$this->fieldspec['idcandlesticksoccured']['application'] = 'finance';
         	$this->fieldspec['idcandlesticksoccured']['issearchable'] = '1';
         	$this->fieldspec['idcandlesticksoccured']['preinserttrigger'] = '';
         	$this->fieldspec['idcandlesticksoccured']['postinserttrigger'] = '';
         	$this->fieldspec['idcandlesticksoccured']['preupdatetrigger'] = '';
         	$this->fieldspec['idcandlesticksoccured']['postupdatetrigger'] = '';
         	$this->fieldspec['idcandlesticksoccured']['predeletetrigger'] = '';
         	$this->fieldspec['idcandlesticksoccured']['postdeletetrigger'] = '';
         	$this->fieldspec['idcandlesticksoccured']['definition_version'] = '1';
         	$this->fieldspec['idcandlesticksoccured']['form_javascript'] = '';
         	$this->fieldspec['idcandlesticksoccured']['rowSecurityProc'] = '';
         	$this->fieldspec['idcandlesticksoccured']['postinsert'] = 'PostidcandlesticksoccuredInsert';
         	$this->fieldspec['idcandlesticksoccured']['postupdate'] = 'PostidcandlesticksoccuredUpdate';
         	$this->fieldspec['idcandlesticksoccured']['postdelete'] = 'PostidcandlesticksoccuredDelete';
         	$this->fieldspec['idcandlesticksoccured']['preinsert'] = 'PreidcandlesticksoccuredInsert';
         	$this->fieldspec['idcandlesticksoccured']['preupdate'] = 'PreidcandlesticksoccuredUpdate';
         	$this->fieldspec['idcandlesticksoccured']['predelete'] = 'PreidcandlesticksoccuredDelete';
         	$this->fieldspec['createddate']['metadata_id'] = '9085';
         	$this->fieldspec['createddate']['table_name'] = 'candlesticksoccured';
         	$this->fieldspec['createddate']['column_name'] = 'createddate';
         	$this->fieldspec['createddate']['pretty_name'] = 'Record Created Date';
         	$this->fieldspec['createddate']['abstract_data_type'] = 'datetime';
         	$this->fieldspec['createddate']['db_data_type'] = 'datetime';
         	$this->fieldspec['createddate']['field_null'] = 'YES';
         	$this->fieldspec['createddate']['field_key'] = '';
         	$this->fieldspec['createddate']['extra_sql'] = ' ';
         	$this->fieldspec['createddate']['html_form_type'] = 'datetime';
         	$this->fieldspec['createddate']['html_form_options'] = '';
         	$this->fieldspec['createddate']['html_link_options'] = '';
         	$this->fieldspec['createddate']['html_form_explanation'] = 'Record Created Date';
         	$this->fieldspec['createddate']['help_text'] = '';
         	$this->fieldspec['createddate']['mandatory_p'] = 'N';
         	$this->fieldspec['createddate']['sort_key'] = '0';
         	$this->fieldspec['createddate']['form_sort_key'] = '0';
         	$this->fieldspec['createddate']['form_number'] = '1';
         	$this->fieldspec['createddate']['default_value'] = '';
         	$this->fieldspec['createddate']['field_toupper'] = 'NO';
         	$this->fieldspec['createddate']['validationprocname'] = '';
         	$this->fieldspec['createddate']['minlength'] = '1';
         	$this->fieldspec['createddate']['maxlength'] = '11';
         	$this->fieldspec['createddate']['c_size'] = '11';
         	$this->fieldspec['createddate']['prikey'] = 'N';
         	$this->fieldspec['createddate']['noedit'] = 'N';
         	$this->fieldspec['createddate']['nodisplay'] = 'N';
         	$this->fieldspec['createddate']['c_unsigned'] = 'N';
         	$this->fieldspec['createddate']['c_zerofill'] = 'N';
         	$this->fieldspec['createddate']['c_auto_increment'] = 'N';
         	$this->fieldspec['createddate']['foreign_table'] = '';
         	$this->fieldspec['createddate']['foreign_key'] = '';
         	$this->fieldspec['createddate']['application'] = 'finance';
         	$this->fieldspec['createddate']['issearchable'] = '1';
         	$this->fieldspec['createddate']['preinserttrigger'] = '';
         	$this->fieldspec['createddate']['postinserttrigger'] = '';
         	$this->fieldspec['createddate']['preupdatetrigger'] = '';
         	$this->fieldspec['createddate']['postupdatetrigger'] = '';
         	$this->fieldspec['createddate']['predeletetrigger'] = '';
         	$this->fieldspec['createddate']['postdeletetrigger'] = '';
         	$this->fieldspec['createddate']['definition_version'] = '1';
         	$this->fieldspec['createddate']['form_javascript'] = '';
         	$this->fieldspec['createddate']['rowSecurityProc'] = '';
         	$this->fieldspec['createddate']['postinsert'] = 'PostcreateddateInsert';
         	$this->fieldspec['createddate']['postupdate'] = 'PostcreateddateUpdate';
         	$this->fieldspec['createddate']['postdelete'] = 'PostcreateddateDelete';
         	$this->fieldspec['createddate']['preinsert'] = 'PrecreateddateInsert';
         	$this->fieldspec['createddate']['preupdate'] = 'PrecreateddateUpdate';
         	$this->fieldspec['createddate']['predelete'] = 'PrecreateddateDelete';
         	$this->fieldspec['createduser']['metadata_id'] = '9086';
         	$this->fieldspec['createduser']['table_name'] = 'candlesticksoccured';
         	$this->fieldspec['createduser']['column_name'] = 'createduser';
         	$this->fieldspec['createduser']['pretty_name'] = 'Record Created by User';
         	$this->fieldspec['createduser']['abstract_data_type'] = 'int';
         	$this->fieldspec['createduser']['db_data_type'] = 'int';
         	$this->fieldspec['createduser']['field_null'] = 'YES';
         	$this->fieldspec['createduser']['field_key'] = '';
         	$this->fieldspec['createduser']['extra_sql'] = ' ';
         	$this->fieldspec['createduser']['html_form_type'] = 'currentindexuser';
         	$this->fieldspec['createduser']['html_form_options'] = '<fk><field>username</field></fk>';
         	$this->fieldspec['createduser']['html_link_options'] = '';
         	$this->fieldspec['createduser']['html_form_explanation'] = 'Record Created by User';
         	$this->fieldspec['createduser']['help_text'] = '';
         	$this->fieldspec['createduser']['mandatory_p'] = 'N';
         	$this->fieldspec['createduser']['sort_key'] = '0';
         	$this->fieldspec['createduser']['form_sort_key'] = '0';
         	$this->fieldspec['createduser']['form_number'] = '1';
         	$this->fieldspec['createduser']['default_value'] = '';
         	$this->fieldspec['createduser']['field_toupper'] = 'NO';
         	$this->fieldspec['createduser']['validationprocname'] = '';
         	$this->fieldspec['createduser']['minlength'] = '1';
         	$this->fieldspec['createduser']['maxlength'] = '11';
         	$this->fieldspec['createduser']['c_size'] = '11';
         	$this->fieldspec['createduser']['prikey'] = 'N';
         	$this->fieldspec['createduser']['noedit'] = 'N';
         	$this->fieldspec['createduser']['nodisplay'] = 'N';
         	$this->fieldspec['createduser']['c_unsigned'] = 'N';
         	$this->fieldspec['createduser']['c_zerofill'] = 'N';
         	$this->fieldspec['createduser']['c_auto_increment'] = 'N';
         	$this->fieldspec['createduser']['foreign_table'] = 'users';
         	$this->fieldspec['createduser']['foreign_key'] = 'idusers';
         	$this->fieldspec['createduser']['application'] = 'finance';
         	$this->fieldspec['createduser']['issearchable'] = '1';
         	$this->fieldspec['createduser']['preinserttrigger'] = '';
         	$this->fieldspec['createduser']['postinserttrigger'] = '';
         	$this->fieldspec['createduser']['preupdatetrigger'] = '';
         	$this->fieldspec['createduser']['postupdatetrigger'] = '';
         	$this->fieldspec['createduser']['predeletetrigger'] = '';
         	$this->fieldspec['createduser']['postdeletetrigger'] = '';
         	$this->fieldspec['createduser']['definition_version'] = '1';
         	$this->fieldspec['createduser']['form_javascript'] = '';
         	$this->fieldspec['createduser']['rowSecurityProc'] = '';
         	$this->fieldspec['createduser']['postinsert'] = 'PostcreateduserInsert';
         	$this->fieldspec['createduser']['postupdate'] = 'PostcreateduserUpdate';
         	$this->fieldspec['createduser']['postdelete'] = 'PostcreateduserDelete';
         	$this->fieldspec['createduser']['preinsert'] = 'PrecreateduserInsert';
         	$this->fieldspec['createduser']['preupdate'] = 'PrecreateduserUpdate';
         	$this->fieldspec['createduser']['predelete'] = 'PrecreateduserDelete';
         	$this->fieldspec['updateddate']['metadata_id'] = '9087';
         	$this->fieldspec['updateddate']['table_name'] = 'candlesticksoccured';
         	$this->fieldspec['updateddate']['column_name'] = 'updateddate';
         	$this->fieldspec['updateddate']['pretty_name'] = 'Record updated date';
         	$this->fieldspec['updateddate']['abstract_data_type'] = 'timestamp';
         	$this->fieldspec['updateddate']['db_data_type'] = 'timestamp';
         	$this->fieldspec['updateddate']['field_null'] = 'YES';
         	$this->fieldspec['updateddate']['field_key'] = '';
         	$this->fieldspec['updateddate']['extra_sql'] = ' ';
         	$this->fieldspec['updateddate']['html_form_type'] = 'currenttime';
         	$this->fieldspec['updateddate']['html_form_options'] = '';
         	$this->fieldspec['updateddate']['html_link_options'] = '';
         	$this->fieldspec['updateddate']['html_form_explanation'] = 'Record updated date';
         	$this->fieldspec['updateddate']['help_text'] = '';
         	$this->fieldspec['updateddate']['mandatory_p'] = 'N';
         	$this->fieldspec['updateddate']['sort_key'] = '0';
         	$this->fieldspec['updateddate']['form_sort_key'] = '0';
         	$this->fieldspec['updateddate']['form_number'] = '3';
         	$this->fieldspec['updateddate']['default_value'] = '';
         	$this->fieldspec['updateddate']['field_toupper'] = 'NO';
         	$this->fieldspec['updateddate']['validationprocname'] = '';
         	$this->fieldspec['updateddate']['minlength'] = '1';
         	$this->fieldspec['updateddate']['maxlength'] = '11';
         	$this->fieldspec['updateddate']['c_size'] = '11';
         	$this->fieldspec['updateddate']['prikey'] = 'N';
         	$this->fieldspec['updateddate']['noedit'] = 'N';
         	$this->fieldspec['updateddate']['nodisplay'] = 'N';
         	$this->fieldspec['updateddate']['c_unsigned'] = 'N';
         	$this->fieldspec['updateddate']['c_zerofill'] = 'N';
         	$this->fieldspec['updateddate']['c_auto_increment'] = 'N';
         	$this->fieldspec['updateddate']['foreign_table'] = '';
         	$this->fieldspec['updateddate']['foreign_key'] = '';
         	$this->fieldspec['updateddate']['application'] = 'finance';
         	$this->fieldspec['updateddate']['issearchable'] = '1';
         	$this->fieldspec['updateddate']['preinserttrigger'] = '';
         	$this->fieldspec['updateddate']['postinserttrigger'] = '';
         	$this->fieldspec['updateddate']['preupdatetrigger'] = '';
         	$this->fieldspec['updateddate']['postupdatetrigger'] = '';
         	$this->fieldspec['updateddate']['predeletetrigger'] = '';
         	$this->fieldspec['updateddate']['postdeletetrigger'] = '';
         	$this->fieldspec['updateddate']['definition_version'] = '1';
         	$this->fieldspec['updateddate']['form_javascript'] = '';
         	$this->fieldspec['updateddate']['rowSecurityProc'] = '';
         	$this->fieldspec['updateddate']['postinsert'] = 'PostupdateddateInsert';
         	$this->fieldspec['updateddate']['postupdate'] = 'PostupdateddateUpdate';
         	$this->fieldspec['updateddate']['postdelete'] = 'PostupdateddateDelete';
         	$this->fieldspec['updateddate']['preinsert'] = 'PreupdateddateInsert';
         	$this->fieldspec['updateddate']['preupdate'] = 'PreupdateddateUpdate';
         	$this->fieldspec['updateddate']['predelete'] = 'PreupdateddateDelete';
         	$this->fieldspec['updateduser']['metadata_id'] = '9088';
         	$this->fieldspec['updateduser']['table_name'] = 'candlesticksoccured';
         	$this->fieldspec['updateduser']['column_name'] = 'updateduser';
         	$this->fieldspec['updateduser']['pretty_name'] = 'Record Updated by user';
         	$this->fieldspec['updateduser']['abstract_data_type'] = 'int';
         	$this->fieldspec['updateduser']['db_data_type'] = 'int';
         	$this->fieldspec['updateduser']['field_null'] = 'YES';
         	$this->fieldspec['updateduser']['field_key'] = '';
         	$this->fieldspec['updateduser']['extra_sql'] = ' ';
         	$this->fieldspec['updateduser']['html_form_type'] = 'currentindexuser';
         	$this->fieldspec['updateduser']['html_form_options'] = '<fk><field>username</field></fk>';
         	$this->fieldspec['updateduser']['html_link_options'] = '';
         	$this->fieldspec['updateduser']['html_form_explanation'] = 'Record Updated by user';
         	$this->fieldspec['updateduser']['help_text'] = '';
         	$this->fieldspec['updateduser']['mandatory_p'] = 'N';
         	$this->fieldspec['updateduser']['sort_key'] = '0';
         	$this->fieldspec['updateduser']['form_sort_key'] = '0';
         	$this->fieldspec['updateduser']['form_number'] = '1';
         	$this->fieldspec['updateduser']['default_value'] = '';
         	$this->fieldspec['updateduser']['field_toupper'] = 'NO';
         	$this->fieldspec['updateduser']['validationprocname'] = '';
         	$this->fieldspec['updateduser']['minlength'] = '1';
         	$this->fieldspec['updateduser']['maxlength'] = '11';
         	$this->fieldspec['updateduser']['c_size'] = '11';
         	$this->fieldspec['updateduser']['prikey'] = 'N';
         	$this->fieldspec['updateduser']['noedit'] = 'N';
         	$this->fieldspec['updateduser']['nodisplay'] = 'N';
         	$this->fieldspec['updateduser']['c_unsigned'] = 'N';
         	$this->fieldspec['updateduser']['c_zerofill'] = 'N';
         	$this->fieldspec['updateduser']['c_auto_increment'] = 'N';
         	$this->fieldspec['updateduser']['foreign_table'] = 'users';
         	$this->fieldspec['updateduser']['foreign_key'] = 'idusers';
         	$this->fieldspec['updateduser']['application'] = 'finance';
         	$this->fieldspec['updateduser']['issearchable'] = '1';
         	$this->fieldspec['updateduser']['preinserttrigger'] = '';
         	$this->fieldspec['updateduser']['postinserttrigger'] = '';
         	$this->fieldspec['updateduser']['preupdatetrigger'] = '';
         	$this->fieldspec['updateduser']['postupdatetrigger'] = '';
         	$this->fieldspec['updateduser']['predeletetrigger'] = '';
         	$this->fieldspec['updateduser']['postdeletetrigger'] = '';
         	$this->fieldspec['updateduser']['definition_version'] = '1';
         	$this->fieldspec['updateduser']['form_javascript'] = '';
         	$this->fieldspec['updateduser']['rowSecurityProc'] = '';
         	$this->fieldspec['updateduser']['postinsert'] = 'PostupdateduserInsert';
         	$this->fieldspec['updateduser']['postupdate'] = 'PostupdateduserUpdate';
         	$this->fieldspec['updateduser']['postdelete'] = 'PostupdateduserDelete';
         	$this->fieldspec['updateduser']['preinsert'] = 'PreupdateduserInsert';
         	$this->fieldspec['updateduser']['preupdate'] = 'PreupdateduserUpdate';
         	$this->fieldspec['updateduser']['predelete'] = 'PreupdateduserDelete';
         	$this->fieldspec['symbol']['metadata_id'] = '9089';
         	$this->fieldspec['symbol']['table_name'] = 'candlesticksoccured';
         	$this->fieldspec['symbol']['column_name'] = 'symbol';
         	$this->fieldspec['symbol']['pretty_name'] = 'Stock Symbol';
         	$this->fieldspec['symbol']['abstract_data_type'] = 'varchar';
         	$this->fieldspec['symbol']['db_data_type'] = 'varchar';
         	$this->fieldspec['symbol']['field_null'] = 'YES';
         	$this->fieldspec['symbol']['field_key'] = '';
         	$this->fieldspec['symbol']['extra_sql'] = ' ';
         	$this->fieldspec['symbol']['html_form_type'] = 'varchar';
         	$this->fieldspec['symbol']['html_form_options'] = '';
         	$this->fieldspec['symbol']['html_link_options'] = '';
         	$this->fieldspec['symbol']['html_form_explanation'] = 'Stock Symbol';
         	$this->fieldspec['symbol']['help_text'] = '';
         	$this->fieldspec['symbol']['mandatory_p'] = 'N';
         	$this->fieldspec['symbol']['sort_key'] = '0';
         	$this->fieldspec['symbol']['form_sort_key'] = '0';
         	$this->fieldspec['symbol']['form_number'] = '1';
         	$this->fieldspec['symbol']['default_value'] = '';
         	$this->fieldspec['symbol']['field_toupper'] = 'NO';
         	$this->fieldspec['symbol']['validationprocname'] = '';
         	$this->fieldspec['symbol']['minlength'] = '1';
         	$this->fieldspec['symbol']['maxlength'] = '11';
         	$this->fieldspec['symbol']['c_size'] = '11';
         	$this->fieldspec['symbol']['prikey'] = 'N';
         	$this->fieldspec['symbol']['noedit'] = 'N';
         	$this->fieldspec['symbol']['nodisplay'] = 'N';
         	$this->fieldspec['symbol']['c_unsigned'] = 'N';
         	$this->fieldspec['symbol']['c_zerofill'] = 'N';
         	$this->fieldspec['symbol']['c_auto_increment'] = 'N';
         	$this->fieldspec['symbol']['foreign_table'] = '';
         	$this->fieldspec['symbol']['foreign_key'] = '';
         	$this->fieldspec['symbol']['application'] = 'finance';
         	$this->fieldspec['symbol']['issearchable'] = '1';
         	$this->fieldspec['symbol']['preinserttrigger'] = '';
         	$this->fieldspec['symbol']['postinserttrigger'] = '';
         	$this->fieldspec['symbol']['preupdatetrigger'] = '';
         	$this->fieldspec['symbol']['postupdatetrigger'] = '';
         	$this->fieldspec['symbol']['predeletetrigger'] = '';
         	$this->fieldspec['symbol']['postdeletetrigger'] = '';
         	$this->fieldspec['symbol']['definition_version'] = '1';
         	$this->fieldspec['symbol']['form_javascript'] = '';
         	$this->fieldspec['symbol']['rowSecurityProc'] = '';
         	$this->fieldspec['symbol']['postinsert'] = 'PostsymbolInsert';
         	$this->fieldspec['symbol']['postupdate'] = 'PostsymbolUpdate';
         	$this->fieldspec['symbol']['postdelete'] = 'PostsymbolDelete';
         	$this->fieldspec['symbol']['preinsert'] = 'PresymbolInsert';
         	$this->fieldspec['symbol']['preupdate'] = 'PresymbolUpdate';
         	$this->fieldspec['symbol']['predelete'] = 'PresymbolDelete';
         	$this->fieldspec['date']['metadata_id'] = '9090';
         	$this->fieldspec['date']['table_name'] = 'candlesticksoccured';
         	$this->fieldspec['date']['column_name'] = 'date';
         	$this->fieldspec['date']['pretty_name'] = 'Date in stockprices';
         	$this->fieldspec['date']['abstract_data_type'] = 'date';
         	$this->fieldspec['date']['db_data_type'] = 'date';
         	$this->fieldspec['date']['field_null'] = 'YES';
         	$this->fieldspec['date']['field_key'] = '';
         	$this->fieldspec['date']['extra_sql'] = ' ';
         	$this->fieldspec['date']['html_form_type'] = 'dateselect';
         	$this->fieldspec['date']['html_form_options'] = '';
         	$this->fieldspec['date']['html_link_options'] = '';
         	$this->fieldspec['date']['html_form_explanation'] = 'Date in stockprices';
         	$this->fieldspec['date']['help_text'] = '';
         	$this->fieldspec['date']['mandatory_p'] = 'N';
         	$this->fieldspec['date']['sort_key'] = '0';
         	$this->fieldspec['date']['form_sort_key'] = '0';
         	$this->fieldspec['date']['form_number'] = '1';
         	$this->fieldspec['date']['default_value'] = '';
         	$this->fieldspec['date']['field_toupper'] = 'NO';
         	$this->fieldspec['date']['validationprocname'] = '';
         	$this->fieldspec['date']['minlength'] = '1';
         	$this->fieldspec['date']['maxlength'] = '0';
         	$this->fieldspec['date']['c_size'] = '11';
         	$this->fieldspec['date']['prikey'] = 'N';
         	$this->fieldspec['date']['noedit'] = 'N';
         	$this->fieldspec['date']['nodisplay'] = 'N';
         	$this->fieldspec['date']['c_unsigned'] = 'N';
         	$this->fieldspec['date']['c_zerofill'] = 'N';
         	$this->fieldspec['date']['c_auto_increment'] = 'N';
         	$this->fieldspec['date']['foreign_table'] = '';
         	$this->fieldspec['date']['foreign_key'] = '';
         	$this->fieldspec['date']['application'] = 'finance';
         	$this->fieldspec['date']['issearchable'] = '1';
         	$this->fieldspec['date']['preinserttrigger'] = '';
         	$this->fieldspec['date']['postinserttrigger'] = '';
         	$this->fieldspec['date']['preupdatetrigger'] = '';
         	$this->fieldspec['date']['postupdatetrigger'] = '';
         	$this->fieldspec['date']['predeletetrigger'] = '';
         	$this->fieldspec['date']['postdeletetrigger'] = '';
         	$this->fieldspec['date']['definition_version'] = '1';
         	$this->fieldspec['date']['form_javascript'] = '';
         	$this->fieldspec['date']['rowSecurityProc'] = '';
         	$this->fieldspec['date']['postinsert'] = 'PostdateInsert';
         	$this->fieldspec['date']['postupdate'] = 'PostdateUpdate';
         	$this->fieldspec['date']['postdelete'] = 'PostdateDelete';
         	$this->fieldspec['date']['preinsert'] = 'PredateInsert';
         	$this->fieldspec['date']['preupdate'] = 'PredateUpdate';
         	$this->fieldspec['date']['predelete'] = 'PredateDelete';
         	$this->fieldspec['candlestick']['metadata_id'] = '9091';
         	$this->fieldspec['candlestick']['table_name'] = 'candlesticksoccured';
         	$this->fieldspec['candlestick']['column_name'] = 'candlestick';
         	$this->fieldspec['candlestick']['pretty_name'] = 'Candlestick Identified for this date';
         	$this->fieldspec['candlestick']['abstract_data_type'] = 'varchar';
         	$this->fieldspec['candlestick']['db_data_type'] = 'varchar';
         	$this->fieldspec['candlestick']['field_null'] = 'YES';
         	$this->fieldspec['candlestick']['field_key'] = '';
         	$this->fieldspec['candlestick']['extra_sql'] = ' ';
         	$this->fieldspec['candlestick']['html_form_type'] = 'varchar';
         	$this->fieldspec['candlestick']['html_form_options'] = '';
         	$this->fieldspec['candlestick']['html_link_options'] = '';
         	$this->fieldspec['candlestick']['html_form_explanation'] = 'Candlestick Identified for this date';
         	$this->fieldspec['candlestick']['help_text'] = '';
         	$this->fieldspec['candlestick']['mandatory_p'] = 'N';
         	$this->fieldspec['candlestick']['sort_key'] = '0';
         	$this->fieldspec['candlestick']['form_sort_key'] = '0';
         	$this->fieldspec['candlestick']['form_number'] = '1';
         	$this->fieldspec['candlestick']['default_value'] = '';
         	$this->fieldspec['candlestick']['field_toupper'] = 'NO';
         	$this->fieldspec['candlestick']['validationprocname'] = '';
         	$this->fieldspec['candlestick']['minlength'] = '1';
         	$this->fieldspec['candlestick']['maxlength'] = '255';
         	$this->fieldspec['candlestick']['c_size'] = '255';
         	$this->fieldspec['candlestick']['prikey'] = 'N';
         	$this->fieldspec['candlestick']['noedit'] = 'N';
         	$this->fieldspec['candlestick']['nodisplay'] = 'N';
         	$this->fieldspec['candlestick']['c_unsigned'] = 'N';
         	$this->fieldspec['candlestick']['c_zerofill'] = 'N';
         	$this->fieldspec['candlestick']['c_auto_increment'] = 'N';
         	$this->fieldspec['candlestick']['foreign_table'] = '';
         	$this->fieldspec['candlestick']['foreign_key'] = '';
         	$this->fieldspec['candlestick']['application'] = 'finance';
         	$this->fieldspec['candlestick']['issearchable'] = '1';
         	$this->fieldspec['candlestick']['preinserttrigger'] = '';
         	$this->fieldspec['candlestick']['postinserttrigger'] = '';
         	$this->fieldspec['candlestick']['preupdatetrigger'] = '';
         	$this->fieldspec['candlestick']['postupdatetrigger'] = '';
         	$this->fieldspec['candlestick']['predeletetrigger'] = '';
         	$this->fieldspec['candlestick']['postdeletetrigger'] = '';
         	$this->fieldspec['candlestick']['definition_version'] = '1';
         	$this->fieldspec['candlestick']['form_javascript'] = '';
         	$this->fieldspec['candlestick']['rowSecurityProc'] = '';
         	$this->fieldspec['candlestick']['postinsert'] = 'PostcandlestickInsert';
         	$this->fieldspec['candlestick']['postupdate'] = 'PostcandlestickUpdate';
         	$this->fieldspec['candlestick']['postdelete'] = 'PostcandlestickDelete';
         	$this->fieldspec['candlestick']['preinsert'] = 'PrecandlestickInsert';
         	$this->fieldspec['candlestick']['preupdate'] = 'PrecandlestickUpdate';
         	$this->fieldspec['candlestick']['predelete'] = 'PrecandlestickDelete';
         	$this->fieldlist = array('idcandlesticksoccured', 'createddate', 'createduser', 'updateddate', 'updateduser', 'symbol', 'date', 'candlestick');
         	$this->searchlist = array('idcandlesticksoccured', 'createddate', 'createduser', 'updateddate', 'updateduser', 'symbol', 'date', 'candlestick');
         	$this->prikeylist = array('idcandlesticksoccured');
		$this->defaultsort = '';
	         return SUCCESS;
         }
         /*void*/ function  candlesticksoccured()
         { //For older php which doesn't have constructor
              return $this->__construct();
         }
         /*@bool@*//*int*/ function Push()
         {
	         $_SESSION['candlesticksoccured'] = serialize($this);
	         return SUCCESS;
         }
         /*@bool@*//*int*/ function Pop()
         {
                 //Can't do this in self - this is how to do it outside
	       //  $this = unserialize($_SESSION['candlesticksoccured']);
	         return SUCCESS;
         }
         /********************************************************************
         *	@function ObserverRegister
         *	@param class observer 
         *	@param string event 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function ObserverRegister(  $observer,  $event )
         {
                 $this->observers[$event][] = $observer;
	         return SUCCESS;
         }
         /********************************************************************
         *	@function ObserverDeRegister
         *	@param class observer
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function ObserverDeRegister( $observer )
         {
                 $this->observers[] = array_diff( $this->observers, array( $observer) );
	         return SUCCESS;
         }
         /********************************************************************
         *	@function ObserverNotify
         *	@param string event
         *	@param string msg 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function ObserverNotify(  $event,  $msg )
         {
                 if ( isset( $this->observers[$event] ) )
                 	foreach ( $this->observers[$event] as $obs ) 
                 	{
                      		$obs->notify( $event, $msg );
                 	}
                 /* '**' being used as 'ALL' */
                 if ( isset( $this->observers['**'] ) )
                 	foreach ( $this->observers['**'] as $obs ) 
                 	{
                      		$obs->notify( $event, $msg );
                 	}
	         return SUCCESS;
         }
         /********************************************************************
         *	@function notify
         *	@param class object 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function notify(  $object )
         {
                 //Called when another object we are observing sends us a notification
	         return SUCCESS;
         }
         /********************************************************************
         *	@function PreidcandlesticksoccuredInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreidcandlesticksoccuredInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PreidcandlesticksoccuredInsert ) )
	            return $this->candlesticksoccured_PreidcandlesticksoccuredInsert( $this );
                 else if ( is_callable( candlesticksoccured_PreidcandlesticksoccuredInsert ) )
	            return candlesticksoccured_PreidcandlesticksoccuredInsert( $this );
                 else if ( is_callable( PreidcandlesticksoccuredInsert ) )
	            return PreidcandlesticksoccuredInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostidcandlesticksoccuredInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostidcandlesticksoccuredInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostidcandlesticksoccuredInsert ) )
	            $returnval =  $this->candlesticksoccured_PostidcandlesticksoccuredInsert( $this );
                 else if ( is_callable( candlesticksoccured_PostidcandlesticksoccuredInsert ) )
	            $returnval =  candlesticksoccured_PostidcandlesticksoccuredInsert( $this );
                 else if ( is_callable( PostidcandlesticksoccuredInsert ) )
	            $returnval =  PostidcandlesticksoccuredInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "idcandlesticksoccured" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PreidcandlesticksoccuredUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreidcandlesticksoccuredUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PreidcandlesticksoccuredUpdate ) )
	            return $this->candlesticksoccured_PreidcandlesticksoccuredUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PreidcandlesticksoccuredUpdate ) )
	            return candlesticksoccured_PreidcandlesticksoccuredUpdate( $this );
                 else if ( is_callable( PreidcandlesticksoccuredUpdate ) )
	            return PreidcandlesticksoccuredUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostidcandlesticksoccuredUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostidcandlesticksoccuredUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostidcandlesticksoccuredUpdate ) )
	            $returnval =  $this->candlesticksoccured_PostidcandlesticksoccuredUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PostidcandlesticksoccuredUpdate ) )
	            $returnval =  candlesticksoccured_PostidcandlesticksoccuredUpdate( $this );
                 else if ( is_callable( PostidcandlesticksoccuredUpdate ) )
	            $returnval =  PostidcandlesticksoccuredUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "idcandlesticksoccured" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PreidcandlesticksoccuredDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreidcandlesticksoccuredDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PreidcandlesticksoccuredDelete ) )
	            return $this->candlesticksoccured_PreidcandlesticksoccuredDelete( $this );
                 else if ( is_callable( candlesticksoccured_PreidcandlesticksoccuredDelete ) )
	            return candlesticksoccured_PreidcandlesticksoccuredDelete( $this );
                 else if ( is_callable( PreidcandlesticksoccuredDelete ) )
	            return PreidcandlesticksoccuredDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostidcandlesticksoccuredDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostidcandlesticksoccuredDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostidcandlesticksoccuredDelete ) )
	            $returnval =  $this->candlesticksoccured_PostidcandlesticksoccuredDelete( $this );
                 else if ( is_callable( candlesticksoccured_PostidcandlesticksoccuredDelete ) )
	            $returnval =  candlesticksoccured_PostidcandlesticksoccuredDelete( $this );
                 else if ( is_callable( PostidcandlesticksoccuredDelete ) )
	            $returnval =  PostidcandlesticksoccuredDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "idcandlesticksoccured" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setidcandlesticksoccured
         *	@param int  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setidcandlesticksoccured(  $value )
         {
                 $this->idcandlesticksoccured = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getidcandlesticksoccured
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*@int@*//*int*/ function Getidcandlesticksoccured()
         {
                    return $this->idcandlesticksoccured;
         }
         /********************************************************************
         *	@function PrecreateddateInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecreateddateInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PrecreateddateInsert ) )
	            return $this->candlesticksoccured_PrecreateddateInsert( $this );
                 else if ( is_callable( candlesticksoccured_PrecreateddateInsert ) )
	            return candlesticksoccured_PrecreateddateInsert( $this );
                 else if ( is_callable( PrecreateddateInsert ) )
	            return PrecreateddateInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcreateddateInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcreateddateInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostcreateddateInsert ) )
	            $returnval =  $this->candlesticksoccured_PostcreateddateInsert( $this );
                 else if ( is_callable( candlesticksoccured_PostcreateddateInsert ) )
	            $returnval =  candlesticksoccured_PostcreateddateInsert( $this );
                 else if ( is_callable( PostcreateddateInsert ) )
	            $returnval =  PostcreateddateInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "createddate" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PrecreateddateUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecreateddateUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PrecreateddateUpdate ) )
	            return $this->candlesticksoccured_PrecreateddateUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PrecreateddateUpdate ) )
	            return candlesticksoccured_PrecreateddateUpdate( $this );
                 else if ( is_callable( PrecreateddateUpdate ) )
	            return PrecreateddateUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcreateddateUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcreateddateUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostcreateddateUpdate ) )
	            $returnval =  $this->candlesticksoccured_PostcreateddateUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PostcreateddateUpdate ) )
	            $returnval =  candlesticksoccured_PostcreateddateUpdate( $this );
                 else if ( is_callable( PostcreateddateUpdate ) )
	            $returnval =  PostcreateddateUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "createddate" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PrecreateddateDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecreateddateDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PrecreateddateDelete ) )
	            return $this->candlesticksoccured_PrecreateddateDelete( $this );
                 else if ( is_callable( candlesticksoccured_PrecreateddateDelete ) )
	            return candlesticksoccured_PrecreateddateDelete( $this );
                 else if ( is_callable( PrecreateddateDelete ) )
	            return PrecreateddateDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcreateddateDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcreateddateDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostcreateddateDelete ) )
	            $returnval =  $this->candlesticksoccured_PostcreateddateDelete( $this );
                 else if ( is_callable( candlesticksoccured_PostcreateddateDelete ) )
	            $returnval =  candlesticksoccured_PostcreateddateDelete( $this );
                 else if ( is_callable( PostcreateddateDelete ) )
	            $returnval =  PostcreateddateDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "createddate" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setcreateddate
         *	@param datetime  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setcreateddate(  $value )
         {
                 $this->createddate = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getcreateddate
         *	@param 
         *	@see 
         *	@return datetime
         ********************************************************************/
         /*@datetime@*//*int*/ function Getcreateddate()
         {
                    return $this->createddate;
         }
         /********************************************************************
         *	@function PrecreateduserInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecreateduserInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PrecreateduserInsert ) )
	            return $this->candlesticksoccured_PrecreateduserInsert( $this );
                 else if ( is_callable( candlesticksoccured_PrecreateduserInsert ) )
	            return candlesticksoccured_PrecreateduserInsert( $this );
                 else if ( is_callable( PrecreateduserInsert ) )
	            return PrecreateduserInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcreateduserInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcreateduserInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostcreateduserInsert ) )
	            $returnval =  $this->candlesticksoccured_PostcreateduserInsert( $this );
                 else if ( is_callable( candlesticksoccured_PostcreateduserInsert ) )
	            $returnval =  candlesticksoccured_PostcreateduserInsert( $this );
                 else if ( is_callable( PostcreateduserInsert ) )
	            $returnval =  PostcreateduserInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "createduser" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PrecreateduserUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecreateduserUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PrecreateduserUpdate ) )
	            return $this->candlesticksoccured_PrecreateduserUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PrecreateduserUpdate ) )
	            return candlesticksoccured_PrecreateduserUpdate( $this );
                 else if ( is_callable( PrecreateduserUpdate ) )
	            return PrecreateduserUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcreateduserUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcreateduserUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostcreateduserUpdate ) )
	            $returnval =  $this->candlesticksoccured_PostcreateduserUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PostcreateduserUpdate ) )
	            $returnval =  candlesticksoccured_PostcreateduserUpdate( $this );
                 else if ( is_callable( PostcreateduserUpdate ) )
	            $returnval =  PostcreateduserUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "createduser" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PrecreateduserDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecreateduserDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PrecreateduserDelete ) )
	            return $this->candlesticksoccured_PrecreateduserDelete( $this );
                 else if ( is_callable( candlesticksoccured_PrecreateduserDelete ) )
	            return candlesticksoccured_PrecreateduserDelete( $this );
                 else if ( is_callable( PrecreateduserDelete ) )
	            return PrecreateduserDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcreateduserDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcreateduserDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostcreateduserDelete ) )
	            $returnval =  $this->candlesticksoccured_PostcreateduserDelete( $this );
                 else if ( is_callable( candlesticksoccured_PostcreateduserDelete ) )
	            $returnval =  candlesticksoccured_PostcreateduserDelete( $this );
                 else if ( is_callable( PostcreateduserDelete ) )
	            $returnval =  PostcreateduserDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "createduser" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setcreateduser
         *	@param int  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setcreateduser(  $value )
         {
                 $this->createduser = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getcreateduser
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*@int@*//*int*/ function Getcreateduser()
         {
                    return $this->createduser;
         }
         /********************************************************************
         *	@function PreupdateddateInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreupdateddateInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PreupdateddateInsert ) )
	            return $this->candlesticksoccured_PreupdateddateInsert( $this );
                 else if ( is_callable( candlesticksoccured_PreupdateddateInsert ) )
	            return candlesticksoccured_PreupdateddateInsert( $this );
                 else if ( is_callable( PreupdateddateInsert ) )
	            return PreupdateddateInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostupdateddateInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostupdateddateInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostupdateddateInsert ) )
	            $returnval =  $this->candlesticksoccured_PostupdateddateInsert( $this );
                 else if ( is_callable( candlesticksoccured_PostupdateddateInsert ) )
	            $returnval =  candlesticksoccured_PostupdateddateInsert( $this );
                 else if ( is_callable( PostupdateddateInsert ) )
	            $returnval =  PostupdateddateInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "updateddate" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PreupdateddateUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreupdateddateUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PreupdateddateUpdate ) )
	            return $this->candlesticksoccured_PreupdateddateUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PreupdateddateUpdate ) )
	            return candlesticksoccured_PreupdateddateUpdate( $this );
                 else if ( is_callable( PreupdateddateUpdate ) )
	            return PreupdateddateUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostupdateddateUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostupdateddateUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostupdateddateUpdate ) )
	            $returnval =  $this->candlesticksoccured_PostupdateddateUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PostupdateddateUpdate ) )
	            $returnval =  candlesticksoccured_PostupdateddateUpdate( $this );
                 else if ( is_callable( PostupdateddateUpdate ) )
	            $returnval =  PostupdateddateUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "updateddate" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PreupdateddateDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreupdateddateDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PreupdateddateDelete ) )
	            return $this->candlesticksoccured_PreupdateddateDelete( $this );
                 else if ( is_callable( candlesticksoccured_PreupdateddateDelete ) )
	            return candlesticksoccured_PreupdateddateDelete( $this );
                 else if ( is_callable( PreupdateddateDelete ) )
	            return PreupdateddateDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostupdateddateDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostupdateddateDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostupdateddateDelete ) )
	            $returnval =  $this->candlesticksoccured_PostupdateddateDelete( $this );
                 else if ( is_callable( candlesticksoccured_PostupdateddateDelete ) )
	            $returnval =  candlesticksoccured_PostupdateddateDelete( $this );
                 else if ( is_callable( PostupdateddateDelete ) )
	            $returnval =  PostupdateddateDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "updateddate" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setupdateddate
         *	@param timestamp  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setupdateddate(  $value )
         {
                 $this->updateddate = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getupdateddate
         *	@param 
         *	@see 
         *	@return timestamp
         ********************************************************************/
         /*@timestamp@*//*int*/ function Getupdateddate()
         {
                    return $this->updateddate;
         }
         /********************************************************************
         *	@function PreupdateduserInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreupdateduserInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PreupdateduserInsert ) )
	            return $this->candlesticksoccured_PreupdateduserInsert( $this );
                 else if ( is_callable( candlesticksoccured_PreupdateduserInsert ) )
	            return candlesticksoccured_PreupdateduserInsert( $this );
                 else if ( is_callable( PreupdateduserInsert ) )
	            return PreupdateduserInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostupdateduserInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostupdateduserInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostupdateduserInsert ) )
	            $returnval =  $this->candlesticksoccured_PostupdateduserInsert( $this );
                 else if ( is_callable( candlesticksoccured_PostupdateduserInsert ) )
	            $returnval =  candlesticksoccured_PostupdateduserInsert( $this );
                 else if ( is_callable( PostupdateduserInsert ) )
	            $returnval =  PostupdateduserInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "updateduser" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PreupdateduserUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreupdateduserUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PreupdateduserUpdate ) )
	            return $this->candlesticksoccured_PreupdateduserUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PreupdateduserUpdate ) )
	            return candlesticksoccured_PreupdateduserUpdate( $this );
                 else if ( is_callable( PreupdateduserUpdate ) )
	            return PreupdateduserUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostupdateduserUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostupdateduserUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostupdateduserUpdate ) )
	            $returnval =  $this->candlesticksoccured_PostupdateduserUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PostupdateduserUpdate ) )
	            $returnval =  candlesticksoccured_PostupdateduserUpdate( $this );
                 else if ( is_callable( PostupdateduserUpdate ) )
	            $returnval =  PostupdateduserUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "updateduser" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PreupdateduserDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreupdateduserDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PreupdateduserDelete ) )
	            return $this->candlesticksoccured_PreupdateduserDelete( $this );
                 else if ( is_callable( candlesticksoccured_PreupdateduserDelete ) )
	            return candlesticksoccured_PreupdateduserDelete( $this );
                 else if ( is_callable( PreupdateduserDelete ) )
	            return PreupdateduserDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostupdateduserDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostupdateduserDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostupdateduserDelete ) )
	            $returnval =  $this->candlesticksoccured_PostupdateduserDelete( $this );
                 else if ( is_callable( candlesticksoccured_PostupdateduserDelete ) )
	            $returnval =  candlesticksoccured_PostupdateduserDelete( $this );
                 else if ( is_callable( PostupdateduserDelete ) )
	            $returnval =  PostupdateduserDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "updateduser" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setupdateduser
         *	@param int  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setupdateduser(  $value )
         {
                 $this->updateduser = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getupdateduser
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*@int@*//*int*/ function Getupdateduser()
         {
                    return $this->updateduser;
         }
         /********************************************************************
         *	@function PresymbolInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PresymbolInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PresymbolInsert ) )
	            return $this->candlesticksoccured_PresymbolInsert( $this );
                 else if ( is_callable( candlesticksoccured_PresymbolInsert ) )
	            return candlesticksoccured_PresymbolInsert( $this );
                 else if ( is_callable( PresymbolInsert ) )
	            return PresymbolInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostsymbolInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostsymbolInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostsymbolInsert ) )
	            $returnval =  $this->candlesticksoccured_PostsymbolInsert( $this );
                 else if ( is_callable( candlesticksoccured_PostsymbolInsert ) )
	            $returnval =  candlesticksoccured_PostsymbolInsert( $this );
                 else if ( is_callable( PostsymbolInsert ) )
	            $returnval =  PostsymbolInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "symbol" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PresymbolUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PresymbolUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PresymbolUpdate ) )
	            return $this->candlesticksoccured_PresymbolUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PresymbolUpdate ) )
	            return candlesticksoccured_PresymbolUpdate( $this );
                 else if ( is_callable( PresymbolUpdate ) )
	            return PresymbolUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostsymbolUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostsymbolUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostsymbolUpdate ) )
	            $returnval =  $this->candlesticksoccured_PostsymbolUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PostsymbolUpdate ) )
	            $returnval =  candlesticksoccured_PostsymbolUpdate( $this );
                 else if ( is_callable( PostsymbolUpdate ) )
	            $returnval =  PostsymbolUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "symbol" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PresymbolDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PresymbolDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PresymbolDelete ) )
	            return $this->candlesticksoccured_PresymbolDelete( $this );
                 else if ( is_callable( candlesticksoccured_PresymbolDelete ) )
	            return candlesticksoccured_PresymbolDelete( $this );
                 else if ( is_callable( PresymbolDelete ) )
	            return PresymbolDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostsymbolDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostsymbolDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostsymbolDelete ) )
	            $returnval =  $this->candlesticksoccured_PostsymbolDelete( $this );
                 else if ( is_callable( candlesticksoccured_PostsymbolDelete ) )
	            $returnval =  candlesticksoccured_PostsymbolDelete( $this );
                 else if ( is_callable( PostsymbolDelete ) )
	            $returnval =  PostsymbolDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "symbol" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setsymbol
         *	@param varchar  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setsymbol(  $value )
         {
                 $this->symbol = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getsymbol
         *	@param 
         *	@see 
         *	@return varchar
         ********************************************************************/
         /*@varchar@*//*int*/ function Getsymbol()
         {
                    return $this->symbol;
         }
         /********************************************************************
         *	@function PredateInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PredateInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PredateInsert ) )
	            return $this->candlesticksoccured_PredateInsert( $this );
                 else if ( is_callable( candlesticksoccured_PredateInsert ) )
	            return candlesticksoccured_PredateInsert( $this );
                 else if ( is_callable( PredateInsert ) )
	            return PredateInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostdateInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostdateInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostdateInsert ) )
	            $returnval =  $this->candlesticksoccured_PostdateInsert( $this );
                 else if ( is_callable( candlesticksoccured_PostdateInsert ) )
	            $returnval =  candlesticksoccured_PostdateInsert( $this );
                 else if ( is_callable( PostdateInsert ) )
	            $returnval =  PostdateInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "date" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PredateUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PredateUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PredateUpdate ) )
	            return $this->candlesticksoccured_PredateUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PredateUpdate ) )
	            return candlesticksoccured_PredateUpdate( $this );
                 else if ( is_callable( PredateUpdate ) )
	            return PredateUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostdateUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostdateUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostdateUpdate ) )
	            $returnval =  $this->candlesticksoccured_PostdateUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PostdateUpdate ) )
	            $returnval =  candlesticksoccured_PostdateUpdate( $this );
                 else if ( is_callable( PostdateUpdate ) )
	            $returnval =  PostdateUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "date" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PredateDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PredateDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PredateDelete ) )
	            return $this->candlesticksoccured_PredateDelete( $this );
                 else if ( is_callable( candlesticksoccured_PredateDelete ) )
	            return candlesticksoccured_PredateDelete( $this );
                 else if ( is_callable( PredateDelete ) )
	            return PredateDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostdateDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostdateDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostdateDelete ) )
	            $returnval =  $this->candlesticksoccured_PostdateDelete( $this );
                 else if ( is_callable( candlesticksoccured_PostdateDelete ) )
	            $returnval =  candlesticksoccured_PostdateDelete( $this );
                 else if ( is_callable( PostdateDelete ) )
	            $returnval =  PostdateDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "date" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setdate
         *	@param date  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setdate(  $value )
         {
                 $this->date = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getdate
         *	@param 
         *	@see 
         *	@return date
         ********************************************************************/
         /*@date@*//*int*/ function Getdate()
         {
                    return $this->date;
         }
         /********************************************************************
         *	@function PrecandlestickInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecandlestickInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PrecandlestickInsert ) )
	            return $this->candlesticksoccured_PrecandlestickInsert( $this );
                 else if ( is_callable( candlesticksoccured_PrecandlestickInsert ) )
	            return candlesticksoccured_PrecandlestickInsert( $this );
                 else if ( is_callable( PrecandlestickInsert ) )
	            return PrecandlestickInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcandlestickInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcandlestickInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostcandlestickInsert ) )
	            $returnval =  $this->candlesticksoccured_PostcandlestickInsert( $this );
                 else if ( is_callable( candlesticksoccured_PostcandlestickInsert ) )
	            $returnval =  candlesticksoccured_PostcandlestickInsert( $this );
                 else if ( is_callable( PostcandlestickInsert ) )
	            $returnval =  PostcandlestickInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "candlestick" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PrecandlestickUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecandlestickUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PrecandlestickUpdate ) )
	            return $this->candlesticksoccured_PrecandlestickUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PrecandlestickUpdate ) )
	            return candlesticksoccured_PrecandlestickUpdate( $this );
                 else if ( is_callable( PrecandlestickUpdate ) )
	            return PrecandlestickUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcandlestickUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcandlestickUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostcandlestickUpdate ) )
	            $returnval =  $this->candlesticksoccured_PostcandlestickUpdate( $this );
                 else if ( is_callable( candlesticksoccured_PostcandlestickUpdate ) )
	            $returnval =  candlesticksoccured_PostcandlestickUpdate( $this );
                 else if ( is_callable( PostcandlestickUpdate ) )
	            $returnval =  PostcandlestickUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "candlestick" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PrecandlestickDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecandlestickDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PrecandlestickDelete ) )
	            return $this->candlesticksoccured_PrecandlestickDelete( $this );
                 else if ( is_callable( candlesticksoccured_PrecandlestickDelete ) )
	            return candlesticksoccured_PrecandlestickDelete( $this );
                 else if ( is_callable( PrecandlestickDelete ) )
	            return PrecandlestickDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcandlestickDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcandlestickDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlesticksoccured_PostcandlestickDelete ) )
	            $returnval =  $this->candlesticksoccured_PostcandlestickDelete( $this );
                 else if ( is_callable( candlesticksoccured_PostcandlestickDelete ) )
	            $returnval =  candlesticksoccured_PostcandlestickDelete( $this );
                 else if ( is_callable( PostcandlestickDelete ) )
	            $returnval =  PostcandlestickDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "candlestick" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setcandlestick
         *	@param varchar  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setcandlestick(  $value )
         {
                 $this->candlestick = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getcandlestick
         *	@param 
         *	@see 
         *	@return varchar
         ********************************************************************/
         /*@varchar@*//*int*/ function Getcandlestick()
         {
                    return $this->candlestick;
         }
} /* class candlesticksoccured */

require_once( 'DB/Table/Database.php' );;

class candlesticksoccured_table extends DB_Table
{
	var $col = array(
	'idcandlesticksoccured' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'createddate' => array( 'type'=>'datetime', 'require'=>false, 'size' =>'11' ),
	'createduser' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'updateddate' => array( 'type'=>'timestamp', 'require'=>false, 'size' =>'11' ),
	'updateduser' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'symbol' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	'date' => array( 'type'=>'date', 'require'=>false, 'size' =>'11' ),
	'candlestick' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'255' ),
	);
};
require_once( 'DB/DataObject.php' );;

class candlesticksoccured_object extends DB_DataObject
{
	var $__table='candlesticksoccured';
		//This is a Structures/DataGrid object
	var $idcandlesticksoccured;
	var $createddate;
	var $createduser;
	var $updateddate;
	var $updateduser;
	var $symbol;
	var $date;
	var $candlestick;
};
/*	view/QuickFormIncludes and TabbedPages.php are in the skel-app/view if required	*/
require_once( 'view/QuickFormIncludes.php' );;
require_once( 'view/TabbedPages.php' );;

class candlesticksoccured_Page1 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('candlesticksoccured page 1');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('submit', 'empty.gif');
		$this->addGlobalSubmit();
		$idcandlesticksoccured = $fs->addElement('text', 'idcandlesticksoccured', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Index' )
;
		$createddate = $fs->addElement('text', 'createddate', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Record Created Date' )
			->addFilter( 'trim' )
;
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'createduser' => $_SERVER['PHP_AUTH_USER'] ) ) );
		$createduser = $fs->addElement('text', 'createduser', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Record Created by User' )
			->addFilter( 'trim' )
;
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'updateduser' => $_SERVER['PHP_AUTH_USER'] ) ) );
		$updateduser = $fs->addElement('text', 'updateduser', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Record Updated by user' )
			->addFilter( 'trim' )
;
		$symbol = $fs->addElement('text', 'symbol', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Stock Symbol' )
			->addFilter( 'trim' )
;
		$f_date = date("Y-m-d" );
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'date' => $f_date ) ) );
		$date = $fs->addElement('text', 'date', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Date in stockprices' )
			->addFilter( 'trim' )
;
		$candlestick = $fs->addElement('text', 'candlestick', array('size' => 255, 'maxlength' => 255) )
			->setLabel( 'Candlestick Identified for this date' )
			->addFilter( 'trim' )
;
	}
}
?>