<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

class candlestickdates extends generictable 
{
	/*char * */ var $pretty_name = '';
	/*char * */ var $pretty_plural = '';
	/*char * */ var $pageheader = '';
	/*char * */ var $pagefooter = '';
         private $observers;
	/*char * */ var $data; //data passed in by other calls
/********************************************************
 *
 *	This section is the table columns
 *
 *******************************************************/
         var          /*char* *//* date */ $candlestickdates;
		 /*The dates for which candlesticks have been calculated */
         function __construct()
         {
         	$this->querytablename = 'candlestickdates';
         	$this->classname = 'candlestickdates';
         	$this->fieldspec['candlestickdates']['metadata_id'] = '6797';
         	$this->fieldspec['candlestickdates']['table_name'] = 'candlestickdates';
         	$this->fieldspec['candlestickdates']['column_name'] = 'candlestickdates';
         	$this->fieldspec['candlestickdates']['pretty_name'] = 'The dates for which candlesticks have been calculated';
         	$this->fieldspec['candlestickdates']['abstract_data_type'] = 'date';
         	$this->fieldspec['candlestickdates']['db_data_type'] = 'date';
         	$this->fieldspec['candlestickdates']['field_null'] = 'YES';
         	$this->fieldspec['candlestickdates']['field_key'] = '';
         	$this->fieldspec['candlestickdates']['extra_sql'] = ' ';
         	$this->fieldspec['candlestickdates']['html_form_type'] = 'date';
         	$this->fieldspec['candlestickdates']['html_form_options'] = '';
         	$this->fieldspec['candlestickdates']['html_link_options'] = '';
         	$this->fieldspec['candlestickdates']['html_form_explanation'] = 'The dates for which candlesticks have been calculated';
         	$this->fieldspec['candlestickdates']['help_text'] = '';
         	$this->fieldspec['candlestickdates']['mandatory_p'] = 'N';
         	$this->fieldspec['candlestickdates']['sort_key'] = '0';
         	$this->fieldspec['candlestickdates']['form_sort_key'] = '0';
         	$this->fieldspec['candlestickdates']['form_number'] = '1';
         	$this->fieldspec['candlestickdates']['default_value'] = '';
         	$this->fieldspec['candlestickdates']['field_toupper'] = 'NO';
         	$this->fieldspec['candlestickdates']['validationprocname'] = '';
         	$this->fieldspec['candlestickdates']['minlength'] = '1';
         	$this->fieldspec['candlestickdates']['maxlength'] = '11';
         	$this->fieldspec['candlestickdates']['c_size'] = '11';
         	$this->fieldspec['candlestickdates']['prikey'] = 'Y';
         	$this->fieldspec['candlestickdates']['noedit'] = 'Y';
         	$this->fieldspec['candlestickdates']['nodisplay'] = 'Y';
         	$this->fieldspec['candlestickdates']['c_unsigned'] = 'N';
         	$this->fieldspec['candlestickdates']['c_zerofill'] = 'N';
         	$this->fieldspec['candlestickdates']['c_auto_increment'] = 'N';
         	$this->fieldspec['candlestickdates']['foreign_table'] = '';
         	$this->fieldspec['candlestickdates']['foreign_key'] = '';
         	$this->fieldspec['candlestickdates']['application'] = 'finance';
         	$this->fieldspec['candlestickdates']['issearchable'] = '1';
         	$this->fieldspec['candlestickdates']['preinserttrigger'] = '';
         	$this->fieldspec['candlestickdates']['postinserttrigger'] = '';
         	$this->fieldspec['candlestickdates']['preupdatetrigger'] = '';
         	$this->fieldspec['candlestickdates']['postupdatetrigger'] = '';
         	$this->fieldspec['candlestickdates']['predeletetrigger'] = '';
         	$this->fieldspec['candlestickdates']['postdeletetrigger'] = '';
         	$this->fieldspec['candlestickdates']['definition_version'] = '1';
         	$this->fieldspec['candlestickdates']['form_javascript'] = '';
         	$this->fieldspec['candlestickdates']['rowSecurityProc'] = '';
         	$this->fieldspec['candlestickdates']['postinsert'] = 'PostcandlestickdatesInsert';
         	$this->fieldspec['candlestickdates']['postupdate'] = 'PostcandlestickdatesUpdate';
         	$this->fieldspec['candlestickdates']['postdelete'] = 'PostcandlestickdatesDelete';
         	$this->fieldspec['candlestickdates']['preinsert'] = 'PrecandlestickdatesInsert';
         	$this->fieldspec['candlestickdates']['preupdate'] = 'PrecandlestickdatesUpdate';
         	$this->fieldspec['candlestickdates']['predelete'] = 'PrecandlestickdatesDelete';
         	$this->fieldlist = array('candlestickdates');
         	$this->searchlist = array('candlestickdates');
         	$this->prikeylist = array('candlestickdates');
		$this->defaultsort = '';
	         return SUCCESS;
         }
         /*void*/ function  candlestickdates()
         { //For older php which doesn't have constructor
              return $this->__construct();
         }
         /*@bool@*//*int*/ function Push()
         {
	         $_SESSION['candlestickdates'] = serialize($this);
	         return SUCCESS;
         }
         /*@bool@*//*int*/ function Pop()
         {
                 //Can't do this in self - this is how to do it outside
	       //  $this = unserialize($_SESSION['candlestickdates']);
	         return SUCCESS;
         }
         /********************************************************************
         *	@function ObserverRegister
         *	@param class observer 
         *	@param string event 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function ObserverRegister(  $observer,  $event )
         {
                 $this->observers[$event][] = $observer;
	         return SUCCESS;
         }
         /********************************************************************
         *	@function ObserverDeRegister
         *	@param class observer
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function ObserverDeRegister( $observer )
         {
                 $this->observers[] = array_diff( $this->observers, array( $observer) );
	         return SUCCESS;
         }
         /********************************************************************
         *	@function ObserverNotify
         *	@param string event
         *	@param string msg 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function ObserverNotify(  $event,  $msg )
         {
                 if ( isset( $this->observers[$event] ) )
                 	foreach ( $this->observers[$event] as $obs ) 
                 	{
                      		$obs->notify( $event, $msg );
                 	}
                 /* '**' being used as 'ALL' */
                 if ( isset( $this->observers['**'] ) )
                 	foreach ( $this->observers['**'] as $obs ) 
                 	{
                      		$obs->notify( $event, $msg );
                 	}
	         return SUCCESS;
         }
         /********************************************************************
         *	@function notify
         *	@param class object 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function notify(  $object )
         {
                 //Called when another object we are observing sends us a notification
	         return SUCCESS;
         }
         /********************************************************************
         *	@function PrecandlestickdatesInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecandlestickdatesInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlestickdates_PrecandlestickdatesInsert ) )
	            return $this->candlestickdates_PrecandlestickdatesInsert( $this );
                 else if ( is_callable( candlestickdates_PrecandlestickdatesInsert ) )
	            return candlestickdates_PrecandlestickdatesInsert( $this );
                 else if ( is_callable( PrecandlestickdatesInsert ) )
	            return PrecandlestickdatesInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcandlestickdatesInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcandlestickdatesInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlestickdates_PostcandlestickdatesInsert ) )
	            $returnval =  $this->candlestickdates_PostcandlestickdatesInsert( $this );
                 else if ( is_callable( candlestickdates_PostcandlestickdatesInsert ) )
	            $returnval =  candlestickdates_PostcandlestickdatesInsert( $this );
                 else if ( is_callable( PostcandlestickdatesInsert ) )
	            $returnval =  PostcandlestickdatesInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "candlestickdates" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PrecandlestickdatesUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecandlestickdatesUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlestickdates_PrecandlestickdatesUpdate ) )
	            return $this->candlestickdates_PrecandlestickdatesUpdate( $this );
                 else if ( is_callable( candlestickdates_PrecandlestickdatesUpdate ) )
	            return candlestickdates_PrecandlestickdatesUpdate( $this );
                 else if ( is_callable( PrecandlestickdatesUpdate ) )
	            return PrecandlestickdatesUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcandlestickdatesUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcandlestickdatesUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlestickdates_PostcandlestickdatesUpdate ) )
	            $returnval =  $this->candlestickdates_PostcandlestickdatesUpdate( $this );
                 else if ( is_callable( candlestickdates_PostcandlestickdatesUpdate ) )
	            $returnval =  candlestickdates_PostcandlestickdatesUpdate( $this );
                 else if ( is_callable( PostcandlestickdatesUpdate ) )
	            $returnval =  PostcandlestickdatesUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "candlestickdates" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PrecandlestickdatesDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecandlestickdatesDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlestickdates_PrecandlestickdatesDelete ) )
	            return $this->candlestickdates_PrecandlestickdatesDelete( $this );
                 else if ( is_callable( candlestickdates_PrecandlestickdatesDelete ) )
	            return candlestickdates_PrecandlestickdatesDelete( $this );
                 else if ( is_callable( PrecandlestickdatesDelete ) )
	            return PrecandlestickdatesDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcandlestickdatesDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcandlestickdatesDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->candlestickdates_PostcandlestickdatesDelete ) )
	            $returnval =  $this->candlestickdates_PostcandlestickdatesDelete( $this );
                 else if ( is_callable( candlestickdates_PostcandlestickdatesDelete ) )
	            $returnval =  candlestickdates_PostcandlestickdatesDelete( $this );
                 else if ( is_callable( PostcandlestickdatesDelete ) )
	            $returnval =  PostcandlestickdatesDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "candlestickdates" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setcandlestickdates
         *	@param date  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setcandlestickdates(  $value )
         {
                 $this->candlestickdates = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getcandlestickdates
         *	@param 
         *	@see 
         *	@return date
         ********************************************************************/
         /*@date@*//*int*/ function Getcandlestickdates()
         {
                    return $this->candlestickdates;
         }
} /* class candlestickdates */

require_once( 'DB/Table/Database.php' );;

class candlestickdates_table extends DB_Table
{
	var $col = array(
	'candlestickdates' => array( 'type'=>'date', 'require'=>false, 'size' =>'11' ),
	);
};
require_once( 'DB/DataObject.php' );;

class candlestickdates_object extends DB_DataObject
{
	var $__table='candlestickdates';
		//This is a Structures/DataGrid object
	var $candlestickdates;
};
/*	view/QuickFormIncludes and TabbedPages.php are in the skel-app/view if required	*/
require_once( 'view/QuickFormIncludes.php' );;
require_once( 'view/TabbedPages.php' );;

class candlestickdates_Page1 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('candlestickdates page 1');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('submit', 'empty.gif');
		$this->addGlobalSubmit();
		$f_date = date("Y-m-d" );
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'candlestickdates' => $f_date ) ) );
		$candlestickdates = $fs->addElement('text', 'candlestickdates', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'The dates for which candlesticks have been calculated' )
			->addFilter( 'trim' )
;
	}
}
?>