<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class evalfinancial */

require_once( 'DB/DataObject.php' );;

class evalfinancial_object extends DB_DataObject
{
	var $__table='evalfinancial';
		//This is a Structures/DataGrid object
	var $summary;
	var $idevalfinancial;
	var $idstockinfo;
	var $ownerearnings;
	var $roe;
	var $lasteval;
	var $user;
	var $retainearningsmv;
	var $debtratio;
	var $acceptabledebt;
	var $lowcost;
};
?>