<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class evalmarket */

require_once( 'DB/Table/Database.php' );;

class evalmarket_table extends DB_Table
{
	var $col = array(
	'netvalue' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'idevalmarket' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'idstockinfo' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'ownerearnings' => array( 'type'=>'float', 'require'=>false, 'size' =>'10' ),
	'discountrate' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'incomegrowth' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'value' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'netincome' => array( 'type'=>'float', 'require'=>false, 'size' =>'10' ),
	'depreciation' => array( 'type'=>'float', 'require'=>false, 'size' =>'10' ),
	'depletion' => array( 'type'=>'float', 'require'=>false, 'size' =>'10' ),
	'amortization' => array( 'type'=>'float', 'require'=>false, 'size' =>'10' ),
	'capitalexpenses' => array( 'type'=>'float', 'require'=>false, 'size' =>'10' ),
	'workingcapital' => array( 'type'=>'float', 'require'=>false, 'size' =>'10' ),
	'marketcap' => array( 'type'=>'bigint', 'require'=>false, 'size' =>'19' ),
	'marginsafety' => array( 'type'=>'float', 'require'=>false, 'size' =>'10' ),
	'lasteval' => array( 'type'=>'timestamp', 'require'=>false, 'size' =>'16' ),
	'user' => array( 'type'=>'varchar', 'require'=>true, 'size' =>'45' ),
	'outstandingshares' => array( 'type'=>'integer', 'require'=>false, 'size' =>'10' ),
	);
};
?>