<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class fxprices */

require_once( 'DB/Table/Database.php' );;

class fxprices_table extends DB_Table
{
	var $col = array(
	'currency' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	'date' => array( 'type'=>'date', 'require'=>false, 'size' =>'11' ),
	'previous_close' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'day_open' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'day_low' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'day_high' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'day_close' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'day_change' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'foreigncurrency' => array( 'type'=>'varchar', 'require'=>true, 'size' =>'11' ),
	);
};
?>