<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

class fxprices extends generictable 
{
	/*char * */ var $pretty_name = '';
	/*char * */ var $pretty_plural = '';
	/*char * */ var $pageheader = '';
	/*char * */ var $pagefooter = '';
         private $observers;
	/*char * */ var $data; //data passed in by other calls
/********************************************************
 *
 *	This section is the table columns
 *
 *******************************************************/
         var          /*char* *//* varchar */ $currency;
		 /* */
         var          /*char* *//* date */ $date;
		 /* */
         var          /*float *//* float */ $previous_close;
		 /* */
         var          /*float *//* float */ $day_open;
		 /* */
         var          /*float *//* float */ $day_low;
		 /* */
         var          /*float *//* float */ $day_high;
		 /* */
         var          /*float *//* float */ $day_close;
		 /* */
         var          /*float *//* float */ $day_change;
		 /* */
         var          /*char* *//* varchar */ $foreigncurrency;
		 /*Foreign Currency */
         function __construct()
         {
         	$this->querytablename = 'fxprices';
         	$this->classname = 'fxprices';
         	$this->fieldspec['currency']['metadata_id'] = '6677';
         	$this->fieldspec['currency']['table_name'] = 'fxprices';
         	$this->fieldspec['currency']['column_name'] = 'currency';
         	$this->fieldspec['currency']['pretty_name'] = '';
         	$this->fieldspec['currency']['abstract_data_type'] = 'varchar';
         	$this->fieldspec['currency']['db_data_type'] = 'varchar';
         	$this->fieldspec['currency']['field_null'] = 'YES';
         	$this->fieldspec['currency']['field_key'] = '';
         	$this->fieldspec['currency']['extra_sql'] = ' ';
         	$this->fieldspec['currency']['html_form_type'] = 'varchar';
         	$this->fieldspec['currency']['html_form_options'] = '';
         	$this->fieldspec['currency']['html_link_options'] = '';
         	$this->fieldspec['currency']['html_form_explanation'] = '';
         	$this->fieldspec['currency']['help_text'] = '';
         	$this->fieldspec['currency']['mandatory_p'] = 'N';
         	$this->fieldspec['currency']['sort_key'] = '0';
         	$this->fieldspec['currency']['form_sort_key'] = '0';
         	$this->fieldspec['currency']['form_number'] = '1';
         	$this->fieldspec['currency']['default_value'] = '';
         	$this->fieldspec['currency']['field_toupper'] = 'NO';
         	$this->fieldspec['currency']['validationprocname'] = '';
         	$this->fieldspec['currency']['minlength'] = '1';
         	$this->fieldspec['currency']['maxlength'] = '11';
         	$this->fieldspec['currency']['c_size'] = '11';
         	$this->fieldspec['currency']['prikey'] = 'N';
         	$this->fieldspec['currency']['noedit'] = 'N';
         	$this->fieldspec['currency']['nodisplay'] = 'N';
         	$this->fieldspec['currency']['c_unsigned'] = 'N';
         	$this->fieldspec['currency']['c_zerofill'] = 'N';
         	$this->fieldspec['currency']['c_auto_increment'] = 'N';
         	$this->fieldspec['currency']['foreign_table'] = '';
         	$this->fieldspec['currency']['foreign_key'] = '';
         	$this->fieldspec['currency']['application'] = 'finance';
         	$this->fieldspec['currency']['issearchable'] = '1';
         	$this->fieldspec['currency']['preinserttrigger'] = '';
         	$this->fieldspec['currency']['postinserttrigger'] = '';
         	$this->fieldspec['currency']['preupdatetrigger'] = '';
         	$this->fieldspec['currency']['postupdatetrigger'] = '';
         	$this->fieldspec['currency']['predeletetrigger'] = '';
         	$this->fieldspec['currency']['postdeletetrigger'] = '';
         	$this->fieldspec['currency']['definition_version'] = '1';
         	$this->fieldspec['currency']['form_javascript'] = '';
         	$this->fieldspec['currency']['rowSecurityProc'] = '';
         	$this->fieldspec['currency']['postinsert'] = 'PostcurrencyInsert';
         	$this->fieldspec['currency']['postupdate'] = 'PostcurrencyUpdate';
         	$this->fieldspec['currency']['postdelete'] = 'PostcurrencyDelete';
         	$this->fieldspec['currency']['preinsert'] = 'PrecurrencyInsert';
         	$this->fieldspec['currency']['preupdate'] = 'PrecurrencyUpdate';
         	$this->fieldspec['currency']['predelete'] = 'PrecurrencyDelete';
         	$this->fieldspec['date']['metadata_id'] = '6678';
         	$this->fieldspec['date']['table_name'] = 'fxprices';
         	$this->fieldspec['date']['column_name'] = 'date';
         	$this->fieldspec['date']['pretty_name'] = '';
         	$this->fieldspec['date']['abstract_data_type'] = 'date';
         	$this->fieldspec['date']['db_data_type'] = 'date';
         	$this->fieldspec['date']['field_null'] = 'NO';
         	$this->fieldspec['date']['field_key'] = '';
         	$this->fieldspec['date']['extra_sql'] = ' ';
         	$this->fieldspec['date']['html_form_type'] = 'date';
         	$this->fieldspec['date']['html_form_options'] = '';
         	$this->fieldspec['date']['html_link_options'] = '';
         	$this->fieldspec['date']['html_form_explanation'] = '';
         	$this->fieldspec['date']['help_text'] = '';
         	$this->fieldspec['date']['mandatory_p'] = 'N';
         	$this->fieldspec['date']['sort_key'] = '0';
         	$this->fieldspec['date']['form_sort_key'] = '0';
         	$this->fieldspec['date']['form_number'] = '1';
         	$this->fieldspec['date']['default_value'] = '';
         	$this->fieldspec['date']['field_toupper'] = 'NO';
         	$this->fieldspec['date']['validationprocname'] = '';
         	$this->fieldspec['date']['minlength'] = '1';
         	$this->fieldspec['date']['maxlength'] = '11';
         	$this->fieldspec['date']['c_size'] = '11';
         	$this->fieldspec['date']['prikey'] = 'N';
         	$this->fieldspec['date']['noedit'] = 'N';
         	$this->fieldspec['date']['nodisplay'] = 'N';
         	$this->fieldspec['date']['c_unsigned'] = 'N';
         	$this->fieldspec['date']['c_zerofill'] = 'N';
         	$this->fieldspec['date']['c_auto_increment'] = 'N';
         	$this->fieldspec['date']['foreign_table'] = '';
         	$this->fieldspec['date']['foreign_key'] = '';
         	$this->fieldspec['date']['application'] = 'finance';
         	$this->fieldspec['date']['issearchable'] = '1';
         	$this->fieldspec['date']['preinserttrigger'] = '';
         	$this->fieldspec['date']['postinserttrigger'] = '';
         	$this->fieldspec['date']['preupdatetrigger'] = '';
         	$this->fieldspec['date']['postupdatetrigger'] = '';
         	$this->fieldspec['date']['predeletetrigger'] = '';
         	$this->fieldspec['date']['postdeletetrigger'] = '';
         	$this->fieldspec['date']['definition_version'] = '1';
         	$this->fieldspec['date']['form_javascript'] = '';
         	$this->fieldspec['date']['rowSecurityProc'] = '';
         	$this->fieldspec['date']['postinsert'] = 'PostdateInsert';
         	$this->fieldspec['date']['postupdate'] = 'PostdateUpdate';
         	$this->fieldspec['date']['postdelete'] = 'PostdateDelete';
         	$this->fieldspec['date']['preinsert'] = 'PredateInsert';
         	$this->fieldspec['date']['preupdate'] = 'PredateUpdate';
         	$this->fieldspec['date']['predelete'] = 'PredateDelete';
         	$this->fieldspec['previous_close']['metadata_id'] = '6679';
         	$this->fieldspec['previous_close']['table_name'] = 'fxprices';
         	$this->fieldspec['previous_close']['column_name'] = 'previous_close';
         	$this->fieldspec['previous_close']['pretty_name'] = '';
         	$this->fieldspec['previous_close']['abstract_data_type'] = 'float';
         	$this->fieldspec['previous_close']['db_data_type'] = 'float';
         	$this->fieldspec['previous_close']['field_null'] = 'NO';
         	$this->fieldspec['previous_close']['field_key'] = '';
         	$this->fieldspec['previous_close']['extra_sql'] = ' ';
         	$this->fieldspec['previous_close']['html_form_type'] = 'float';
         	$this->fieldspec['previous_close']['html_form_options'] = '';
         	$this->fieldspec['previous_close']['html_link_options'] = '';
         	$this->fieldspec['previous_close']['html_form_explanation'] = '';
         	$this->fieldspec['previous_close']['help_text'] = '';
         	$this->fieldspec['previous_close']['mandatory_p'] = 'N';
         	$this->fieldspec['previous_close']['sort_key'] = '0';
         	$this->fieldspec['previous_close']['form_sort_key'] = '0';
         	$this->fieldspec['previous_close']['form_number'] = '1';
         	$this->fieldspec['previous_close']['default_value'] = '';
         	$this->fieldspec['previous_close']['field_toupper'] = 'NO';
         	$this->fieldspec['previous_close']['validationprocname'] = '';
         	$this->fieldspec['previous_close']['minlength'] = '1';
         	$this->fieldspec['previous_close']['maxlength'] = '11';
         	$this->fieldspec['previous_close']['c_size'] = '11';
         	$this->fieldspec['previous_close']['prikey'] = 'N';
         	$this->fieldspec['previous_close']['noedit'] = 'N';
         	$this->fieldspec['previous_close']['nodisplay'] = 'N';
         	$this->fieldspec['previous_close']['c_unsigned'] = 'N';
         	$this->fieldspec['previous_close']['c_zerofill'] = 'N';
         	$this->fieldspec['previous_close']['c_auto_increment'] = 'N';
         	$this->fieldspec['previous_close']['foreign_table'] = '';
         	$this->fieldspec['previous_close']['foreign_key'] = '';
         	$this->fieldspec['previous_close']['application'] = 'finance';
         	$this->fieldspec['previous_close']['issearchable'] = '1';
         	$this->fieldspec['previous_close']['preinserttrigger'] = '';
         	$this->fieldspec['previous_close']['postinserttrigger'] = '';
         	$this->fieldspec['previous_close']['preupdatetrigger'] = '';
         	$this->fieldspec['previous_close']['postupdatetrigger'] = '';
         	$this->fieldspec['previous_close']['predeletetrigger'] = '';
         	$this->fieldspec['previous_close']['postdeletetrigger'] = '';
         	$this->fieldspec['previous_close']['definition_version'] = '1';
         	$this->fieldspec['previous_close']['form_javascript'] = '';
         	$this->fieldspec['previous_close']['rowSecurityProc'] = '';
         	$this->fieldspec['previous_close']['postinsert'] = 'Postprevious_closeInsert';
         	$this->fieldspec['previous_close']['postupdate'] = 'Postprevious_closeUpdate';
         	$this->fieldspec['previous_close']['postdelete'] = 'Postprevious_closeDelete';
         	$this->fieldspec['previous_close']['preinsert'] = 'Preprevious_closeInsert';
         	$this->fieldspec['previous_close']['preupdate'] = 'Preprevious_closeUpdate';
         	$this->fieldspec['previous_close']['predelete'] = 'Preprevious_closeDelete';
         	$this->fieldspec['day_open']['metadata_id'] = '6680';
         	$this->fieldspec['day_open']['table_name'] = 'fxprices';
         	$this->fieldspec['day_open']['column_name'] = 'day_open';
         	$this->fieldspec['day_open']['pretty_name'] = '';
         	$this->fieldspec['day_open']['abstract_data_type'] = 'float';
         	$this->fieldspec['day_open']['db_data_type'] = 'float';
         	$this->fieldspec['day_open']['field_null'] = 'NO';
         	$this->fieldspec['day_open']['field_key'] = '';
         	$this->fieldspec['day_open']['extra_sql'] = ' ';
         	$this->fieldspec['day_open']['html_form_type'] = 'float';
         	$this->fieldspec['day_open']['html_form_options'] = '';
         	$this->fieldspec['day_open']['html_link_options'] = '';
         	$this->fieldspec['day_open']['html_form_explanation'] = '';
         	$this->fieldspec['day_open']['help_text'] = '';
         	$this->fieldspec['day_open']['mandatory_p'] = 'N';
         	$this->fieldspec['day_open']['sort_key'] = '0';
         	$this->fieldspec['day_open']['form_sort_key'] = '0';
         	$this->fieldspec['day_open']['form_number'] = '1';
         	$this->fieldspec['day_open']['default_value'] = '';
         	$this->fieldspec['day_open']['field_toupper'] = 'NO';
         	$this->fieldspec['day_open']['validationprocname'] = '';
         	$this->fieldspec['day_open']['minlength'] = '1';
         	$this->fieldspec['day_open']['maxlength'] = '11';
         	$this->fieldspec['day_open']['c_size'] = '11';
         	$this->fieldspec['day_open']['prikey'] = 'N';
         	$this->fieldspec['day_open']['noedit'] = 'N';
         	$this->fieldspec['day_open']['nodisplay'] = 'N';
         	$this->fieldspec['day_open']['c_unsigned'] = 'N';
         	$this->fieldspec['day_open']['c_zerofill'] = 'N';
         	$this->fieldspec['day_open']['c_auto_increment'] = 'N';
         	$this->fieldspec['day_open']['foreign_table'] = '';
         	$this->fieldspec['day_open']['foreign_key'] = '';
         	$this->fieldspec['day_open']['application'] = 'finance';
         	$this->fieldspec['day_open']['issearchable'] = '1';
         	$this->fieldspec['day_open']['preinserttrigger'] = '';
         	$this->fieldspec['day_open']['postinserttrigger'] = '';
         	$this->fieldspec['day_open']['preupdatetrigger'] = '';
         	$this->fieldspec['day_open']['postupdatetrigger'] = '';
         	$this->fieldspec['day_open']['predeletetrigger'] = '';
         	$this->fieldspec['day_open']['postdeletetrigger'] = '';
         	$this->fieldspec['day_open']['definition_version'] = '1';
         	$this->fieldspec['day_open']['form_javascript'] = '';
         	$this->fieldspec['day_open']['rowSecurityProc'] = '';
         	$this->fieldspec['day_open']['postinsert'] = 'Postday_openInsert';
         	$this->fieldspec['day_open']['postupdate'] = 'Postday_openUpdate';
         	$this->fieldspec['day_open']['postdelete'] = 'Postday_openDelete';
         	$this->fieldspec['day_open']['preinsert'] = 'Preday_openInsert';
         	$this->fieldspec['day_open']['preupdate'] = 'Preday_openUpdate';
         	$this->fieldspec['day_open']['predelete'] = 'Preday_openDelete';
         	$this->fieldspec['day_low']['metadata_id'] = '6681';
         	$this->fieldspec['day_low']['table_name'] = 'fxprices';
         	$this->fieldspec['day_low']['column_name'] = 'day_low';
         	$this->fieldspec['day_low']['pretty_name'] = '';
         	$this->fieldspec['day_low']['abstract_data_type'] = 'float';
         	$this->fieldspec['day_low']['db_data_type'] = 'float';
         	$this->fieldspec['day_low']['field_null'] = 'NO';
         	$this->fieldspec['day_low']['field_key'] = '';
         	$this->fieldspec['day_low']['extra_sql'] = ' ';
         	$this->fieldspec['day_low']['html_form_type'] = 'float';
         	$this->fieldspec['day_low']['html_form_options'] = '';
         	$this->fieldspec['day_low']['html_link_options'] = '';
         	$this->fieldspec['day_low']['html_form_explanation'] = '';
         	$this->fieldspec['day_low']['help_text'] = '';
         	$this->fieldspec['day_low']['mandatory_p'] = 'N';
         	$this->fieldspec['day_low']['sort_key'] = '0';
         	$this->fieldspec['day_low']['form_sort_key'] = '0';
         	$this->fieldspec['day_low']['form_number'] = '1';
         	$this->fieldspec['day_low']['default_value'] = '';
         	$this->fieldspec['day_low']['field_toupper'] = 'NO';
         	$this->fieldspec['day_low']['validationprocname'] = '';
         	$this->fieldspec['day_low']['minlength'] = '1';
         	$this->fieldspec['day_low']['maxlength'] = '11';
         	$this->fieldspec['day_low']['c_size'] = '11';
         	$this->fieldspec['day_low']['prikey'] = 'N';
         	$this->fieldspec['day_low']['noedit'] = 'N';
         	$this->fieldspec['day_low']['nodisplay'] = 'N';
         	$this->fieldspec['day_low']['c_unsigned'] = 'N';
         	$this->fieldspec['day_low']['c_zerofill'] = 'N';
         	$this->fieldspec['day_low']['c_auto_increment'] = 'N';
         	$this->fieldspec['day_low']['foreign_table'] = '';
         	$this->fieldspec['day_low']['foreign_key'] = '';
         	$this->fieldspec['day_low']['application'] = 'finance';
         	$this->fieldspec['day_low']['issearchable'] = '1';
         	$this->fieldspec['day_low']['preinserttrigger'] = '';
         	$this->fieldspec['day_low']['postinserttrigger'] = '';
         	$this->fieldspec['day_low']['preupdatetrigger'] = '';
         	$this->fieldspec['day_low']['postupdatetrigger'] = '';
         	$this->fieldspec['day_low']['predeletetrigger'] = '';
         	$this->fieldspec['day_low']['postdeletetrigger'] = '';
         	$this->fieldspec['day_low']['definition_version'] = '1';
         	$this->fieldspec['day_low']['form_javascript'] = '';
         	$this->fieldspec['day_low']['rowSecurityProc'] = '';
         	$this->fieldspec['day_low']['postinsert'] = 'Postday_lowInsert';
         	$this->fieldspec['day_low']['postupdate'] = 'Postday_lowUpdate';
         	$this->fieldspec['day_low']['postdelete'] = 'Postday_lowDelete';
         	$this->fieldspec['day_low']['preinsert'] = 'Preday_lowInsert';
         	$this->fieldspec['day_low']['preupdate'] = 'Preday_lowUpdate';
         	$this->fieldspec['day_low']['predelete'] = 'Preday_lowDelete';
         	$this->fieldspec['day_high']['metadata_id'] = '6682';
         	$this->fieldspec['day_high']['table_name'] = 'fxprices';
         	$this->fieldspec['day_high']['column_name'] = 'day_high';
         	$this->fieldspec['day_high']['pretty_name'] = '';
         	$this->fieldspec['day_high']['abstract_data_type'] = 'float';
         	$this->fieldspec['day_high']['db_data_type'] = 'float';
         	$this->fieldspec['day_high']['field_null'] = 'NO';
         	$this->fieldspec['day_high']['field_key'] = '';
         	$this->fieldspec['day_high']['extra_sql'] = ' ';
         	$this->fieldspec['day_high']['html_form_type'] = 'float';
         	$this->fieldspec['day_high']['html_form_options'] = '';
         	$this->fieldspec['day_high']['html_link_options'] = '';
         	$this->fieldspec['day_high']['html_form_explanation'] = '';
         	$this->fieldspec['day_high']['help_text'] = '';
         	$this->fieldspec['day_high']['mandatory_p'] = 'N';
         	$this->fieldspec['day_high']['sort_key'] = '0';
         	$this->fieldspec['day_high']['form_sort_key'] = '0';
         	$this->fieldspec['day_high']['form_number'] = '1';
         	$this->fieldspec['day_high']['default_value'] = '';
         	$this->fieldspec['day_high']['field_toupper'] = 'NO';
         	$this->fieldspec['day_high']['validationprocname'] = '';
         	$this->fieldspec['day_high']['minlength'] = '1';
         	$this->fieldspec['day_high']['maxlength'] = '11';
         	$this->fieldspec['day_high']['c_size'] = '11';
         	$this->fieldspec['day_high']['prikey'] = 'N';
         	$this->fieldspec['day_high']['noedit'] = 'N';
         	$this->fieldspec['day_high']['nodisplay'] = 'N';
         	$this->fieldspec['day_high']['c_unsigned'] = 'N';
         	$this->fieldspec['day_high']['c_zerofill'] = 'N';
         	$this->fieldspec['day_high']['c_auto_increment'] = 'N';
         	$this->fieldspec['day_high']['foreign_table'] = '';
         	$this->fieldspec['day_high']['foreign_key'] = '';
         	$this->fieldspec['day_high']['application'] = 'finance';
         	$this->fieldspec['day_high']['issearchable'] = '1';
         	$this->fieldspec['day_high']['preinserttrigger'] = '';
         	$this->fieldspec['day_high']['postinserttrigger'] = '';
         	$this->fieldspec['day_high']['preupdatetrigger'] = '';
         	$this->fieldspec['day_high']['postupdatetrigger'] = '';
         	$this->fieldspec['day_high']['predeletetrigger'] = '';
         	$this->fieldspec['day_high']['postdeletetrigger'] = '';
         	$this->fieldspec['day_high']['definition_version'] = '1';
         	$this->fieldspec['day_high']['form_javascript'] = '';
         	$this->fieldspec['day_high']['rowSecurityProc'] = '';
         	$this->fieldspec['day_high']['postinsert'] = 'Postday_highInsert';
         	$this->fieldspec['day_high']['postupdate'] = 'Postday_highUpdate';
         	$this->fieldspec['day_high']['postdelete'] = 'Postday_highDelete';
         	$this->fieldspec['day_high']['preinsert'] = 'Preday_highInsert';
         	$this->fieldspec['day_high']['preupdate'] = 'Preday_highUpdate';
         	$this->fieldspec['day_high']['predelete'] = 'Preday_highDelete';
         	$this->fieldspec['day_close']['metadata_id'] = '6683';
         	$this->fieldspec['day_close']['table_name'] = 'fxprices';
         	$this->fieldspec['day_close']['column_name'] = 'day_close';
         	$this->fieldspec['day_close']['pretty_name'] = '';
         	$this->fieldspec['day_close']['abstract_data_type'] = 'float';
         	$this->fieldspec['day_close']['db_data_type'] = 'float';
         	$this->fieldspec['day_close']['field_null'] = 'NO';
         	$this->fieldspec['day_close']['field_key'] = '';
         	$this->fieldspec['day_close']['extra_sql'] = ' ';
         	$this->fieldspec['day_close']['html_form_type'] = 'float';
         	$this->fieldspec['day_close']['html_form_options'] = '';
         	$this->fieldspec['day_close']['html_link_options'] = '';
         	$this->fieldspec['day_close']['html_form_explanation'] = '';
         	$this->fieldspec['day_close']['help_text'] = '';
         	$this->fieldspec['day_close']['mandatory_p'] = 'N';
         	$this->fieldspec['day_close']['sort_key'] = '0';
         	$this->fieldspec['day_close']['form_sort_key'] = '0';
         	$this->fieldspec['day_close']['form_number'] = '1';
         	$this->fieldspec['day_close']['default_value'] = '';
         	$this->fieldspec['day_close']['field_toupper'] = 'NO';
         	$this->fieldspec['day_close']['validationprocname'] = '';
         	$this->fieldspec['day_close']['minlength'] = '1';
         	$this->fieldspec['day_close']['maxlength'] = '11';
         	$this->fieldspec['day_close']['c_size'] = '11';
         	$this->fieldspec['day_close']['prikey'] = 'N';
         	$this->fieldspec['day_close']['noedit'] = 'N';
         	$this->fieldspec['day_close']['nodisplay'] = 'N';
         	$this->fieldspec['day_close']['c_unsigned'] = 'N';
         	$this->fieldspec['day_close']['c_zerofill'] = 'N';
         	$this->fieldspec['day_close']['c_auto_increment'] = 'N';
         	$this->fieldspec['day_close']['foreign_table'] = '';
         	$this->fieldspec['day_close']['foreign_key'] = '';
         	$this->fieldspec['day_close']['application'] = 'finance';
         	$this->fieldspec['day_close']['issearchable'] = '1';
         	$this->fieldspec['day_close']['preinserttrigger'] = '';
         	$this->fieldspec['day_close']['postinserttrigger'] = '';
         	$this->fieldspec['day_close']['preupdatetrigger'] = '';
         	$this->fieldspec['day_close']['postupdatetrigger'] = '';
         	$this->fieldspec['day_close']['predeletetrigger'] = '';
         	$this->fieldspec['day_close']['postdeletetrigger'] = '';
         	$this->fieldspec['day_close']['definition_version'] = '1';
         	$this->fieldspec['day_close']['form_javascript'] = '';
         	$this->fieldspec['day_close']['rowSecurityProc'] = '';
         	$this->fieldspec['day_close']['postinsert'] = 'Postday_closeInsert';
         	$this->fieldspec['day_close']['postupdate'] = 'Postday_closeUpdate';
         	$this->fieldspec['day_close']['postdelete'] = 'Postday_closeDelete';
         	$this->fieldspec['day_close']['preinsert'] = 'Preday_closeInsert';
         	$this->fieldspec['day_close']['preupdate'] = 'Preday_closeUpdate';
         	$this->fieldspec['day_close']['predelete'] = 'Preday_closeDelete';
         	$this->fieldspec['day_change']['metadata_id'] = '6684';
         	$this->fieldspec['day_change']['table_name'] = 'fxprices';
         	$this->fieldspec['day_change']['column_name'] = 'day_change';
         	$this->fieldspec['day_change']['pretty_name'] = '';
         	$this->fieldspec['day_change']['abstract_data_type'] = 'float';
         	$this->fieldspec['day_change']['db_data_type'] = 'float';
         	$this->fieldspec['day_change']['field_null'] = 'NO';
         	$this->fieldspec['day_change']['field_key'] = '';
         	$this->fieldspec['day_change']['extra_sql'] = ' ';
         	$this->fieldspec['day_change']['html_form_type'] = 'float';
         	$this->fieldspec['day_change']['html_form_options'] = '';
         	$this->fieldspec['day_change']['html_link_options'] = '';
         	$this->fieldspec['day_change']['html_form_explanation'] = '';
         	$this->fieldspec['day_change']['help_text'] = '';
         	$this->fieldspec['day_change']['mandatory_p'] = 'N';
         	$this->fieldspec['day_change']['sort_key'] = '0';
         	$this->fieldspec['day_change']['form_sort_key'] = '0';
         	$this->fieldspec['day_change']['form_number'] = '1';
         	$this->fieldspec['day_change']['default_value'] = '';
         	$this->fieldspec['day_change']['field_toupper'] = 'NO';
         	$this->fieldspec['day_change']['validationprocname'] = '';
         	$this->fieldspec['day_change']['minlength'] = '1';
         	$this->fieldspec['day_change']['maxlength'] = '11';
         	$this->fieldspec['day_change']['c_size'] = '11';
         	$this->fieldspec['day_change']['prikey'] = 'N';
         	$this->fieldspec['day_change']['noedit'] = 'N';
         	$this->fieldspec['day_change']['nodisplay'] = 'N';
         	$this->fieldspec['day_change']['c_unsigned'] = 'N';
         	$this->fieldspec['day_change']['c_zerofill'] = 'N';
         	$this->fieldspec['day_change']['c_auto_increment'] = 'N';
         	$this->fieldspec['day_change']['foreign_table'] = '';
         	$this->fieldspec['day_change']['foreign_key'] = '';
         	$this->fieldspec['day_change']['application'] = 'finance';
         	$this->fieldspec['day_change']['issearchable'] = '1';
         	$this->fieldspec['day_change']['preinserttrigger'] = '';
         	$this->fieldspec['day_change']['postinserttrigger'] = '';
         	$this->fieldspec['day_change']['preupdatetrigger'] = '';
         	$this->fieldspec['day_change']['postupdatetrigger'] = '';
         	$this->fieldspec['day_change']['predeletetrigger'] = '';
         	$this->fieldspec['day_change']['postdeletetrigger'] = '';
         	$this->fieldspec['day_change']['definition_version'] = '1';
         	$this->fieldspec['day_change']['form_javascript'] = '';
         	$this->fieldspec['day_change']['rowSecurityProc'] = '';
         	$this->fieldspec['day_change']['postinsert'] = 'Postday_changeInsert';
         	$this->fieldspec['day_change']['postupdate'] = 'Postday_changeUpdate';
         	$this->fieldspec['day_change']['postdelete'] = 'Postday_changeDelete';
         	$this->fieldspec['day_change']['preinsert'] = 'Preday_changeInsert';
         	$this->fieldspec['day_change']['preupdate'] = 'Preday_changeUpdate';
         	$this->fieldspec['day_change']['predelete'] = 'Preday_changeDelete';
         	$this->fieldspec['foreigncurrency']['metadata_id'] = '6704';
         	$this->fieldspec['foreigncurrency']['table_name'] = 'fxprices';
         	$this->fieldspec['foreigncurrency']['column_name'] = 'foreigncurrency';
         	$this->fieldspec['foreigncurrency']['pretty_name'] = 'Foreign Currency';
         	$this->fieldspec['foreigncurrency']['abstract_data_type'] = 'Name';
         	$this->fieldspec['foreigncurrency']['db_data_type'] = 'varchar';
         	$this->fieldspec['foreigncurrency']['field_null'] = 'NO';
         	$this->fieldspec['foreigncurrency']['field_key'] = '';
         	$this->fieldspec['foreigncurrency']['extra_sql'] = '';
         	$this->fieldspec['foreigncurrency']['html_form_type'] = 'text';
         	$this->fieldspec['foreigncurrency']['html_form_options'] = '';
         	$this->fieldspec['foreigncurrency']['html_link_options'] = '';
         	$this->fieldspec['foreigncurrency']['html_form_explanation'] = '';
         	$this->fieldspec['foreigncurrency']['help_text'] = '';
         	$this->fieldspec['foreigncurrency']['mandatory_p'] = 'Y';
         	$this->fieldspec['foreigncurrency']['sort_key'] = '0';
         	$this->fieldspec['foreigncurrency']['form_sort_key'] = '0';
         	$this->fieldspec['foreigncurrency']['form_number'] = '1';
         	$this->fieldspec['foreigncurrency']['default_value'] = '0';
         	$this->fieldspec['foreigncurrency']['field_toupper'] = 'NO';
         	$this->fieldspec['foreigncurrency']['validationprocname'] = '';
         	$this->fieldspec['foreigncurrency']['minlength'] = '1';
         	$this->fieldspec['foreigncurrency']['maxlength'] = '11';
         	$this->fieldspec['foreigncurrency']['c_size'] = '11';
         	$this->fieldspec['foreigncurrency']['prikey'] = 'N';
         	$this->fieldspec['foreigncurrency']['noedit'] = 'N';
         	$this->fieldspec['foreigncurrency']['nodisplay'] = 'N';
         	$this->fieldspec['foreigncurrency']['c_unsigned'] = 'N';
         	$this->fieldspec['foreigncurrency']['c_zerofill'] = 'N';
         	$this->fieldspec['foreigncurrency']['c_auto_increment'] = 'N';
         	$this->fieldspec['foreigncurrency']['foreign_table'] = '';
         	$this->fieldspec['foreigncurrency']['foreign_key'] = '';
         	$this->fieldspec['foreigncurrency']['application'] = 'finance';
         	$this->fieldspec['foreigncurrency']['issearchable'] = '1';
         	$this->fieldspec['foreigncurrency']['preinserttrigger'] = '';
         	$this->fieldspec['foreigncurrency']['postinserttrigger'] = '';
         	$this->fieldspec['foreigncurrency']['preupdatetrigger'] = '';
         	$this->fieldspec['foreigncurrency']['postupdatetrigger'] = '';
         	$this->fieldspec['foreigncurrency']['predeletetrigger'] = '';
         	$this->fieldspec['foreigncurrency']['postdeletetrigger'] = '';
         	$this->fieldspec['foreigncurrency']['definition_version'] = '1';
         	$this->fieldspec['foreigncurrency']['form_javascript'] = '';
         	$this->fieldspec['foreigncurrency']['rowSecurityProc'] = '';
         	$this->fieldspec['foreigncurrency']['postinsert'] = 'PostforeigncurrencyInsert';
         	$this->fieldspec['foreigncurrency']['postupdate'] = 'PostforeigncurrencyUpdate';
         	$this->fieldspec['foreigncurrency']['postdelete'] = 'PostforeigncurrencyDelete';
         	$this->fieldspec['foreigncurrency']['preinsert'] = 'PreforeigncurrencyInsert';
         	$this->fieldspec['foreigncurrency']['preupdate'] = 'PreforeigncurrencyUpdate';
         	$this->fieldspec['foreigncurrency']['predelete'] = 'PreforeigncurrencyDelete';
         	$this->fieldlist = array('currency', 'date', 'previous_close', 'day_open', 'day_low', 'day_high', 'day_close', 'day_change', 'foreigncurrency');
         	$this->searchlist = array('currency', 'date', 'previous_close', 'day_open', 'day_low', 'day_high', 'day_close', 'day_change', 'foreigncurrency');
         	$this->prikeylist = array();
		$this->defaultsort = '';
	         return SUCCESS;
         }
         /*void*/ function  fxprices()
         { //For older php which doesn't have constructor
              return $this->__construct();
         }
         /*@bool@*//*int*/ function Push()
         {
	         $_SESSION['fxprices'] = serialize($this);
	         return SUCCESS;
         }
         /*@bool@*//*int*/ function Pop()
         {
                 //Can't do this in self - this is how to do it outside
	       //  $this = unserialize($_SESSION['fxprices']);
	         return SUCCESS;
         }
         /********************************************************************
         *	@function ObserverRegister
         *	@param class observer 
         *	@param string event 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function ObserverRegister(  $observer,  $event )
         {
                 $this->observers[$event][] = $observer;
	         return SUCCESS;
         }
         /********************************************************************
         *	@function ObserverDeRegister
         *	@param class observer
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function ObserverDeRegister( $observer )
         {
                 $this->observers[] = array_diff( $this->observers, array( $observer) );
	         return SUCCESS;
         }
         /********************************************************************
         *	@function ObserverNotify
         *	@param string event
         *	@param string msg 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function ObserverNotify(  $event,  $msg )
         {
                 if ( isset( $this->observers[$event] ) )
                 	foreach ( $this->observers[$event] as $obs ) 
                 	{
                      		$obs->notify( $event, $msg );
                 	}
                 /* '**' being used as 'ALL' */
                 if ( isset( $this->observers['**'] ) )
                 	foreach ( $this->observers['**'] as $obs ) 
                 	{
                      		$obs->notify( $event, $msg );
                 	}
	         return SUCCESS;
         }
         /********************************************************************
         *	@function notify
         *	@param class object 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function notify(  $object )
         {
                 //Called when another object we are observing sends us a notification
	         return SUCCESS;
         }
         /********************************************************************
         *	@function PrecurrencyInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecurrencyInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PrecurrencyInsert ) )
	            return $this->fxprices_PrecurrencyInsert( $this );
                 else if ( is_callable( fxprices_PrecurrencyInsert ) )
	            return fxprices_PrecurrencyInsert( $this );
                 else if ( is_callable( PrecurrencyInsert ) )
	            return PrecurrencyInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcurrencyInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcurrencyInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PostcurrencyInsert ) )
	            $returnval =  $this->fxprices_PostcurrencyInsert( $this );
                 else if ( is_callable( fxprices_PostcurrencyInsert ) )
	            $returnval =  fxprices_PostcurrencyInsert( $this );
                 else if ( is_callable( PostcurrencyInsert ) )
	            $returnval =  PostcurrencyInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "currency" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PrecurrencyUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecurrencyUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PrecurrencyUpdate ) )
	            return $this->fxprices_PrecurrencyUpdate( $this );
                 else if ( is_callable( fxprices_PrecurrencyUpdate ) )
	            return fxprices_PrecurrencyUpdate( $this );
                 else if ( is_callable( PrecurrencyUpdate ) )
	            return PrecurrencyUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcurrencyUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcurrencyUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PostcurrencyUpdate ) )
	            $returnval =  $this->fxprices_PostcurrencyUpdate( $this );
                 else if ( is_callable( fxprices_PostcurrencyUpdate ) )
	            $returnval =  fxprices_PostcurrencyUpdate( $this );
                 else if ( is_callable( PostcurrencyUpdate ) )
	            $returnval =  PostcurrencyUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "currency" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PrecurrencyDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PrecurrencyDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PrecurrencyDelete ) )
	            return $this->fxprices_PrecurrencyDelete( $this );
                 else if ( is_callable( fxprices_PrecurrencyDelete ) )
	            return fxprices_PrecurrencyDelete( $this );
                 else if ( is_callable( PrecurrencyDelete ) )
	            return PrecurrencyDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostcurrencyDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostcurrencyDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PostcurrencyDelete ) )
	            $returnval =  $this->fxprices_PostcurrencyDelete( $this );
                 else if ( is_callable( fxprices_PostcurrencyDelete ) )
	            $returnval =  fxprices_PostcurrencyDelete( $this );
                 else if ( is_callable( PostcurrencyDelete ) )
	            $returnval =  PostcurrencyDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "currency" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setcurrency
         *	@param varchar  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setcurrency(  $value )
         {
                 $this->currency = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getcurrency
         *	@param 
         *	@see 
         *	@return varchar
         ********************************************************************/
         /*@varchar@*//*int*/ function Getcurrency()
         {
                    return $this->currency;
         }
         /********************************************************************
         *	@function PredateInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PredateInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PredateInsert ) )
	            return $this->fxprices_PredateInsert( $this );
                 else if ( is_callable( fxprices_PredateInsert ) )
	            return fxprices_PredateInsert( $this );
                 else if ( is_callable( PredateInsert ) )
	            return PredateInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostdateInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostdateInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PostdateInsert ) )
	            $returnval =  $this->fxprices_PostdateInsert( $this );
                 else if ( is_callable( fxprices_PostdateInsert ) )
	            $returnval =  fxprices_PostdateInsert( $this );
                 else if ( is_callable( PostdateInsert ) )
	            $returnval =  PostdateInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "date" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PredateUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PredateUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PredateUpdate ) )
	            return $this->fxprices_PredateUpdate( $this );
                 else if ( is_callable( fxprices_PredateUpdate ) )
	            return fxprices_PredateUpdate( $this );
                 else if ( is_callable( PredateUpdate ) )
	            return PredateUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostdateUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostdateUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PostdateUpdate ) )
	            $returnval =  $this->fxprices_PostdateUpdate( $this );
                 else if ( is_callable( fxprices_PostdateUpdate ) )
	            $returnval =  fxprices_PostdateUpdate( $this );
                 else if ( is_callable( PostdateUpdate ) )
	            $returnval =  PostdateUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "date" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PredateDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PredateDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PredateDelete ) )
	            return $this->fxprices_PredateDelete( $this );
                 else if ( is_callable( fxprices_PredateDelete ) )
	            return fxprices_PredateDelete( $this );
                 else if ( is_callable( PredateDelete ) )
	            return PredateDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostdateDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostdateDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PostdateDelete ) )
	            $returnval =  $this->fxprices_PostdateDelete( $this );
                 else if ( is_callable( fxprices_PostdateDelete ) )
	            $returnval =  fxprices_PostdateDelete( $this );
                 else if ( is_callable( PostdateDelete ) )
	            $returnval =  PostdateDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "date" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setdate
         *	@param date  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setdate(  $value )
         {
                 $this->date = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getdate
         *	@param 
         *	@see 
         *	@return date
         ********************************************************************/
         /*@date@*//*int*/ function Getdate()
         {
                    return $this->date;
         }
         /********************************************************************
         *	@function Preprevious_closeInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preprevious_closeInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preprevious_closeInsert ) )
	            return $this->fxprices_Preprevious_closeInsert( $this );
                 else if ( is_callable( fxprices_Preprevious_closeInsert ) )
	            return fxprices_Preprevious_closeInsert( $this );
                 else if ( is_callable( Preprevious_closeInsert ) )
	            return Preprevious_closeInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postprevious_closeInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postprevious_closeInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postprevious_closeInsert ) )
	            $returnval =  $this->fxprices_Postprevious_closeInsert( $this );
                 else if ( is_callable( fxprices_Postprevious_closeInsert ) )
	            $returnval =  fxprices_Postprevious_closeInsert( $this );
                 else if ( is_callable( Postprevious_closeInsert ) )
	            $returnval =  Postprevious_closeInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "previous_close" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Preprevious_closeUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preprevious_closeUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preprevious_closeUpdate ) )
	            return $this->fxprices_Preprevious_closeUpdate( $this );
                 else if ( is_callable( fxprices_Preprevious_closeUpdate ) )
	            return fxprices_Preprevious_closeUpdate( $this );
                 else if ( is_callable( Preprevious_closeUpdate ) )
	            return Preprevious_closeUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postprevious_closeUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postprevious_closeUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postprevious_closeUpdate ) )
	            $returnval =  $this->fxprices_Postprevious_closeUpdate( $this );
                 else if ( is_callable( fxprices_Postprevious_closeUpdate ) )
	            $returnval =  fxprices_Postprevious_closeUpdate( $this );
                 else if ( is_callable( Postprevious_closeUpdate ) )
	            $returnval =  Postprevious_closeUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "previous_close" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Preprevious_closeDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preprevious_closeDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preprevious_closeDelete ) )
	            return $this->fxprices_Preprevious_closeDelete( $this );
                 else if ( is_callable( fxprices_Preprevious_closeDelete ) )
	            return fxprices_Preprevious_closeDelete( $this );
                 else if ( is_callable( Preprevious_closeDelete ) )
	            return Preprevious_closeDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postprevious_closeDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postprevious_closeDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postprevious_closeDelete ) )
	            $returnval =  $this->fxprices_Postprevious_closeDelete( $this );
                 else if ( is_callable( fxprices_Postprevious_closeDelete ) )
	            $returnval =  fxprices_Postprevious_closeDelete( $this );
                 else if ( is_callable( Postprevious_closeDelete ) )
	            $returnval =  Postprevious_closeDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "previous_close" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setprevious_close
         *	@param float  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setprevious_close(  $value )
         {
                 $this->previous_close = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getprevious_close
         *	@param 
         *	@see 
         *	@return float
         ********************************************************************/
         /*@float@*//*int*/ function Getprevious_close()
         {
                    return $this->previous_close;
         }
         /********************************************************************
         *	@function Preday_openInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_openInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_openInsert ) )
	            return $this->fxprices_Preday_openInsert( $this );
                 else if ( is_callable( fxprices_Preday_openInsert ) )
	            return fxprices_Preday_openInsert( $this );
                 else if ( is_callable( Preday_openInsert ) )
	            return Preday_openInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_openInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_openInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_openInsert ) )
	            $returnval =  $this->fxprices_Postday_openInsert( $this );
                 else if ( is_callable( fxprices_Postday_openInsert ) )
	            $returnval =  fxprices_Postday_openInsert( $this );
                 else if ( is_callable( Postday_openInsert ) )
	            $returnval =  Postday_openInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "day_open" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Preday_openUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_openUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_openUpdate ) )
	            return $this->fxprices_Preday_openUpdate( $this );
                 else if ( is_callable( fxprices_Preday_openUpdate ) )
	            return fxprices_Preday_openUpdate( $this );
                 else if ( is_callable( Preday_openUpdate ) )
	            return Preday_openUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_openUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_openUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_openUpdate ) )
	            $returnval =  $this->fxprices_Postday_openUpdate( $this );
                 else if ( is_callable( fxprices_Postday_openUpdate ) )
	            $returnval =  fxprices_Postday_openUpdate( $this );
                 else if ( is_callable( Postday_openUpdate ) )
	            $returnval =  Postday_openUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "day_open" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Preday_openDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_openDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_openDelete ) )
	            return $this->fxprices_Preday_openDelete( $this );
                 else if ( is_callable( fxprices_Preday_openDelete ) )
	            return fxprices_Preday_openDelete( $this );
                 else if ( is_callable( Preday_openDelete ) )
	            return Preday_openDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_openDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_openDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_openDelete ) )
	            $returnval =  $this->fxprices_Postday_openDelete( $this );
                 else if ( is_callable( fxprices_Postday_openDelete ) )
	            $returnval =  fxprices_Postday_openDelete( $this );
                 else if ( is_callable( Postday_openDelete ) )
	            $returnval =  Postday_openDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "day_open" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setday_open
         *	@param float  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setday_open(  $value )
         {
                 $this->day_open = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getday_open
         *	@param 
         *	@see 
         *	@return float
         ********************************************************************/
         /*@float@*//*int*/ function Getday_open()
         {
                    return $this->day_open;
         }
         /********************************************************************
         *	@function Preday_lowInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_lowInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_lowInsert ) )
	            return $this->fxprices_Preday_lowInsert( $this );
                 else if ( is_callable( fxprices_Preday_lowInsert ) )
	            return fxprices_Preday_lowInsert( $this );
                 else if ( is_callable( Preday_lowInsert ) )
	            return Preday_lowInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_lowInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_lowInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_lowInsert ) )
	            $returnval =  $this->fxprices_Postday_lowInsert( $this );
                 else if ( is_callable( fxprices_Postday_lowInsert ) )
	            $returnval =  fxprices_Postday_lowInsert( $this );
                 else if ( is_callable( Postday_lowInsert ) )
	            $returnval =  Postday_lowInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "day_low" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Preday_lowUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_lowUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_lowUpdate ) )
	            return $this->fxprices_Preday_lowUpdate( $this );
                 else if ( is_callable( fxprices_Preday_lowUpdate ) )
	            return fxprices_Preday_lowUpdate( $this );
                 else if ( is_callable( Preday_lowUpdate ) )
	            return Preday_lowUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_lowUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_lowUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_lowUpdate ) )
	            $returnval =  $this->fxprices_Postday_lowUpdate( $this );
                 else if ( is_callable( fxprices_Postday_lowUpdate ) )
	            $returnval =  fxprices_Postday_lowUpdate( $this );
                 else if ( is_callable( Postday_lowUpdate ) )
	            $returnval =  Postday_lowUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "day_low" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Preday_lowDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_lowDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_lowDelete ) )
	            return $this->fxprices_Preday_lowDelete( $this );
                 else if ( is_callable( fxprices_Preday_lowDelete ) )
	            return fxprices_Preday_lowDelete( $this );
                 else if ( is_callable( Preday_lowDelete ) )
	            return Preday_lowDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_lowDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_lowDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_lowDelete ) )
	            $returnval =  $this->fxprices_Postday_lowDelete( $this );
                 else if ( is_callable( fxprices_Postday_lowDelete ) )
	            $returnval =  fxprices_Postday_lowDelete( $this );
                 else if ( is_callable( Postday_lowDelete ) )
	            $returnval =  Postday_lowDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "day_low" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setday_low
         *	@param float  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setday_low(  $value )
         {
                 $this->day_low = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getday_low
         *	@param 
         *	@see 
         *	@return float
         ********************************************************************/
         /*@float@*//*int*/ function Getday_low()
         {
                    return $this->day_low;
         }
         /********************************************************************
         *	@function Preday_highInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_highInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_highInsert ) )
	            return $this->fxprices_Preday_highInsert( $this );
                 else if ( is_callable( fxprices_Preday_highInsert ) )
	            return fxprices_Preday_highInsert( $this );
                 else if ( is_callable( Preday_highInsert ) )
	            return Preday_highInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_highInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_highInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_highInsert ) )
	            $returnval =  $this->fxprices_Postday_highInsert( $this );
                 else if ( is_callable( fxprices_Postday_highInsert ) )
	            $returnval =  fxprices_Postday_highInsert( $this );
                 else if ( is_callable( Postday_highInsert ) )
	            $returnval =  Postday_highInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "day_high" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Preday_highUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_highUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_highUpdate ) )
	            return $this->fxprices_Preday_highUpdate( $this );
                 else if ( is_callable( fxprices_Preday_highUpdate ) )
	            return fxprices_Preday_highUpdate( $this );
                 else if ( is_callable( Preday_highUpdate ) )
	            return Preday_highUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_highUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_highUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_highUpdate ) )
	            $returnval =  $this->fxprices_Postday_highUpdate( $this );
                 else if ( is_callable( fxprices_Postday_highUpdate ) )
	            $returnval =  fxprices_Postday_highUpdate( $this );
                 else if ( is_callable( Postday_highUpdate ) )
	            $returnval =  Postday_highUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "day_high" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Preday_highDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_highDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_highDelete ) )
	            return $this->fxprices_Preday_highDelete( $this );
                 else if ( is_callable( fxprices_Preday_highDelete ) )
	            return fxprices_Preday_highDelete( $this );
                 else if ( is_callable( Preday_highDelete ) )
	            return Preday_highDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_highDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_highDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_highDelete ) )
	            $returnval =  $this->fxprices_Postday_highDelete( $this );
                 else if ( is_callable( fxprices_Postday_highDelete ) )
	            $returnval =  fxprices_Postday_highDelete( $this );
                 else if ( is_callable( Postday_highDelete ) )
	            $returnval =  Postday_highDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "day_high" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setday_high
         *	@param float  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setday_high(  $value )
         {
                 $this->day_high = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getday_high
         *	@param 
         *	@see 
         *	@return float
         ********************************************************************/
         /*@float@*//*int*/ function Getday_high()
         {
                    return $this->day_high;
         }
         /********************************************************************
         *	@function Preday_closeInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_closeInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_closeInsert ) )
	            return $this->fxprices_Preday_closeInsert( $this );
                 else if ( is_callable( fxprices_Preday_closeInsert ) )
	            return fxprices_Preday_closeInsert( $this );
                 else if ( is_callable( Preday_closeInsert ) )
	            return Preday_closeInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_closeInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_closeInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_closeInsert ) )
	            $returnval =  $this->fxprices_Postday_closeInsert( $this );
                 else if ( is_callable( fxprices_Postday_closeInsert ) )
	            $returnval =  fxprices_Postday_closeInsert( $this );
                 else if ( is_callable( Postday_closeInsert ) )
	            $returnval =  Postday_closeInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "day_close" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Preday_closeUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_closeUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_closeUpdate ) )
	            return $this->fxprices_Preday_closeUpdate( $this );
                 else if ( is_callable( fxprices_Preday_closeUpdate ) )
	            return fxprices_Preday_closeUpdate( $this );
                 else if ( is_callable( Preday_closeUpdate ) )
	            return Preday_closeUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_closeUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_closeUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_closeUpdate ) )
	            $returnval =  $this->fxprices_Postday_closeUpdate( $this );
                 else if ( is_callable( fxprices_Postday_closeUpdate ) )
	            $returnval =  fxprices_Postday_closeUpdate( $this );
                 else if ( is_callable( Postday_closeUpdate ) )
	            $returnval =  Postday_closeUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "day_close" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Preday_closeDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_closeDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_closeDelete ) )
	            return $this->fxprices_Preday_closeDelete( $this );
                 else if ( is_callable( fxprices_Preday_closeDelete ) )
	            return fxprices_Preday_closeDelete( $this );
                 else if ( is_callable( Preday_closeDelete ) )
	            return Preday_closeDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_closeDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_closeDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_closeDelete ) )
	            $returnval =  $this->fxprices_Postday_closeDelete( $this );
                 else if ( is_callable( fxprices_Postday_closeDelete ) )
	            $returnval =  fxprices_Postday_closeDelete( $this );
                 else if ( is_callable( Postday_closeDelete ) )
	            $returnval =  Postday_closeDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "day_close" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setday_close
         *	@param float  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setday_close(  $value )
         {
                 $this->day_close = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getday_close
         *	@param 
         *	@see 
         *	@return float
         ********************************************************************/
         /*@float@*//*int*/ function Getday_close()
         {
                    return $this->day_close;
         }
         /********************************************************************
         *	@function Preday_changeInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_changeInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_changeInsert ) )
	            return $this->fxprices_Preday_changeInsert( $this );
                 else if ( is_callable( fxprices_Preday_changeInsert ) )
	            return fxprices_Preday_changeInsert( $this );
                 else if ( is_callable( Preday_changeInsert ) )
	            return Preday_changeInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_changeInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_changeInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_changeInsert ) )
	            $returnval =  $this->fxprices_Postday_changeInsert( $this );
                 else if ( is_callable( fxprices_Postday_changeInsert ) )
	            $returnval =  fxprices_Postday_changeInsert( $this );
                 else if ( is_callable( Postday_changeInsert ) )
	            $returnval =  Postday_changeInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "day_change" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Preday_changeUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_changeUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_changeUpdate ) )
	            return $this->fxprices_Preday_changeUpdate( $this );
                 else if ( is_callable( fxprices_Preday_changeUpdate ) )
	            return fxprices_Preday_changeUpdate( $this );
                 else if ( is_callable( Preday_changeUpdate ) )
	            return Preday_changeUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_changeUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_changeUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_changeUpdate ) )
	            $returnval =  $this->fxprices_Postday_changeUpdate( $this );
                 else if ( is_callable( fxprices_Postday_changeUpdate ) )
	            $returnval =  fxprices_Postday_changeUpdate( $this );
                 else if ( is_callable( Postday_changeUpdate ) )
	            $returnval =  Postday_changeUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "day_change" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Preday_changeDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Preday_changeDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Preday_changeDelete ) )
	            return $this->fxprices_Preday_changeDelete( $this );
                 else if ( is_callable( fxprices_Preday_changeDelete ) )
	            return fxprices_Preday_changeDelete( $this );
                 else if ( is_callable( Preday_changeDelete ) )
	            return Preday_changeDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function Postday_changeDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function Postday_changeDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_Postday_changeDelete ) )
	            $returnval =  $this->fxprices_Postday_changeDelete( $this );
                 else if ( is_callable( fxprices_Postday_changeDelete ) )
	            $returnval =  fxprices_Postday_changeDelete( $this );
                 else if ( is_callable( Postday_changeDelete ) )
	            $returnval =  Postday_changeDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "day_change" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setday_change
         *	@param float  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setday_change(  $value )
         {
                 $this->day_change = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getday_change
         *	@param 
         *	@see 
         *	@return float
         ********************************************************************/
         /*@float@*//*int*/ function Getday_change()
         {
                    return $this->day_change;
         }
         /********************************************************************
         *	@function PreforeigncurrencyInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreforeigncurrencyInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PreforeigncurrencyInsert ) )
	            return $this->fxprices_PreforeigncurrencyInsert( $this );
                 else if ( is_callable( fxprices_PreforeigncurrencyInsert ) )
	            return fxprices_PreforeigncurrencyInsert( $this );
                 else if ( is_callable( PreforeigncurrencyInsert ) )
	            return PreforeigncurrencyInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostforeigncurrencyInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostforeigncurrencyInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PostforeigncurrencyInsert ) )
	            $returnval =  $this->fxprices_PostforeigncurrencyInsert( $this );
                 else if ( is_callable( fxprices_PostforeigncurrencyInsert ) )
	            $returnval =  fxprices_PostforeigncurrencyInsert( $this );
                 else if ( is_callable( PostforeigncurrencyInsert ) )
	            $returnval =  PostforeigncurrencyInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "foreigncurrency" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PreforeigncurrencyUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreforeigncurrencyUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PreforeigncurrencyUpdate ) )
	            return $this->fxprices_PreforeigncurrencyUpdate( $this );
                 else if ( is_callable( fxprices_PreforeigncurrencyUpdate ) )
	            return fxprices_PreforeigncurrencyUpdate( $this );
                 else if ( is_callable( PreforeigncurrencyUpdate ) )
	            return PreforeigncurrencyUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostforeigncurrencyUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostforeigncurrencyUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PostforeigncurrencyUpdate ) )
	            $returnval =  $this->fxprices_PostforeigncurrencyUpdate( $this );
                 else if ( is_callable( fxprices_PostforeigncurrencyUpdate ) )
	            $returnval =  fxprices_PostforeigncurrencyUpdate( $this );
                 else if ( is_callable( PostforeigncurrencyUpdate ) )
	            $returnval =  PostforeigncurrencyUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "foreigncurrency" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PreforeigncurrencyDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreforeigncurrencyDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PreforeigncurrencyDelete ) )
	            return $this->fxprices_PreforeigncurrencyDelete( $this );
                 else if ( is_callable( fxprices_PreforeigncurrencyDelete ) )
	            return fxprices_PreforeigncurrencyDelete( $this );
                 else if ( is_callable( PreforeigncurrencyDelete ) )
	            return PreforeigncurrencyDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostforeigncurrencyDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostforeigncurrencyDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->fxprices_PostforeigncurrencyDelete ) )
	            $returnval =  $this->fxprices_PostforeigncurrencyDelete( $this );
                 else if ( is_callable( fxprices_PostforeigncurrencyDelete ) )
	            $returnval =  fxprices_PostforeigncurrencyDelete( $this );
                 else if ( is_callable( PostforeigncurrencyDelete ) )
	            $returnval =  PostforeigncurrencyDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "foreigncurrency" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setforeigncurrency
         *	@param varchar  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setforeigncurrency(  $value )
         {
                 $this->foreigncurrency = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getforeigncurrency
         *	@param 
         *	@see 
         *	@return varchar
         ********************************************************************/
         /*@varchar@*//*int*/ function Getforeigncurrency()
         {
                    return $this->foreigncurrency;
         }
	/*********************************************************************
	*	@function update_day_change
	*	@param 
	*	@see 
	*	@return 
	*********************************************************************/
	/**//*C  C*/ function  update_day_change()
	{
		/*To update the daily_change from today and yesterday's date*/
		/*This function is generated by the generator from codemeta_functions*/
		/*	Requirements:  0*/
		/*	Use Case Who: */
		/*	Use Case When: */
		/*	Use Case What: */
		/*	Use Case Why: */
		/*	Author: Kevin <fraser.ks@gmail.com>*/
		
		$this->querystring = "update fxprices a, fxprices b
		set
		        a.day_change = (a.day_close - b.day_close)
		where
		        a.currency = b.currency
		        and a.foreigncurrency = b.foreigncurrency
		        and a.date = b.date + 1
		        and a.day_change = '0'";
		$this->GenericQuery();
		return SUCCESS;
		//If we don't have a return in the body in codemeta, return
		return ;
	}
} /* class fxprices */

require_once( 'DB/Table/Database.php' );;

class fxprices_table extends DB_Table
{
	var $col = array(
	'currency' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	'date' => array( 'type'=>'date', 'require'=>false, 'size' =>'11' ),
	'previous_close' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'day_open' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'day_low' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'day_high' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'day_close' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'day_change' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'foreigncurrency' => array( 'type'=>'varchar', 'require'=>true, 'size' =>'11' ),
	);
};
require_once( 'DB/DataObject.php' );;

class fxprices_object extends DB_DataObject
{
	var $__table='fxprices';
		//This is a Structures/DataGrid object
	var $currency;
	var $date;
	var $previous_close;
	var $day_open;
	var $day_low;
	var $day_high;
	var $day_close;
	var $day_change;
	var $foreigncurrency;
};
/*	view/QuickFormIncludes and TabbedPages.php are in the skel-app/view if required	*/
require_once( 'view/QuickFormIncludes.php' );;
require_once( 'view/TabbedPages.php' );;

class fxprices_Page1 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('fxprices page 1');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('submit', 'empty.gif');
		$this->addGlobalSubmit();
		$currency = $fs->addElement('text', 'currency', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
			->addFilter( 'trim' )
;
		$f_date = date("Y-m-d" );
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'date' => $f_date ) ) );
		$date = $fs->addElement('text', 'date', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
			->addFilter( 'trim' )
;
		$previous_close = $fs->addElement('text', 'previous_close', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
;
		$day_open = $fs->addElement('text', 'day_open', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
;
		$day_low = $fs->addElement('text', 'day_low', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
;
		$day_high = $fs->addElement('text', 'day_high', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
;
		$day_close = $fs->addElement('text', 'day_close', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
;
		$day_change = $fs->addElement('text', 'day_change', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
;
		$foreigncurrency = $fs->addElement('text', 'foreigncurrency', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Foreign Currency' )
			->addFilter( 'trim' )
			->addRule('required', 'foreigncurrency Field Required' );
	}
}
?>