<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class hedgefolios */

require_once( 'DB/Table/Database.php' );;

class hedgefolios_table extends DB_Table
{
	var $col = array(
	'idhedgefolios' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'idstockinfo' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'createddate' => array( 'type'=>'datetime', 'require'=>false, 'size' =>'11' ),
	'createduser' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'updateddate' => array( 'type'=>'timestamp', 'require'=>false, 'size' =>'11' ),
	'updateduser' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'supportlevel' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'resistancelevel' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'Volume' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'bollingerbands' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	'elliotwave' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	'fibonacci' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	'sentiment' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	'trailingpe' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'forwardpe' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'pricetobook' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'pricetosale' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'pricetocash' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'expectedgrowth' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'chartpattern' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	'candlesticks' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	);
};
?>