<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class motleyfool */

require_once( 'DB/DataObject.php' );;

class motleyfool_object extends DB_DataObject
{
	var $__table='motleyfool';
		//This is a Structures/DataGrid object
	var $doubledigitrisingsales;
	var $risingfreecashflow;
	var $risingbookvalue;
	var $improvingmargin;
	var $risingreturnonequity;
	var $insiderownership;
	var $regulardividends;
	var $doubledigitrisingsales;
	var $risingfreecashflow;
	var $risingbookvalue;
	var $improvingmargin;
	var $risingreturnonequity;
	var $insiderownership;
	var $regulardividends;
};
?>