<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class portfolio */

require_once( 'DB/DataObject.php' );;

class portfolio_object extends DB_DataObject
{
	var $__table='portfolio';
		//This is a Structures/DataGrid object
	var $idportfolio;
	var $username;
	var $account;
	var $stocksymbol;
	var $numbershares;
	var $bookvalue;
	var $dividendbookvalue;
	var $marketvalue;
	var $profitloss;
	var $marketbook;
	var $yield;
	var $currentprice;
	var $annualdividendpershare;
	var $annualdividend;
	var $dividendpercentbookvalue;
	var $dividendpercentmarketvalue;
	var $dividendyield;
	var $percenttotalmarketvalue;
	var $percenttotalbookvalue;
	var $percenttotaldividend;
	var $lastupdate;
};
?>