<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class quarter_statement */

require_once( 'DB/Table/Database.php' );;

class quarter_statement_table extends DB_Table
{
	var $col = array(
	'idfin_statement' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'idstockinfo' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'netincome' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'depletion' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'amortization' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'capitalexpenses' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'workingcapital' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'lasteval' => array( 'type'=>'timestamp', 'require'=>false, 'size' =>'11' ),
	'user' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	'outstandingshares' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'incomegrowth' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'ownerearnings' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'totalasset' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'totalliability' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'totalequity' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'totaldebt' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'dividendpershare' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'earningpershare' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'revenue' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'retainedearnings' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'revenuegrowth' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'revenuegrowth2' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	'revenuegrowth3' => array( 'type'=>'float', 'require'=>false, 'size' =>'11' ),
	);
};
?>