<?php 
//This file was generated by calling php /var/www/html/finance/generator.php acl 

//this script may only be included - so its better to die if called directly.
if (strpos($_SERVER["SCRIPT_NAME"],basename(__FILE__)) !== false) {
  header("location: ../index.php");
  exit;
}


         include_once('roletask.class.inc');

class roletask extends generictable{
          private $observers;
         function __constructor()
         {
         $this->querytablename = 'roletask';
         $this->fieldspec['idroletask']['metadata_id'] = '2884';
         $this->fieldspec['idroletask']['table_name'] = 'roletask';
         $this->fieldspec['idroletask']['column_name'] = 'idroletask';
         $this->fieldspec['idroletask']['pretty_name'] = 'Index';
         $this->fieldspec['idroletask']['abstract_data_type'] = 'index';
         $this->fieldspec['idroletask']['db_data_type'] = 'integer';
         $this->fieldspec['idroletask']['field_null'] = 'NO';
         $this->fieldspec['idroletask']['field_key'] = '0';
         $this->fieldspec['idroletask']['extra_sql'] = ' ';
         $this->fieldspec['idroletask']['html_form_type'] = 'hidden';
         $this->fieldspec['idroletask']['html_form_options'] = ' ';
         $this->fieldspec['idroletask']['html_form_explanation'] = ' ';
         $this->fieldspec['idroletask']['help_text'] = ' ';
         $this->fieldspec['idroletask']['mandatory_p'] = 'Y';
         $this->fieldspec['idroletask']['sort_key'] = '0';
         $this->fieldspec['idroletask']['form_sort_key'] = '0';
         $this->fieldspec['idroletask']['form_number'] = '1';
         $this->fieldspec['idroletask']['default_value'] = '0';
         $this->fieldspec['idroletask']['field_toupper'] = 'NO';
         $this->fieldspec['idroletask']['validationprocname'] = ' ';
         $this->fieldspec['idroletask']['c_size'] = '8';
         $this->fieldspec['idroletask']['prikey'] = 'Y';
         $this->fieldspec['idroletask']['noedit'] = 'Y';
         $this->fieldspec['idroletask']['nodisplay'] = 'N';
         $this->fieldspec['idroletask']['c_unsigned'] = 'N';
         $this->fieldspec['idroletask']['c_zerofill'] = 'N';
         $this->fieldspec['idroletask']['c_auto_increment'] = 'N';
         $this->fieldspec['idroletask']['foreign_table'] = '';
         $this->fieldspec['idroletask']['foreign_key'] = '';
         $this->fieldspec['idroletask']['application'] = 'acl';
         $this->fieldspec['idroletask']['issearchable'] = '1';
         $this->fieldspec['idroletask']['preinserttrigger'] = '';
         $this->fieldspec['idroletask']['postinserttrigger'] = '';
         $this->fieldspec['idroletask']['preupdatetrigger'] = '';
         $this->fieldspec['idroletask']['postupdatetrigger'] = '';
         $this->fieldspec['idroletask']['predeletetrigger'] = '';
         $this->fieldspec['idroletask']['postdeletetrigger'] = '';
         $this->fieldspec['roles_id']['metadata_id'] = '2885';
         $this->fieldspec['roles_id']['table_name'] = 'roletask';
         $this->fieldspec['roles_id']['column_name'] = 'roles_id';
         $this->fieldspec['roles_id']['pretty_name'] = 'Role';
         $this->fieldspec['roles_id']['abstract_data_type'] = 'integer';
         $this->fieldspec['roles_id']['db_data_type'] = 'integer';
         $this->fieldspec['roles_id']['field_null'] = 'NO';
         $this->fieldspec['roles_id']['field_key'] = '0';
         $this->fieldspec['roles_id']['extra_sql'] = ' ';
         //$this->fieldspec['roles_id']['html_form_type'] = 'fcheckbox';
         $this->fieldspec['roles_id']['html_form_type'] = 'fddl';
         $this->fieldspec['roles_id']['html_form_options'] = '<fk><field>roledescription</field><key>roles_id</key></fk>';
         $this->fieldspec['roles_id']['html_form_explanation'] = ' ';
         $this->fieldspec['roles_id']['help_text'] = ' ';
         $this->fieldspec['roles_id']['mandatory_p'] = 'Y';
         $this->fieldspec['roles_id']['sort_key'] = '0';
         $this->fieldspec['roles_id']['form_sort_key'] = '0';
         $this->fieldspec['roles_id']['form_number'] = '1';
         $this->fieldspec['roles_id']['default_value'] = '';
         $this->fieldspec['roles_id']['field_toupper'] = 'NO';
         $this->fieldspec['roles_id']['validationprocname'] = ' ';
         $this->fieldspec['roles_id']['c_size'] = '8';
         $this->fieldspec['roles_id']['prikey'] = 'N';
         $this->fieldspec['roles_id']['noedit'] = 'N';
         $this->fieldspec['roles_id']['nodisplay'] = 'N';
         $this->fieldspec['roles_id']['c_unsigned'] = 'N';
         $this->fieldspec['roles_id']['c_zerofill'] = 'N';
         $this->fieldspec['roles_id']['c_auto_increment'] = 'N';
         $this->fieldspec['roles_id']['foreign_table'] = 'roles';
         $this->fieldspec['roles_id']['foreign_key'] = 'roles_id';
         $this->fieldspec['roles_id']['application'] = 'acl';
         $this->fieldspec['roles_id']['issearchable'] = '1';
         $this->fieldspec['roles_id']['preinserttrigger'] = '';
         $this->fieldspec['roles_id']['postinserttrigger'] = '';
         $this->fieldspec['roles_id']['preupdatetrigger'] = '';
         $this->fieldspec['roles_id']['postupdatetrigger'] = '';
         $this->fieldspec['roles_id']['predeletetrigger'] = '';
         $this->fieldspec['roles_id']['postdeletetrigger'] = '';
         $this->fieldspec['idtasks']['metadata_id'] = '2886';
         $this->fieldspec['idtasks']['table_name'] = 'roletask';
         $this->fieldspec['idtasks']['column_name'] = 'idtasks';
         $this->fieldspec['idtasks']['pretty_name'] = 'Task';
         $this->fieldspec['idtasks']['abstract_data_type'] = 'integer';
         $this->fieldspec['idtasks']['db_data_type'] = 'integer';
         $this->fieldspec['idtasks']['field_null'] = 'NO';
         $this->fieldspec['idtasks']['field_key'] = '0';
         $this->fieldspec['idtasks']['extra_sql'] = ' ';
         //$this->fieldspec['idtasks']['html_form_type'] = 'fcheckbox';
         $this->fieldspec['idtasks']['html_form_type'] = 'fddl';
         $this->fieldspec['idtasks']['html_form_options'] = '<fk><field>taskdescription</field><key>idtasks</key></fk>';
         $this->fieldspec['idtasks']['html_form_explanation'] = ' ';
         $this->fieldspec['idtasks']['help_text'] = ' ';
         $this->fieldspec['idtasks']['mandatory_p'] = 'Y';
         $this->fieldspec['idtasks']['sort_key'] = '0';
         $this->fieldspec['idtasks']['form_sort_key'] = '0';
         $this->fieldspec['idtasks']['form_number'] = '1';
         $this->fieldspec['idtasks']['default_value'] = '';
         $this->fieldspec['idtasks']['field_toupper'] = 'NO';
         $this->fieldspec['idtasks']['validationprocname'] = ' ';
         $this->fieldspec['idtasks']['c_size'] = '8';
         $this->fieldspec['idtasks']['prikey'] = 'N';
         $this->fieldspec['idtasks']['noedit'] = 'N';
         $this->fieldspec['idtasks']['nodisplay'] = 'N';
         $this->fieldspec['idtasks']['c_unsigned'] = 'N';
         $this->fieldspec['idtasks']['c_zerofill'] = 'N';
         $this->fieldspec['idtasks']['c_auto_increment'] = 'N';
         $this->fieldspec['idtasks']['foreign_table'] = 'tasks';
         $this->fieldspec['idtasks']['foreign_key'] = 'idtasks';
         $this->fieldspec['idtasks']['application'] = 'acl';
         $this->fieldspec['idtasks']['issearchable'] = '1';
         $this->fieldspec['idtasks']['preinserttrigger'] = '';
         $this->fieldspec['idtasks']['postinserttrigger'] = '';
         $this->fieldspec['idtasks']['preupdatetrigger'] = '';
         $this->fieldspec['idtasks']['postupdatetrigger'] = '';
         $this->fieldspec['idtasks']['predeletetrigger'] = '';
         $this->fieldspec['idtasks']['postdeletetrigger'] = '';
         $this->fieldlist = array('idroletask', 'roles_id', 'idtasks');
         $this->searchlist = array('idroletask', 'roles_id', 'idtasks');
	         return SUCCESS;
         }
         function roletask()
         { //For older php which doesn't have constructor
              return $this->__constructor();
         }
         function Push()
         {
	         $_SESSION['roletask'] = serialize($this);
	         return SUCCESS;
         }
         function Pop()
         {
                 //Can't do this in self - this is how to do it outside
	       //  $this = unserialize($_SESSION['roletask']);
	         return SUCCESS;
         }
         function ObserverRegister( $observer)
         {
                 $this->observers[] = $observer;
	         return SUCCESS;
         }
         function ObserverDeRegister( $observer )
         {
                 $this->observers[] = array_diff( $this->observers, array( $observer) );
	         return SUCCESS;
         }
         function ObserverNotify()
         {
                 foreach ( $this->observers as $obs ) 
                 {
                      $obs->update( $this );
                 }
	         return SUCCESS;
         }
         function Setidtasks($value)
         {
                  $this->fieldspec['idtasks']['VALUE'] = $value;
	          return SUCCESS;
         }
         function Getidtasks()
         {
                    return $this->fieldspec['idtasks']['VALUE'];
         }
         function Validateidtasks()
         {
         }
} /* class roletask */
