<?php 
//This file was generated by calling php /var/www/html/finance/generator.php statemachine 

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

include_once('stateflowrole.extend.php');

class stateflowrole extends generictable 
{
         private $observers;
         var $pretty_name = '';
         var $pretty_plural = '';
         var $pageheader = '';
         var $pagefooter = '';
         var $data; //data passed in by other calls
         var $idstateflowrole;
		 /*Workflow-Role ID */
         var $roles_id;
		 /*Role ID */
         var $workflow_id;
		 /*Workflow ID */
         function __constructor()
         {
         $this->querytablename = 'stateflowrole';
         $this->fieldspec['idstateflowrole']['metadata_id'] = '3087';
         $this->fieldspec['idstateflowrole']['table_name'] = 'stateflowrole';
         $this->fieldspec['idstateflowrole']['column_name'] = 'idstateflowrole';
         $this->fieldspec['idstateflowrole']['pretty_name'] = 'Workflow-Role ID';
         $this->fieldspec['idstateflowrole']['abstract_data_type'] = 'int';
         $this->fieldspec['idstateflowrole']['db_data_type'] = 'int';
         $this->fieldspec['idstateflowrole']['field_null'] = 'NO';
         $this->fieldspec['idstateflowrole']['field_key'] = '';
         $this->fieldspec['idstateflowrole']['extra_sql'] = ' ';
         $this->fieldspec['idstateflowrole']['html_form_type'] = 'integer';
         $this->fieldspec['idstateflowrole']['html_form_options'] = ' ';
         $this->fieldspec['idstateflowrole']['html_form_explanation'] = ' ';
         $this->fieldspec['idstateflowrole']['help_text'] = ' ';
         $this->fieldspec['idstateflowrole']['mandatory_p'] = 'Y';
         $this->fieldspec['idstateflowrole']['sort_key'] = '0';
         $this->fieldspec['idstateflowrole']['form_sort_key'] = '0';
         $this->fieldspec['idstateflowrole']['form_number'] = '1';
         $this->fieldspec['idstateflowrole']['default_value'] = '0';
         $this->fieldspec['idstateflowrole']['field_toupper'] = 'NO';
         $this->fieldspec['idstateflowrole']['validationprocname'] = ' ';
         $this->fieldspec['idstateflowrole']['c_size'] = '8';
         $this->fieldspec['idstateflowrole']['prikey'] = 'Y';
         $this->fieldspec['idstateflowrole']['noedit'] = 'N';
         $this->fieldspec['idstateflowrole']['nodisplay'] = 'N';
         $this->fieldspec['idstateflowrole']['c_unsigned'] = 'N';
         $this->fieldspec['idstateflowrole']['c_zerofill'] = 'N';
         $this->fieldspec['idstateflowrole']['c_auto_increment'] = 'N';
         $this->fieldspec['idstateflowrole']['foreign_table'] = '';
         $this->fieldspec['idstateflowrole']['foreign_key'] = '';
         $this->fieldspec['idstateflowrole']['application'] = 'statemachine';
         $this->fieldspec['idstateflowrole']['issearchable'] = '0';
         $this->fieldspec['idstateflowrole']['preinserttrigger'] = '';
         $this->fieldspec['idstateflowrole']['postinserttrigger'] = '';
         $this->fieldspec['idstateflowrole']['preupdatetrigger'] = '';
         $this->fieldspec['idstateflowrole']['postupdatetrigger'] = '';
         $this->fieldspec['idstateflowrole']['predeletetrigger'] = '';
         $this->fieldspec['idstateflowrole']['postdeletetrigger'] = '';
         $this->fieldspec['roles_id']['metadata_id'] = '3088';
         $this->fieldspec['roles_id']['table_name'] = 'stateflowrole';
         $this->fieldspec['roles_id']['column_name'] = 'roles_id';
         $this->fieldspec['roles_id']['pretty_name'] = 'Role ID';
         $this->fieldspec['roles_id']['abstract_data_type'] = 'int';
         $this->fieldspec['roles_id']['db_data_type'] = 'int';
         $this->fieldspec['roles_id']['field_null'] = 'NO';
         $this->fieldspec['roles_id']['field_key'] = '';
         $this->fieldspec['roles_id']['extra_sql'] = ' ';
         $this->fieldspec['roles_id']['html_form_type'] = 'fddl';
         $this->fieldspec['roles_id']['html_form_options'] = '<fk><field>roledescription</field></fk>';
         $this->fieldspec['roles_id']['html_form_explanation'] = ' ';
         $this->fieldspec['roles_id']['help_text'] = ' ';
         $this->fieldspec['roles_id']['mandatory_p'] = 'Y';
         $this->fieldspec['roles_id']['sort_key'] = '0';
         $this->fieldspec['roles_id']['form_sort_key'] = '0';
         $this->fieldspec['roles_id']['form_number'] = '1';
         $this->fieldspec['roles_id']['default_value'] = '0';
         $this->fieldspec['roles_id']['field_toupper'] = 'NO';
         $this->fieldspec['roles_id']['validationprocname'] = ' ';
         $this->fieldspec['roles_id']['c_size'] = '8';
         $this->fieldspec['roles_id']['prikey'] = 'N';
         $this->fieldspec['roles_id']['noedit'] = 'N';
         $this->fieldspec['roles_id']['nodisplay'] = 'N';
         $this->fieldspec['roles_id']['c_unsigned'] = 'N';
         $this->fieldspec['roles_id']['c_zerofill'] = 'N';
         $this->fieldspec['roles_id']['c_auto_increment'] = 'N';
         $this->fieldspec['roles_id']['foreign_table'] = 'roles';
         $this->fieldspec['roles_id']['foreign_key'] = 'roles_id';
         $this->fieldspec['roles_id']['application'] = 'statemachine';
         $this->fieldspec['roles_id']['issearchable'] = '1';
         $this->fieldspec['roles_id']['preinserttrigger'] = '';
         $this->fieldspec['roles_id']['postinserttrigger'] = '';
         $this->fieldspec['roles_id']['preupdatetrigger'] = '';
         $this->fieldspec['roles_id']['postupdatetrigger'] = '';
         $this->fieldspec['roles_id']['predeletetrigger'] = '';
         $this->fieldspec['roles_id']['postdeletetrigger'] = '';
         $this->fieldspec['workflow_id']['metadata_id'] = '3089';
         $this->fieldspec['workflow_id']['table_name'] = 'stateflowrole';
         $this->fieldspec['workflow_id']['column_name'] = 'workflow_id';
         $this->fieldspec['workflow_id']['pretty_name'] = 'Workflow ID';
         $this->fieldspec['workflow_id']['abstract_data_type'] = 'int';
         $this->fieldspec['workflow_id']['db_data_type'] = 'int';
         $this->fieldspec['workflow_id']['field_null'] = 'NO';
         $this->fieldspec['workflow_id']['field_key'] = '';
         $this->fieldspec['workflow_id']['extra_sql'] = ' ';
         $this->fieldspec['workflow_id']['html_form_type'] = 'fddl';
         $this->fieldspec['workflow_id']['html_form_options'] = '<fk><field>workflow_name</field></fk>';
         $this->fieldspec['workflow_id']['html_form_explanation'] = ' ';
         $this->fieldspec['workflow_id']['help_text'] = ' ';
         $this->fieldspec['workflow_id']['mandatory_p'] = 'N';
         $this->fieldspec['workflow_id']['sort_key'] = '0';
         $this->fieldspec['workflow_id']['form_sort_key'] = '0';
         $this->fieldspec['workflow_id']['form_number'] = '1';
         $this->fieldspec['workflow_id']['default_value'] = '0';
         $this->fieldspec['workflow_id']['field_toupper'] = 'NO';
         $this->fieldspec['workflow_id']['validationprocname'] = ' ';
         $this->fieldspec['workflow_id']['c_size'] = '8';
         $this->fieldspec['workflow_id']['prikey'] = 'N';
         $this->fieldspec['workflow_id']['noedit'] = 'N';
         $this->fieldspec['workflow_id']['nodisplay'] = 'N';
         $this->fieldspec['workflow_id']['c_unsigned'] = 'N';
         $this->fieldspec['workflow_id']['c_zerofill'] = 'N';
         $this->fieldspec['workflow_id']['c_auto_increment'] = 'N';
         $this->fieldspec['workflow_id']['foreign_table'] = 'stateworkflow';
         $this->fieldspec['workflow_id']['foreign_key'] = 'workflow_id';
         $this->fieldspec['workflow_id']['application'] = 'statemachine';
         $this->fieldspec['workflow_id']['issearchable'] = '1';
         $this->fieldspec['workflow_id']['preinserttrigger'] = '';
         $this->fieldspec['workflow_id']['postinserttrigger'] = '';
         $this->fieldspec['workflow_id']['preupdatetrigger'] = '';
         $this->fieldspec['workflow_id']['postupdatetrigger'] = '';
         $this->fieldspec['workflow_id']['predeletetrigger'] = '';
         $this->fieldspec['workflow_id']['postdeletetrigger'] = '';
         $this->fieldlist = array('idstateflowrole', 'roles_id', 'workflow_id');
         $this->searchlist = array('roles_id', 'workflow_id', );
	         return SUCCESS;
         }
         function stateflowrole()
         { //For older php which doesn't have constructor
              return $this->__constructor();
         }
         function Push()
         {
	         $_SESSION['stateflowrole'] = serialize($this);
	         return SUCCESS;
         }
         function Pop()
         {
                 //Can't do this in self - this is how to do it outside
	       //  $this = unserialize($_SESSION['stateflowrole']);
	         return SUCCESS;
         }
         function ObserverRegister( $observer, $event )
         {
                 $this->observers[$event][] = $observer;
	         return SUCCESS;
         }
         function ObserverDeRegister( $observer )
         {
                 $this->observers[] = array_diff( $this->observers, array( $observer) );
	         return SUCCESS;
         }
         function ObserverNotify( $event, $msg )
         {
                 if ( isset( $this->observers[$event] ) )
                 	foreach ( $this->observers[$event] as $obs ) 
                 	{
                      		$obs->notify( $event, $msg );
                 	}
                 /* '**' being used as 'ALL' */
                 if ( isset( $this->observers['**'] ) )
                 	foreach ( $this->observers['**'] as $obs ) 
                 	{
                      		$obs->notify( $event, $msg );
                 	}
	         return SUCCESS;
         }
         function notify( $object )
         {
                 //Called when another object we are observing sends us a notification
	         return SUCCESS;
         }
         function PreidstateflowroleInsert( $data )
         {
         $this->data = $data;
                 if ( is_callable( PreidstateflowroleInsert ) )
	            return PreidstateflowroleInsert( $this );
                 else return;
         }
         function PostidstateflowroleInsert( $data )
         {
         $this->data = $data;
                 if ( is_callable( PreidstateflowroleInsert ) )
	            return PreidstateflowroleInsert( $this );
                 else return;
         }
         function PreidstateflowroleUpdate( $data )
         {
         $this->data = $data;
                 if ( is_callable( PreidstateflowroleUpdate ) )
	            return PreidstateflowroleUpdate( $this );
                 else return;
         }
         function PostidstateflowroleUpdate( $data )
         {
         $this->data = $data;
                 if ( is_callable( PreidstateflowroleUpdate ) )
	            return PreidstateflowroleUpdate( $this );
                 else return;
         }
         function PreidstateflowroleDelete( $data )
         {
         $this->data = $data;
                 if ( is_callable( PreidstateflowroleDelete ) )
	            return PreidstateflowroleDelete( $this );
                 else return;
         }
         function PostidstateflowroleDelete( $data )
         {
         $this->data = $data;
                 if ( is_callable( PreidstateflowroleDelete ) )
	            return PreidstateflowroleDelete( $this );
                 else return;
         }
         function PreidstateflowroleSelect( $data )
         {
         $this->data = $data;
                 if ( is_callable( PreidstateflowroleSelect ) )
	            return PreidstateflowroleSelect( $this );
                 else return;
         }
         function PostidstateflowroleSelect( $data )
         {
         $this->data = $data;
                 if ( is_callable( PreidstateflowroleSelect ) )
	            return PreidstateflowroleSelect( $this );
                 else return;
         }
         function PreidstateflowroleShow( $data )
         {
         $this->data = $data;
                 if ( is_callable( PreidstateflowroleShow ) )
	            return PreidstateflowroleShow( $this );
                 else return;
         }
         function PostidstateflowroleShow( $data )
         {
         $this->data = $data;
                 if ( is_callable( PreidstateflowroleShow ) )
	            return PreidstateflowroleShow( $this );
                 else return;
         }
         function Setidstateflowrole($value)
         {
                 $this->idstateflowrole = $value;
	          return SUCCESS;
         }
         function Getidstateflowrole()
         {
                    return $this->idstateflowrole;
         }
         function Preroles_idInsert( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preroles_idInsert ) )
	            return Preroles_idInsert( $this );
                 else return;
         }
         function Postroles_idInsert( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preroles_idInsert ) )
	            return Preroles_idInsert( $this );
                 else return;
         }
         function Preroles_idUpdate( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preroles_idUpdate ) )
	            return Preroles_idUpdate( $this );
                 else return;
         }
         function Postroles_idUpdate( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preroles_idUpdate ) )
	            return Preroles_idUpdate( $this );
                 else return;
         }
         function Preroles_idDelete( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preroles_idDelete ) )
	            return Preroles_idDelete( $this );
                 else return;
         }
         function Postroles_idDelete( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preroles_idDelete ) )
	            return Preroles_idDelete( $this );
                 else return;
         }
         function Preroles_idSelect( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preroles_idSelect ) )
	            return Preroles_idSelect( $this );
                 else return;
         }
         function Postroles_idSelect( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preroles_idSelect ) )
	            return Preroles_idSelect( $this );
                 else return;
         }
         function Preroles_idShow( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preroles_idShow ) )
	            return Preroles_idShow( $this );
                 else return;
         }
         function Postroles_idShow( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preroles_idShow ) )
	            return Preroles_idShow( $this );
                 else return;
         }
         function Setroles_id($value)
         {
                 $this->roles_id = $value;
	          return SUCCESS;
         }
         function Getroles_id()
         {
                    return $this->roles_id;
         }
         function Preworkflow_idInsert( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preworkflow_idInsert ) )
	            return Preworkflow_idInsert( $this );
                 else return;
         }
         function Postworkflow_idInsert( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preworkflow_idInsert ) )
	            return Preworkflow_idInsert( $this );
                 else return;
         }
         function Preworkflow_idUpdate( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preworkflow_idUpdate ) )
	            return Preworkflow_idUpdate( $this );
                 else return;
         }
         function Postworkflow_idUpdate( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preworkflow_idUpdate ) )
	            return Preworkflow_idUpdate( $this );
                 else return;
         }
         function Preworkflow_idDelete( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preworkflow_idDelete ) )
	            return Preworkflow_idDelete( $this );
                 else return;
         }
         function Postworkflow_idDelete( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preworkflow_idDelete ) )
	            return Preworkflow_idDelete( $this );
                 else return;
         }
         function Preworkflow_idSelect( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preworkflow_idSelect ) )
	            return Preworkflow_idSelect( $this );
                 else return;
         }
         function Postworkflow_idSelect( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preworkflow_idSelect ) )
	            return Preworkflow_idSelect( $this );
                 else return;
         }
         function Preworkflow_idShow( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preworkflow_idShow ) )
	            return Preworkflow_idShow( $this );
                 else return;
         }
         function Postworkflow_idShow( $data )
         {
         $this->data = $data;
                 if ( is_callable( Preworkflow_idShow ) )
	            return Preworkflow_idShow( $this );
                 else return;
         }
         function Setworkflow_id($value)
         {
                 $this->workflow_id = $value;
	          return SUCCESS;
         }
         function Getworkflow_id()
         {
                    return $this->workflow_id;
         }
} /* class stateflowrole */
