<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class stockalert */

require_once( 'DB/Table/Database.php' );;

class stockalert_table extends DB_Table
{
	var $col = array(
	'idstockalert' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'idalerts' => array( 'type'=>'int', 'require'=>true, 'size' =>'11' ),
	'idstockinfo' => array( 'type'=>'int', 'require'=>true, 'size' =>'11' ),
	'username' => array( 'type'=>'varchar', 'require'=>true, 'size' =>'45' ),
	'value1' => array( 'type'=>'varchar', 'require'=>true, 'size' =>'45' ),
	'value2' => array( 'type'=>'varchar', 'require'=>true, 'size' =>'45' ),
	'runonce' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'runstatus' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	);
};
?>