<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class transaction */

require_once( 'DB/Table/Database.php' );;

class transaction_table extends DB_Table
{
	var $col = array(
	'idusers' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'account' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	'currency' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	'foreigncurrency' => array( 'type'=>'varchar', 'require'=>false, 'size' =>'11' ),
	'idstockinfo' => array( 'type'=>'int', 'require'=>false, 'size' =>'11' ),
	'transactiondate' => array( 'type'=>'date', 'require'=>false, 'size' =>'10' ),
	'createduser' => array( 'type'=>'int', 'require'=>false, 'size' =>'10' ),
	'createddate' => array( 'type'=>'date', 'require'=>false, 'size' =>'10' ),
	'reviseduser' => array( 'type'=>'int', 'require'=>false, 'size' =>'10' ),
	'reviseddate' => array( 'type'=>'date', 'require'=>false, 'size' =>'10' ),
	'sequence' => array( 'type'=>'integer', 'require'=>false, 'size' =>'11' ),
	'username' => array( 'type'=>'varchar', 'require'=>true, 'size' =>'45' ),
	'stocksymbol' => array( 'type'=>'varchar', 'require'=>true, 'size' =>'45' ),
	'numbershares' => array( 'type'=>'integer', 'require'=>true, 'size' =>'11' ),
	'transactiontype' => array( 'type'=>'varchar', 'require'=>true, 'size' =>'45' ),
	'dollar' => array( 'type'=>'float', 'require'=>true, 'size' =>'45' ),
	);
};
?>