<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class turtledata */

require_once( 'DB/DataObject.php' );;

class turtledata_object extends DB_DataObject
{
	var $__table='turtledata';
		//This is a Structures/DataGrid object
	var $idturtledata;
	var $symbol;
	var $date;
	var $createddate;
	var $createduser;
	var $updateddate;
	var $updateduser;
	var $volatility;
	var $unit;
	var $breakouthigh20;
	var $breakoutlow20;
	var $breakouthigh55;
	var $breakoutlow55;
	var $low10;
	var $high10;
	var $low20;
	var $high20;
	var $truerange;
	var $ignore20;
	var $positionadd;
	var $sellallprice;
	var $normalizedprice;
};
?>