<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

class turtledates extends generictable 
{
	/*char * */ var $pretty_name = '';
	/*char * */ var $pretty_plural = '';
	/*char * */ var $pageheader = '';
	/*char * */ var $pagefooter = '';
         private $observers;
	/*char * */ var $data; //data passed in by other calls
/********************************************************
 *
 *	This section is the table columns
 *
 *******************************************************/
         var          /*char* *//* date */ $turtledates;
		 /*The dates for which turtledata values have been calculated */
         function __construct()
         {
         	$this->querytablename = 'turtledates';
         	$this->classname = 'turtledates';
         	$this->fieldspec['turtledates']['metadata_id'] = '6814';
         	$this->fieldspec['turtledates']['table_name'] = 'turtledates';
         	$this->fieldspec['turtledates']['column_name'] = 'turtledates';
         	$this->fieldspec['turtledates']['pretty_name'] = 'The dates for which turtledata values have been calculated';
         	$this->fieldspec['turtledates']['abstract_data_type'] = 'date';
         	$this->fieldspec['turtledates']['db_data_type'] = 'date';
         	$this->fieldspec['turtledates']['field_null'] = 'YES';
         	$this->fieldspec['turtledates']['field_key'] = '';
         	$this->fieldspec['turtledates']['extra_sql'] = ' ';
         	$this->fieldspec['turtledates']['html_form_type'] = 'date';
         	$this->fieldspec['turtledates']['html_form_options'] = '';
         	$this->fieldspec['turtledates']['html_link_options'] = '';
         	$this->fieldspec['turtledates']['html_form_explanation'] = 'The dates for which turtledata values have been calculated';
         	$this->fieldspec['turtledates']['help_text'] = '';
         	$this->fieldspec['turtledates']['mandatory_p'] = 'N';
         	$this->fieldspec['turtledates']['sort_key'] = '0';
         	$this->fieldspec['turtledates']['form_sort_key'] = '0';
         	$this->fieldspec['turtledates']['form_number'] = '1';
         	$this->fieldspec['turtledates']['default_value'] = '';
         	$this->fieldspec['turtledates']['field_toupper'] = 'NO';
         	$this->fieldspec['turtledates']['validationprocname'] = '';
         	$this->fieldspec['turtledates']['minlength'] = '1';
         	$this->fieldspec['turtledates']['maxlength'] = '20';
         	$this->fieldspec['turtledates']['c_size'] = '20';
         	$this->fieldspec['turtledates']['prikey'] = 'Y';
         	$this->fieldspec['turtledates']['noedit'] = 'Y';
         	$this->fieldspec['turtledates']['nodisplay'] = 'Y';
         	$this->fieldspec['turtledates']['c_unsigned'] = 'N';
         	$this->fieldspec['turtledates']['c_zerofill'] = 'N';
         	$this->fieldspec['turtledates']['c_auto_increment'] = 'N';
         	$this->fieldspec['turtledates']['foreign_table'] = '';
         	$this->fieldspec['turtledates']['foreign_key'] = '';
         	$this->fieldspec['turtledates']['application'] = 'finance';
         	$this->fieldspec['turtledates']['issearchable'] = '1';
         	$this->fieldspec['turtledates']['preinserttrigger'] = '';
         	$this->fieldspec['turtledates']['postinserttrigger'] = '';
         	$this->fieldspec['turtledates']['preupdatetrigger'] = '';
         	$this->fieldspec['turtledates']['postupdatetrigger'] = '';
         	$this->fieldspec['turtledates']['predeletetrigger'] = '';
         	$this->fieldspec['turtledates']['postdeletetrigger'] = '';
         	$this->fieldspec['turtledates']['definition_version'] = '1';
         	$this->fieldspec['turtledates']['form_javascript'] = '';
         	$this->fieldspec['turtledates']['rowSecurityProc'] = '';
         	$this->fieldspec['turtledates']['postinsert'] = 'PostturtledatesInsert';
         	$this->fieldspec['turtledates']['postupdate'] = 'PostturtledatesUpdate';
         	$this->fieldspec['turtledates']['postdelete'] = 'PostturtledatesDelete';
         	$this->fieldspec['turtledates']['preinsert'] = 'PreturtledatesInsert';
         	$this->fieldspec['turtledates']['preupdate'] = 'PreturtledatesUpdate';
         	$this->fieldspec['turtledates']['predelete'] = 'PreturtledatesDelete';
         	$this->fieldlist = array('turtledates');
         	$this->searchlist = array('turtledates');
         	$this->prikeylist = array('turtledates');
		$this->defaultsort = '';
	         return SUCCESS;
         }
         /*void*/ function  turtledates()
         { //For older php which doesn't have constructor
              return $this->__construct();
         }
         /*@bool@*//*int*/ function Push()
         {
	         $_SESSION['turtledates'] = serialize($this);
	         return SUCCESS;
         }
         /*@bool@*//*int*/ function Pop()
         {
                 //Can't do this in self - this is how to do it outside
	       //  $this = unserialize($_SESSION['turtledates']);
	         return SUCCESS;
         }
         /********************************************************************
         *	@function ObserverRegister
         *	@param class observer 
         *	@param string event 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function ObserverRegister(  $observer,  $event )
         {
                 $this->observers[$event][] = $observer;
	         return SUCCESS;
         }
         /********************************************************************
         *	@function ObserverDeRegister
         *	@param class observer
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function ObserverDeRegister( $observer )
         {
                 $this->observers[] = array_diff( $this->observers, array( $observer) );
	         return SUCCESS;
         }
         /********************************************************************
         *	@function ObserverNotify
         *	@param string event
         *	@param string msg 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function ObserverNotify(  $event,  $msg )
         {
                 if ( isset( $this->observers[$event] ) )
                 	foreach ( $this->observers[$event] as $obs ) 
                 	{
                      		$obs->notify( $event, $msg );
                 	}
                 /* '**' being used as 'ALL' */
                 if ( isset( $this->observers['**'] ) )
                 	foreach ( $this->observers['**'] as $obs ) 
                 	{
                      		$obs->notify( $event, $msg );
                 	}
	         return SUCCESS;
         }
         /********************************************************************
         *	@function notify
         *	@param class object 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function notify(  $object )
         {
                 //Called when another object we are observing sends us a notification
	         return SUCCESS;
         }
         /********************************************************************
         *	@function PreturtledatesInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreturtledatesInsert(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->turtledates_PreturtledatesInsert ) )
	            return $this->turtledates_PreturtledatesInsert( $this );
                 else if ( is_callable( turtledates_PreturtledatesInsert ) )
	            return turtledates_PreturtledatesInsert( $this );
                 else if ( is_callable( PreturtledatesInsert ) )
	            return PreturtledatesInsert( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostturtledatesInsert
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostturtledatesInsert(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->turtledates_PostturtledatesInsert ) )
	            $returnval =  $this->turtledates_PostturtledatesInsert( $this );
                 else if ( is_callable( turtledates_PostturtledatesInsert ) )
	            $returnval =  turtledates_PostturtledatesInsert( $this );
                 else if ( is_callable( PostturtledatesInsert ) )
	            $returnval =  PostturtledatesInsert( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Insert", "turtledates" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PreturtledatesUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreturtledatesUpdate(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->turtledates_PreturtledatesUpdate ) )
	            return $this->turtledates_PreturtledatesUpdate( $this );
                 else if ( is_callable( turtledates_PreturtledatesUpdate ) )
	            return turtledates_PreturtledatesUpdate( $this );
                 else if ( is_callable( PreturtledatesUpdate ) )
	            return PreturtledatesUpdate( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostturtledatesUpdate
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostturtledatesUpdate(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->turtledates_PostturtledatesUpdate ) )
	            $returnval =  $this->turtledates_PostturtledatesUpdate( $this );
                 else if ( is_callable( turtledates_PostturtledatesUpdate ) )
	            $returnval =  turtledates_PostturtledatesUpdate( $this );
                 else if ( is_callable( PostturtledatesUpdate ) )
	            $returnval =  PostturtledatesUpdate( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Update", "turtledates" );
                 return $returnval;
         }
         /********************************************************************
         *	@function PreturtledatesDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PreturtledatesDelete(  $data )
         {
         $this->data = $data;
                 if ( is_callable( $this->turtledates_PreturtledatesDelete ) )
	            return $this->turtledates_PreturtledatesDelete( $this );
                 else if ( is_callable( turtledates_PreturtledatesDelete ) )
	            return turtledates_PreturtledatesDelete( $this );
                 else if ( is_callable( PreturtledatesDelete ) )
	            return PreturtledatesDelete( $this );
                 else return;
         }
         /********************************************************************
         *	@function PostturtledatesDelete
         *	@param 
         *	@see 
         *	@return int
         ********************************************************************/
         /*int*/ function PostturtledatesDelete(  $data,  $lastinsert = 0 )
         {
         $this->data = $data;
                 if ( is_callable( $this->turtledates_PostturtledatesDelete ) )
	            $returnval =  $this->turtledates_PostturtledatesDelete( $this );
                 else if ( is_callable( turtledates_PostturtledatesDelete ) )
	            $returnval =  turtledates_PostturtledatesDelete( $this );
                 else if ( is_callable( PostturtledatesDelete ) )
	            $returnval =  PostturtledatesDelete( $this );
                 else $returnval = NULL;
                 $this->ObserverNotify( "Delete", "turtledates" );
                 return $returnval;
         }
         /********************************************************************
         *	@function Setturtledates
         *	@param date  $value 
         *	@see 
         *	@return bool
         ********************************************************************/
         /*@bool@*//*int*/ function Setturtledates(  $value )
         {
                 $this->turtledates = $value;
	          return SUCCESS;
         }
         /********************************************************************
         *	@function Getturtledates
         *	@param 
         *	@see 
         *	@return date
         ********************************************************************/
         /*@date@*//*int*/ function Getturtledates()
         {
                    return $this->turtledates;
         }
} /* class turtledates */

require_once( 'DB/Table/Database.php' );;

class turtledates_table extends DB_Table
{
	var $col = array(
	'turtledates' => array( 'type'=>'date', 'require'=>false, 'size' =>'20' ),
	);
};
require_once( 'DB/DataObject.php' );;

class turtledates_object extends DB_DataObject
{
	var $__table='turtledates';
		//This is a Structures/DataGrid object
	var $turtledates;
};
/*	view/QuickFormIncludes and TabbedPages.php are in the skel-app/view if required	*/
require_once( 'view/QuickFormIncludes.php' );;
require_once( 'view/TabbedPages.php' );;

class turtledates_Page1 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('turtledates page 1');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('submit', 'empty.gif');
		$this->addGlobalSubmit();
		$f_date = date("Y-m-d" );
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'turtledates' => $f_date ) ) );
		$turtledates = $fs->addElement('text', 'turtledates', array('size' => 20, 'maxlength' => 20) )
			->setLabel( 'The dates for which turtledata values have been calculated' )
			->addFilter( 'trim' )
;
	}
}
?>