<?php
/** Advisor Research Briefs */
$briefs = $data['briefs'] ?? [];
$mode = $data['mode'] ?? 'all';
$category = $data['category'] ?? 'all';
?>
<div class="card" style="margin-bottom:24px;">
    <div class="card-header">&#x1F4DC; Strategy Research Briefs</div>
    <p style="margin-bottom:16px;">
        Daily briefs generated by the Research Agent. Internal briefs use your
        system data (ATR optimization, evaluation scores, fundamentals).
        External briefs scan Reddit, arXiv, TradingView for new strategy ideas.
    </p>

    <!-- Filters -->
    <form method="get" action="?action=advisor" style="margin-bottom:16px;display:flex;gap:8px;flex-wrap:wrap;align-items:center;">
        <input type="hidden" name="action" value="advisor">
        <input type="hidden" name="view" value="research">
        <label>Mode:
            <select name="mode">
                <option value="all" <?= $mode==='all'?'selected':'' ?>>All</option>
                <option value="internal" <?= $mode==='internal'?'selected':'' ?>>Internal</option>
                <option value="external" <?= $mode==='external'?'selected':'' ?>>External</option>
            </select>
        </label>
        <label>Category:
            <select name="category">
                <option value="all" <?= $category==='all'?'selected':'' ?>>All</option>
                <option value="internal">Internal</option>
                <option value="external">External</option>
                <option value="general">General</option>
            </select>
        </label>
        <button type="submit" class="btn btn-sm">Filter</button>
        <a href="?action=advisor&view=research&mode=all&category=all" class="btn btn-sm btn-secondary">Reset</a>
    </form>
</div>

<?php if (empty($briefs)): ?>
<div class="card">
    <p>No briefs for today yet. The nightly cron runs at 02:00.</p>
</div>
<?php else: ?>
    <?php foreach ($briefs as $b): ?>
    <div class="card" style="margin-bottom:16px;border-left:4px solid var(--accent);">
        <div class="card-header">
            <?= htmlspecialchars($b['title']) ?>
            <span style="float:right;font-size:0.85em;color:var(--text3);">
                <?= htmlspecialchars($b['mode']) ?> · <?= htmlspecialchars($b['category']) ?>
                · <?= htmlspecialchars($b['brief_date']) ?>
            </span>
        </div>
        <?php if (!empty($b['source_url'])): ?>
        <p style="margin-bottom:8px;">
            <a href="<?= htmlspecialchars($b['source_url']) ?>" target="_blank">Source</a>
        </p>
        <?php endif; ?>
        <div style="white-space:pre-wrap;font-family:monospace;font-size:0.9em;background:rgba(0,0,0,0.15);padding:12px;border-radius:6px;"><?= htmlspecialchars($b['summary']) ?></div>
        <?php if (!empty($b['recommendation'])): ?>
        <p style="margin-top:12px;color:var(--accent);"><strong>Recommendation:</strong> <?= htmlspecialchars($b['recommendation']) ?></p>
        <?php endif; ?>
        <?php if (!empty($b['scores'])): ?>
        <p style="margin-top:8px;color:var(--text3);"><strong>Scores:</strong> <?= htmlspecialchars(json_encode($b['scores'])) ?></p>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
<?php endif; ?>
