/* */
#ifndef KSF_CDL
#define KSF_CDL
typedef struct candledatastruct {
	char date[11];
	char symbol[7];
	double closePrice;
	double highPrice;
	double lowPrice;
	double openPrice;
	double volume;
	float movavg;
	int CDL2CROWS; /*CDL2CROWS*/
	int CDL3BLACKCROWS; /*CDL3BLACKCROWS*/
	int CDL3INSIDE; /*CDL3INSIDE*/
	int CDL3LINESTRIKE; /*CDL3LINESTRIKE*/
	int CDL3OUTSIDE; /*CDL3OUTSIDE*/
	int CDL3STARSINSOUTH; /*CDL3STARSINSOUTH*/
	int CDL3WHITESOLDIERS; /*CDL3WHITESOLDIERS*/
	int CDLABANDONEDBABY; /*CDLABANDONEDBABY*/
	int CDLADVANCEBLOCK; /*CDLADVANCEBLOCK*/
	int CDLBELTHOLD; /*CDLBELTHOLD*/
	int CDLBREAKAWAY; /*CDLBREAKAWAY*/
	int CDLCLOSINGMARUBOZU; /*CDLCLOSINGMARUBOZU*/
	int CDLCONCEALBABYSWALL; /*CDLCONCEALBABYSWALL*/
	int CDLCOUNTERATTACK; /*CDLCOUNTERATTACK*/
	int CDLDARKCLOUDCOVER; /*CDLDARKCLOUDCOVER*/
	int CDLDOJI; /*CDLDOJI*/
	int CDLDOJISTAR; /*CDLDOJISTAR*/
	int CDLDRAGONFLYDOJI; /*CDLDRAGONFLYDOJI*/
	int CDLENGULFING; /*CDLENGULFING*/
	int CDLEVENINGDOJISTAR; /*CDLEVENINGDOJISTAR*/
	int CDLEVENINGSTAR; /*CDLEVENINGSTAR*/
	int CDLGAPSIDESIDEWHITE; /*CDLGAPSIDESIDEWHITE*/
	int CDLGRAVESTONEDOJI; /*CDLGRAVESTONEDOJI*/
	int CDLHAMMER; /*CDLHAMMER*/
	int CDLHANGINGMAN; /*CDLHANGINGMAN*/
	int CDLHARAMICROSS; /*CDLHARAMICROSS*/
	int CDLHARAMI; /*CDLHARAMI*/
	int CDLHIGHWAVE; /*CDLHIGHWAVE*/
	int CDLHIKKAKEMOD; /*CDLHIKKAKEMOD*/
	int CDLHIKKAKE; /*CDLHIKKAKE*/
	int CDLHOMINGPIGEON; /*CDLHOMINGPIGEON*/
	int CDLIDENTICAL3CROWS; /*CDLIDENTICAL3CROWS*/
	int CDLINNECK; /*CDLINNECK*/
	int CDLINVERTEDHAMMER; /*CDLINVERTEDHAMMER*/
	int CDLKICKINGBYLENGTH; /*CDLKICKINGBYLENGTH*/
	int CDLKICKING; /*CDLKICKING*/
	int CDLLADDERBOTTOM; /*CDLLADDERBOTTOM*/
	int CDLLONGLEGGEDDOJI; /*CDLLONGLEGGEDDOJI*/
	int CDLLONGLINE; /*CDLLONGLINE*/
	int CDLMARUBOZU; /*CDLMARUBOZU*/
	int CDLMATCHINGLOW; /*CDLMATCHINGLOW*/
	int CDLMATHOLD; /*CDLMATHOLD*/
	int CDLMORNINGDOJISTAR; /*CDLMORNINGDOJISTAR*/
	int CDLMORNINGSTAR; /*CDLMORNINGSTAR*/
	int CDLONNECK; /*CDLONNECK*/
	int CDLPIERCING; /*CDLPIERCING*/
	int CDLRICKSHAWMAN; /*CDLRICKSHAWMAN*/
	int CDLRISEFALL3METHODS; /*CDLRISEFALL3METHODS*/
	int CDLSEPARATINGLINES; /*CDLSEPARATINGLINES*/
	int CDLSHOOTINGSTAR; /*CDLSHOOTINGSTAR*/
	int CDLSHORTLINE; /*CDLSHORTLINE*/
	int CDLSPINNINGTOP; /*CDLSPINNINGTOP*/
	int CDLSTALLEDPATTERN; /*CDLSTALLEDPATTERN*/
	int CDLSTICKSANDWICH; /*CDLSTICKSANDWICH*/
	int CDLTAKURI; /*CDLTAKURI*/
	int CDLTASUKIGAP; /*CDLTASUKIGAP*/
	int CDLTHRUSTING; /*CDLTHRUSTING*/
	int CDLTRISTAR; /*CDLTRISTAR*/
	int CDLUNIQUE3RIVER; /*CDLUNIQUE3RIVER*/
	int CDLUPSIDEGAP2CROWS; /*CDLUPSIDEGAP2CROWS*/
	int CDLXSIDEGAP3METHODS; /*CDLXSIDEGAP3METHODS*/
} TA_CDL_DAT;
#endif
TA_CDL_DAT * calcCandlesticks( /*@null@*/ FILE *pfLogfile, int startIdx, int endIdx, TA_Real *openPrice, TA_Real *highPrice, TA_Real *lowPrice, TA_Real *closePrice, /*@only@*/ TA_CDL_DAT *cdldataarray, const TA_DAT *dataarray ); 
/*func*/ char * createQueryCandlesticks( TA_CDL_DAT* cdldataarray, int icdlcount, /*@unique@*/ char *query_setfields, size_t setfields_size, /*@in@*/ /*@only@*/ char *query_setdata ); 
