-- Migration 017: SQLite version of stock_dcf_valuations
CREATE TABLE IF NOT EXISTS stock_dcf_valuations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    as_of_date TEXT NOT NULL,
    fiscal_year INTEGER NOT NULL,
    base_revenue REAL,
    revenue_cagr REAL,
    ebitda_margin REAL,
    da_pct REAL,
    capex_pct REAL,
    nwc_pct REAL,
    tax_rate REAL,
    wacc REAL,
    terminal_growth REAL,
    net_debt REAL,
    shares_outstanding INTEGER,
    assumptions_notes TEXT,
    terminal_value REAL,
    pv_fcf_1 REAL,
    pv_fcf_2 REAL,
    pv_fcf_3 REAL,
    pv_fcf_4 REAL,
    pv_fcf_5 REAL,
    sum_pv_fcf REAL,
    enterprise_value REAL,
    equity_value REAL,
    intrinsic_value_per_share REAL,
    current_price REAL,
    upside_pct REAL,
    recommendation TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(symbol, as_of_date, fiscal_year)
);
