
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/cgenerator.php finance */

#include <string.h>
#include <stdlib.h>
#define SUCCESS 1
#define FAILURE -1
class alerts
{
         char* pretty_name;
         char* pretty_plural;
         char* pageheader;
         char* pagefooter;
         private: char* observers;
                  char* classname;
                  char* querytablename;



		char* data; /*data passed in by other calls*/

/********************************************************
 *
 *	This section is the table columns
 *
 *******************************************************/
         /* int */ float idalerts;
		 /*index */
         /* varchar */ char* alertdescription;
		 /*Description */
         /* varchar */ char* alertfunctionname;
		 /*Called Function */
/********************************************************
 *
 *	End of section table columns
 *
 *******************************************************/
         void __construct( float  idalerts )
         {
         	int iPtrSize;
         	iPtrSize = strlen( "" );
         	this->pretty_name = (char*)malloc( iPtrSize + 1 );
         	memset( this->pretty_name, '0', iPtrSize + 1 );
         	strncpy( this->pretty_name, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pretty_plural = (char*)malloc( iPtrSize + 1 );
         	memset( this->pretty_plural, '0', iPtrSize + 1 );
         	strncpy( this->pretty_plural, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pageheader = (char*)malloc( iPtrSize + 1 );
         	memset( this->pageheader, '0', iPtrSize + 1 );
         	strncpy( this->pageheader, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pagefooter = (char*)malloc( iPtrSize + 1 );
         	memset( this->pagefooter, '0', iPtrSize + 1 );
         	strncpy( this->pagefooter, "", iPtrSize );

         	this->Setquerytablename( "alerts" );
         	this->Setclassname( "alerts" );
         	this->Setidalerts( idalerts );
         	/* primary key: 'idalerts' */
         	return;
         }
          bool Setdata( char* data )
         {
         	this->data = data;
	         return SUCCESS;
         }
          bool Setquerytablename( char* querytablename )
         {
         	this->querytablename = querytablename;
	         return SUCCESS;
         }
          bool Setclassname( char* classname )
         {
         	this->classname = classname;
	         return SUCCESS;
         }
         bool ObserverRegister( char* observer, int event )
         {
	         return FAILURE;
         }
         bool ObserverDeRegister( char *observer )
         {
                 /*this->observers[] = array_diff( $this->observers, array( $observer) );*/
	         return FAILURE;
         }
         bool ObserverNotify( int event, char *msg )
         {
	         return FAILURE;
         }
         bool notify( void *object )
         {
                 //Called when another object we are observing sends us a notification
	         return FAILURE;
         }
         bool Setidalerts( float  value )
         {
                 this->idalerts = value;
	          return 1;
         }
         /* int */ float  Getidalerts()
         {
                    return this->idalerts;
         }
         bool Setalertdescription( char*  value )
         {
                 this->alertdescription = value;
	          return 1;
         }
         /* varchar */ char*  Getalertdescription()
         {
                    return this->alertdescription;
         }
         bool Setalertfunctionname( char*  value )
         {
                 this->alertfunctionname = value;
	          return 1;
         }
         /* varchar */ char*  Getalertfunctionname()
         {
                    return this->alertfunctionname;
         }
}; /* class alerts */
