
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/cgenerator.php finance */

#include <string.h>
#include <stdlib.h>
#define SUCCESS 1
#define FAILURE -1
//module  evalvalue

	char* pretty_name;
	char* pretty_plural;
	char* pageheader;
	char* pagefooter;
	char* observers;
	char* classname;
	char* querytablename;



		char* data; /*data passed in by other calls*/

/********************************************************
 *
 *	This section is the table columns
 *
 *******************************************************/
         /* int */ float fidevalvalue;
		 /* */
         /* int */ float fidstockinfo;
		 /* */
         /* float */ float fownerearnings;
		 /* */
         /* int */ float fdiscountrate;
		 /* */
         /* int */ float fincomegrowth;
		 /*year over year growth percentage */
         /* int */ float fvalue;
		 /* */
         /* tinyint */ char* pcsimple;
		 /* */
         /* tinyint */ char* pcvalueowners;
		 /* */
         /* tinyint */ char* pcbenefitreinvest;
		 /* */
         /* tinyint */ char* pcexpandbypurchase;
		 /* */
         /* tinyint */ char* pcregulated;
		 /* */
         /* tinyint */ char* pcneededproduct;
		 /* */
         /* tinyint */ char* pcclosesubstitute;
		 /* */
         /* tinyint */ char* pcmimiccompetition;
		 /* */
         /* tinyint */ char* pchyperactivity;
		 /* */
         /* float */ float fkellyoptimization;
		 /* */
         /* float */ float friskprobability;
		 /* */
         /* tinyint */ char* pccosnsistanthistory;
		 /* */
         /* tinyint */ char* pccommunicatemorethangaap;
		 /* */
         /* tinyint */ char* pcpublicconfession;
		 /* */
         /* tinyint */ char* pcretainearningsmv;
		 /* */
         /* float */ float fdebtratio;
		 /* */
         /* float */ float facceptabledebt;
		 /* */
         /* tinyint */ char* pcroe;
		 /* */
         /* tinyint */ char* pclowcost;
		 /* */
         /* tinyint */ float ffrfeqreorg;
		 /* */
         /* float */ float fnetincome;
		 /* */
         /* float */ float fdepreciation;
		 /* */
         /* float */ float fdepletion;
		 /* */
         /* float */ float famortization;
		 /* */
         /* float */ float fcapitalexpenses;
		 /* */
         /* float */ float fworkingcapital;
		 /* */
         /* float */ float fmarketcap;
		 /* */
         /* float */ float fmarginsafety;
		 /* */
/********************************************************
 *
 *	End of section table columns
 *
 *******************************************************/
         void evalvalue( float  idevalvalue )
         {
         	int iPtrSize;
         	iPtrSize = strlen( "" );
         	pretty_name = (char*)malloc( iPtrSize + 1 );
         	memset( pretty_name, '0', iPtrSize + 1 );
         	strncpy( pretty_name, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	pretty_plural = (char*)malloc( iPtrSize + 1 );
         	memset( pretty_plural, '0', iPtrSize + 1 );
         	strncpy( pretty_plural, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	pageheader = (char*)malloc( iPtrSize + 1 );
         	memset( pageheader, '0', iPtrSize + 1 );
         	strncpy( pageheader, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	pagefooter = (char*)malloc( iPtrSize + 1 );
         	memset( pagefooter, '0', iPtrSize + 1 );
         	strncpy( pagefooter, "", iPtrSize );

         	Setquerytablename( "evalvalue" );
         	Setclassname( "evalvalue" );
         	Setidevalvalue( idevalvalue );
         	/* primary key: 'idevalvalue' */
         	return;
         }
          bool Setdata( char* data )
         {
         	data = data;
	         return SUCCESS;
         }
          bool Setquerytablename( char* querytablename )
         {
         	querytablename = querytablename;
	         return SUCCESS;
         }
          bool Setclassname( char* classname )
         {
         	classname = classname;
	         return SUCCESS;
         }
         bool ObserverRegister( char* observer, int event )
         {
	         return FAILURE;
         }
         bool ObserverDeRegister( char *observer )
         {
                 /*observers[] = array_diff( $this->observers, array( $observer) );*/
	         return FAILURE;
         }
         bool ObserverNotify( int event, char *msg )
         {
	         return FAILURE;
         }
         bool notify( void *object )
         {
                 //Called when another object we are observing sends us a notification
	         return FAILURE;
         }
         bool Setidevalvalue( float  value )
         {
                 fidevalvalue = value;
	          return 1;
         }
         /* int */ float  Getidevalvalue()
         {
                    return fidevalvalue;
         }
         bool Validateidevalvalue()
         {
         }
         bool Setidstockinfo( float  value )
         {
                 fidstockinfo = value;
	          return 1;
         }
         /* int */ float  Getidstockinfo()
         {
                    return fidstockinfo;
         }
         bool Validateidstockinfo()
         {
         }
         bool Setownerearnings( float  value )
         {
                 fownerearnings = value;
	          return 1;
         }
         /* float */ float  Getownerearnings()
         {
                    return fownerearnings;
         }
         bool Validateownerearnings()
         {
         }
         bool Setdiscountrate( float  value )
         {
                 fdiscountrate = value;
	          return 1;
         }
         /* int */ float  Getdiscountrate()
         {
                    return fdiscountrate;
         }
         bool Validatediscountrate()
         {
         }
         bool Setincomegrowth( float  value )
         {
                 fincomegrowth = value;
	          return 1;
         }
         /* int */ float  Getincomegrowth()
         {
                    return fincomegrowth;
         }
         bool Validateincomegrowth()
         {
         }
         bool Setvalue( float  value )
         {
                 fvalue = value;
	          return 1;
         }
         /* int */ float  Getvalue()
         {
                    return fvalue;
         }
         bool Validatevalue()
         {
         }
         bool Setsimple( char*  value )
         {
                 pcsimple = value;
	          return 1;
         }
         /* tinyint */ char*  Getsimple()
         {
                    return pcsimple;
         }
         bool Validatesimple()
         {
         }
         bool Setvalueowners( char*  value )
         {
                 pcvalueowners = value;
	          return 1;
         }
         /* tinyint */ char*  Getvalueowners()
         {
                    return pcvalueowners;
         }
         bool Validatevalueowners()
         {
         }
         bool Setbenefitreinvest( char*  value )
         {
                 pcbenefitreinvest = value;
	          return 1;
         }
         /* tinyint */ char*  Getbenefitreinvest()
         {
                    return pcbenefitreinvest;
         }
         bool Validatebenefitreinvest()
         {
         }
         bool Setexpandbypurchase( char*  value )
         {
                 pcexpandbypurchase = value;
	          return 1;
         }
         /* tinyint */ char*  Getexpandbypurchase()
         {
                    return pcexpandbypurchase;
         }
         bool Validateexpandbypurchase()
         {
         }
         bool Setregulated( char*  value )
         {
                 pcregulated = value;
	          return 1;
         }
         /* tinyint */ char*  Getregulated()
         {
                    return pcregulated;
         }
         bool Validateregulated()
         {
         }
         bool Setneededproduct( char*  value )
         {
                 pcneededproduct = value;
	          return 1;
         }
         /* tinyint */ char*  Getneededproduct()
         {
                    return pcneededproduct;
         }
         bool Validateneededproduct()
         {
         }
         bool Setclosesubstitute( char*  value )
         {
                 pcclosesubstitute = value;
	          return 1;
         }
         /* tinyint */ char*  Getclosesubstitute()
         {
                    return pcclosesubstitute;
         }
         bool Validateclosesubstitute()
         {
         }
         bool Setmimiccompetition( char*  value )
         {
                 pcmimiccompetition = value;
	          return 1;
         }
         /* tinyint */ char*  Getmimiccompetition()
         {
                    return pcmimiccompetition;
         }
         bool Validatemimiccompetition()
         {
         }
         bool Sethyperactivity( char*  value )
         {
                 pchyperactivity = value;
	          return 1;
         }
         /* tinyint */ char*  Gethyperactivity()
         {
                    return pchyperactivity;
         }
         bool Validatehyperactivity()
         {
         }
         bool Setkellyoptimization( float  value )
         {
                 fkellyoptimization = value;
	          return 1;
         }
         /* float */ float  Getkellyoptimization()
         {
                    return fkellyoptimization;
         }
         bool Validatekellyoptimization()
         {
         }
         bool Setriskprobability( float  value )
         {
                 friskprobability = value;
	          return 1;
         }
         /* float */ float  Getriskprobability()
         {
                    return friskprobability;
         }
         bool Validateriskprobability()
         {
         }
         bool Setcosnsistanthistory( char*  value )
         {
                 pccosnsistanthistory = value;
	          return 1;
         }
         /* tinyint */ char*  Getcosnsistanthistory()
         {
                    return pccosnsistanthistory;
         }
         bool Validatecosnsistanthistory()
         {
         }
         bool Setcommunicatemorethangaap( char*  value )
         {
                 pccommunicatemorethangaap = value;
	          return 1;
         }
         /* tinyint */ char*  Getcommunicatemorethangaap()
         {
                    return pccommunicatemorethangaap;
         }
         bool Validatecommunicatemorethangaap()
         {
         }
         bool Setpublicconfession( char*  value )
         {
                 pcpublicconfession = value;
	          return 1;
         }
         /* tinyint */ char*  Getpublicconfession()
         {
                    return pcpublicconfession;
         }
         bool Validatepublicconfession()
         {
         }
         bool Setretainearningsmv( char*  value )
         {
                 pcretainearningsmv = value;
	          return 1;
         }
         /* tinyint */ char*  Getretainearningsmv()
         {
                    return pcretainearningsmv;
         }
         bool Validateretainearningsmv()
         {
         }
         bool Setdebtratio( float  value )
         {
                 fdebtratio = value;
	          return 1;
         }
         /* float */ float  Getdebtratio()
         {
                    return fdebtratio;
         }
         bool Validatedebtratio()
         {
         }
         bool Setacceptabledebt( float  value )
         {
                 facceptabledebt = value;
	          return 1;
         }
         /* float */ float  Getacceptabledebt()
         {
                    return facceptabledebt;
         }
         bool Validateacceptabledebt()
         {
         }
         bool Setroe( char*  value )
         {
                 pcroe = value;
	          return 1;
         }
         /* tinyint */ char*  Getroe()
         {
                    return pcroe;
         }
         bool Validateroe()
         {
         }
         bool Setlowcost( char*  value )
         {
                 pclowcost = value;
	          return 1;
         }
         /* tinyint */ char*  Getlowcost()
         {
                    return pclowcost;
         }
         bool Validatelowcost()
         {
         }
         bool Setfrfeqreorg( float  value )
         {
                 ffrfeqreorg = value;
	          return 1;
         }
         /* tinyint */ float  Getfrfeqreorg()
         {
                    return ffrfeqreorg;
         }
         bool Validatefrfeqreorg()
         {
         }
         bool Setnetincome( float  value )
         {
                 fnetincome = value;
	          return 1;
         }
         /* float */ float  Getnetincome()
         {
                    return fnetincome;
         }
         bool Validatenetincome()
         {
         }
         bool Setdepreciation( float  value )
         {
                 fdepreciation = value;
	          return 1;
         }
         /* float */ float  Getdepreciation()
         {
                    return fdepreciation;
         }
         bool Validatedepreciation()
         {
         }
         bool Setdepletion( float  value )
         {
                 fdepletion = value;
	          return 1;
         }
         /* float */ float  Getdepletion()
         {
                    return fdepletion;
         }
         bool Validatedepletion()
         {
         }
         bool Setamortization( float  value )
         {
                 famortization = value;
	          return 1;
         }
         /* float */ float  Getamortization()
         {
                    return famortization;
         }
         bool Validateamortization()
         {
         }
         bool Setcapitalexpenses( float  value )
         {
                 fcapitalexpenses = value;
	          return 1;
         }
         /* float */ float  Getcapitalexpenses()
         {
                    return fcapitalexpenses;
         }
         bool Validatecapitalexpenses()
         {
         }
         bool Setworkingcapital( float  value )
         {
                 fworkingcapital = value;
	          return 1;
         }
         /* float */ float  Getworkingcapital()
         {
                    return fworkingcapital;
         }
         bool Validateworkingcapital()
         {
         }
         bool Setmarketcap( float  value )
         {
                 fmarketcap = value;
	          return 1;
         }
         /* float */ float  Getmarketcap()
         {
                    return fmarketcap;
         }
         bool Validatemarketcap()
         {
         }
         bool Setmarginsafety( float  value )
         {
                 fmarginsafety = value;
	          return 1;
         }
         /* float */ float  Getmarginsafety()
         {
                    return fmarginsafety;
         }
         bool Validatemarginsafety()
         {
         }
}; /* class evalvalue */
