
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/cgenerator.php finance */

#include <string.h>
#include <stdlib.h>
#define SUCCESS 1
#define FAILURE -1
class fin_statement
{
         char* pretty_name;
         char* pretty_plural;
         char* pageheader;
         char* pagefooter;
         private: char* observers;
                  char* classname;
                  char* querytablename;



		char* data; /*data passed in by other calls*/

/********************************************************
 *
 *	This section is the table columns
 *
 *******************************************************/
         /* float */ float dividendpershare1;
		 /*dividendpershare last year */
         /* float */ float dividendpershare2;
		 /*dividendpershare 2 years ago */
         /* float */ float dividendpershare3;
		 /*dividendpershare 3 years ago */
         /* float */ float earningspershare1;
		 /*earningspershare 1 year ago */
         /* float */ float earningspershare2;
		 /*earningspershare 2 years ago */
         /* float */ float earningspershare3;
		 /*earningspershare 3 years ago */
         /* int */ float idfin_statement;
		 /*Table Index */
         /* int */ float idstockinfo;
		 /*Stock */
         /* timestamp */ char* lasteval;
		 /*Last Evaluated */
         /* int */ float outstandingshares;
		 /*Outstanding Common Shares */
         /* float */ float earningpershare;
		 /*Earnings Per Share */
         /* varchar */ char* symbol;
		 /*Stock Symbol */
         /* float */ float dividendpershare;
		 /*Annual Dividend Per Share */
         /* float */ float ownerearnings;
		 /*Owner Earnings */
         /* float */ char* retainedearnings;
		 /*Retained Earnings */
         /* float */ float netincome;
		 /*Net Income */
         /* float */ float incomegrowth;
		 /*Year over year Income Growth % */
         /* float */ float revenue;
		 /*Revenue */
         /* float */ char* revenuegrowth;
		 /*Revenue Growth Compared to 1 Year ago */
         /* float */ char* revenuegrowth2;
		 /*Revenue Growth Compared to 2 Year ago */
         /* float */ char* revenuegrowth3;
		 /*Revenue Growth Compared to 3 Year ago */
         /* float */ float totalasset;
		 /*Total Assets */
         /* float */ float totalliability;
		 /*Total Liabilities */
         /* float */ float totalequity;
		 /*Total Equity */
         /* float */ float totaldebt;
		 /*Total Debt */
         /* float */ float depletion;
		 /*Depletion */
         /* float */ float amortization;
		 /*Amortization */
         /* float */ float capitalexpenses;
		 /*Capital Expenses */
         /* float */ float workingcapital;
		 /*Change in Working Capital */
         /* varchar */ char* user;
		 /*Last Evaluation User */
/********************************************************
 *
 *	End of section table columns
 *
 *******************************************************/
         void __construct( float  idfin_statement )
         {
         	int iPtrSize;
         	iPtrSize = strlen( "" );
         	this->pretty_name = (char*)malloc( iPtrSize + 1 );
         	memset( this->pretty_name, '0', iPtrSize + 1 );
         	strncpy( this->pretty_name, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pretty_plural = (char*)malloc( iPtrSize + 1 );
         	memset( this->pretty_plural, '0', iPtrSize + 1 );
         	strncpy( this->pretty_plural, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pageheader = (char*)malloc( iPtrSize + 1 );
         	memset( this->pageheader, '0', iPtrSize + 1 );
         	strncpy( this->pageheader, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pagefooter = (char*)malloc( iPtrSize + 1 );
         	memset( this->pagefooter, '0', iPtrSize + 1 );
         	strncpy( this->pagefooter, "", iPtrSize );

         	this->Setquerytablename( "fin_statement" );
         	this->Setclassname( "fin_statement" );
         	this->Setidfin_statement( idfin_statement );
         	/* primary key: 'idfin_statement' */
         	return;
         }
          bool Setdata( char* data )
         {
         	this->data = data;
	         return SUCCESS;
         }
          bool Setquerytablename( char* querytablename )
         {
         	this->querytablename = querytablename;
	         return SUCCESS;
         }
          bool Setclassname( char* classname )
         {
         	this->classname = classname;
	         return SUCCESS;
         }
         bool ObserverRegister( char* observer, int event )
         {
	         return FAILURE;
         }
         bool ObserverDeRegister( char *observer )
         {
                 /*this->observers[] = array_diff( $this->observers, array( $observer) );*/
	         return FAILURE;
         }
         bool ObserverNotify( int event, char *msg )
         {
	         return FAILURE;
         }
         bool notify( void *object )
         {
                 //Called when another object we are observing sends us a notification
	         return FAILURE;
         }
         bool Setdividendpershare1( float  value )
         {
                 this->dividendpershare1 = value;
	          return 1;
         }
         /* float */ float  Getdividendpershare1()
         {
                    return this->dividendpershare1;
         }
         bool Setdividendpershare2( float  value )
         {
                 this->dividendpershare2 = value;
	          return 1;
         }
         /* float */ float  Getdividendpershare2()
         {
                    return this->dividendpershare2;
         }
         bool Setdividendpershare3( float  value )
         {
                 this->dividendpershare3 = value;
	          return 1;
         }
         /* float */ float  Getdividendpershare3()
         {
                    return this->dividendpershare3;
         }
         bool Setearningspershare1( float  value )
         {
                 this->earningspershare1 = value;
	          return 1;
         }
         /* float */ float  Getearningspershare1()
         {
                    return this->earningspershare1;
         }
         bool Setearningspershare2( float  value )
         {
                 this->earningspershare2 = value;
	          return 1;
         }
         /* float */ float  Getearningspershare2()
         {
                    return this->earningspershare2;
         }
         bool Setearningspershare3( float  value )
         {
                 this->earningspershare3 = value;
	          return 1;
         }
         /* float */ float  Getearningspershare3()
         {
                    return this->earningspershare3;
         }
         bool Setidfin_statement( float  value )
         {
                 this->idfin_statement = value;
	          return 1;
         }
         /* int */ float  Getidfin_statement()
         {
                    return this->idfin_statement;
         }
         bool Setidstockinfo( float  value )
         {
                 this->idstockinfo = value;
	          return 1;
         }
         /* int */ float  Getidstockinfo()
         {
                    return this->idstockinfo;
         }
         bool Setlasteval( char*  value )
         {
                 this->lasteval = value;
	          return 1;
         }
         /* timestamp */ char*  Getlasteval()
         {
                    return this->lasteval;
         }
         bool Setoutstandingshares( float  value )
         {
                 this->outstandingshares = value;
	          return 1;
         }
         /* int */ float  Getoutstandingshares()
         {
                    return this->outstandingshares;
         }
         bool Setearningpershare( float  value )
         {
                 this->earningpershare = value;
	          return 1;
         }
         /* float */ float  Getearningpershare()
         {
                    return this->earningpershare;
         }
         bool Setsymbol( char*  value )
         {
                 this->symbol = value;
	          return 1;
         }
         /* varchar */ char*  Getsymbol()
         {
                    return this->symbol;
         }
         bool Setdividendpershare( float  value )
         {
                 this->dividendpershare = value;
	          return 1;
         }
         /* float */ float  Getdividendpershare()
         {
                    return this->dividendpershare;
         }
         bool Setownerearnings( float  value )
         {
                 this->ownerearnings = value;
	          return 1;
         }
         /* float */ float  Getownerearnings()
         {
                    return this->ownerearnings;
         }
         bool Setretainedearnings( char*  value )
         {
                 this->retainedearnings = value;
	          return 1;
         }
         /* float */ char*  Getretainedearnings()
         {
                    return this->retainedearnings;
         }
         bool Setnetincome( float  value )
         {
                 this->netincome = value;
	          return 1;
         }
         /* float */ float  Getnetincome()
         {
                    return this->netincome;
         }
         bool Setincomegrowth( float  value )
         {
                 this->incomegrowth = value;
	          return 1;
         }
         /* float */ float  Getincomegrowth()
         {
                    return this->incomegrowth;
         }
         bool Setrevenue( float  value )
         {
                 this->revenue = value;
	          return 1;
         }
         /* float */ float  Getrevenue()
         {
                    return this->revenue;
         }
         bool Setrevenuegrowth( char*  value )
         {
                 this->revenuegrowth = value;
	          return 1;
         }
         /* float */ char*  Getrevenuegrowth()
         {
                    return this->revenuegrowth;
         }
         bool Setrevenuegrowth2( char*  value )
         {
                 this->revenuegrowth2 = value;
	          return 1;
         }
         /* float */ char*  Getrevenuegrowth2()
         {
                    return this->revenuegrowth2;
         }
         bool Setrevenuegrowth3( char*  value )
         {
                 this->revenuegrowth3 = value;
	          return 1;
         }
         /* float */ char*  Getrevenuegrowth3()
         {
                    return this->revenuegrowth3;
         }
         bool Settotalasset( float  value )
         {
                 this->totalasset = value;
	          return 1;
         }
         /* float */ float  Gettotalasset()
         {
                    return this->totalasset;
         }
         bool Settotalliability( float  value )
         {
                 this->totalliability = value;
	          return 1;
         }
         /* float */ float  Gettotalliability()
         {
                    return this->totalliability;
         }
         bool Settotalequity( float  value )
         {
                 this->totalequity = value;
	          return 1;
         }
         /* float */ float  Gettotalequity()
         {
                    return this->totalequity;
         }
         bool Settotaldebt( float  value )
         {
                 this->totaldebt = value;
	          return 1;
         }
         /* float */ float  Gettotaldebt()
         {
                    return this->totaldebt;
         }
         bool Setdepletion( float  value )
         {
                 this->depletion = value;
	          return 1;
         }
         /* float */ float  Getdepletion()
         {
                    return this->depletion;
         }
         bool Setamortization( float  value )
         {
                 this->amortization = value;
	          return 1;
         }
         /* float */ float  Getamortization()
         {
                    return this->amortization;
         }
         bool Setcapitalexpenses( float  value )
         {
                 this->capitalexpenses = value;
	          return 1;
         }
         /* float */ float  Getcapitalexpenses()
         {
                    return this->capitalexpenses;
         }
         bool Setworkingcapital( float  value )
         {
                 this->workingcapital = value;
	          return 1;
         }
         /* float */ float  Getworkingcapital()
         {
                    return this->workingcapital;
         }
         bool Setuser( char*  value )
         {
                 this->user = value;
	          return 1;
         }
         /* varchar */ char*  Getuser()
         {
                    return this->user;
         }
}; /* class fin_statement */
