
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/cgenerator.php finance */

#include <string.h>
#include <stdlib.h>
#define SUCCESS 1
#define FAILURE -1
class investorplace
{
         char* pretty_name;
         char* pretty_plural;
         char* pageheader;
         char* pagefooter;
         private: char* observers;
                  char* classname;
                  char* querytablename;



		char* data; /*data passed in by other calls*/

/********************************************************
 *
 *	This section is the table columns
 *
 *******************************************************/
         /* int */ float idinvestorplace;
		 /*Index */
         /* tinyint */ char* seventyfivepercent;
		 /*Does the company depend on 75 percent or greater of domestic sales */
         /* tinyint */ char* earningsgrowth;
		 /*Are earnings growing */
         /* tinyint */ char* earningsaccel;
		 /*Are earnings growth accelerating */
         /* float */ float pe;
		 /*Price to Earnings ratio */
         /* int */ float tradingvolume;
		 /*Trading Volume */
         /* int */ float institutioninterest;
		 /*Percentage of shares owned by institutions */
         /* tinyint */ char* orderimbalance;
		 /*Balance of buy and sell orders */
         /* tinyint */ char* shortinterest;
		 /*Is there a lot of short options sold */
         /* float */ float volatility;
		 /*The volatility of the share */
         /* int */ char* createduser;
		 /*Created By User */
         /* datetime */ char* createddate;
		 /*Created Date */
         /* int */ char* updateduser;
		 /*Updated by User */
         /* timestamp */ char* updateddate;
		 /*Updated Date */
         /* int */ float idstockinfo;
		 /*Company */
         /* float */ float dividendearningratio;
		 /*Dividends per share divided by earnings per share */
         /* tinyint */ char* newproductline;
		 /*Innovations - new products that are needed */
         /* tinyint */ char* restructuring;
		 /*Is the company cutting costs by restructuring */
         /* tinyint */ char* reengineering;
		 /*Is the company reengineering themselves */
         /* tinyint */ char* sharebuyback;
		 /*Share Buy Back */
         /* tinyint */ char* headcountcuts;
		 /*Announced staff reductions */
         /* tinyint */ char* spinoffs;
		 /*Shedding lines of business as spin-offs */
         /* tinyint */ char* reducedrd;
		 /*Reducing research and development */
         /* tinyint */ char* extracash;
		 /*Does the company have cash on hand */
         /* tinyint */ char* shareholderprofitgoal;
		 /*Management focused on shareholder profit */
         /* tinyint */ char* dividendincreases;
		 /*Track record of dividend increases */
         /* int */ float score;
		 /*Score of this filter */
/********************************************************
 *
 *	End of section table columns
 *
 *******************************************************/
         void __construct( float  idinvestorplace )
         {
         	int iPtrSize;
         	iPtrSize = strlen( "" );
         	this->pretty_name = (char*)malloc( iPtrSize + 1 );
         	memset( this->pretty_name, '0', iPtrSize + 1 );
         	strncpy( this->pretty_name, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pretty_plural = (char*)malloc( iPtrSize + 1 );
         	memset( this->pretty_plural, '0', iPtrSize + 1 );
         	strncpy( this->pretty_plural, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pageheader = (char*)malloc( iPtrSize + 1 );
         	memset( this->pageheader, '0', iPtrSize + 1 );
         	strncpy( this->pageheader, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pagefooter = (char*)malloc( iPtrSize + 1 );
         	memset( this->pagefooter, '0', iPtrSize + 1 );
         	strncpy( this->pagefooter, "", iPtrSize );

         	this->Setquerytablename( "investorplace" );
         	this->Setclassname( "investorplace" );
         	this->Setidinvestorplace( idinvestorplace );
         	/* primary key: 'idinvestorplace' */
         	return;
         }
          bool Setdata( char* data )
         {
         	this->data = data;
	         return SUCCESS;
         }
          bool Setquerytablename( char* querytablename )
         {
         	this->querytablename = querytablename;
	         return SUCCESS;
         }
          bool Setclassname( char* classname )
         {
         	this->classname = classname;
	         return SUCCESS;
         }
         bool ObserverRegister( char* observer, int event )
         {
	         return FAILURE;
         }
         bool ObserverDeRegister( char *observer )
         {
                 /*this->observers[] = array_diff( $this->observers, array( $observer) );*/
	         return FAILURE;
         }
         bool ObserverNotify( int event, char *msg )
         {
	         return FAILURE;
         }
         bool notify( void *object )
         {
                 //Called when another object we are observing sends us a notification
	         return FAILURE;
         }
         bool Setidinvestorplace( float  value )
         {
                 this->idinvestorplace = value;
	          return 1;
         }
         /* int */ float  Getidinvestorplace()
         {
                    return this->idinvestorplace;
         }
         bool Setseventyfivepercent( char*  value )
         {
                 this->seventyfivepercent = value;
	          return 1;
         }
         /* tinyint */ char*  Getseventyfivepercent()
         {
                    return this->seventyfivepercent;
         }
         bool Setearningsgrowth( char*  value )
         {
                 this->earningsgrowth = value;
	          return 1;
         }
         /* tinyint */ char*  Getearningsgrowth()
         {
                    return this->earningsgrowth;
         }
         bool Setearningsaccel( char*  value )
         {
                 this->earningsaccel = value;
	          return 1;
         }
         /* tinyint */ char*  Getearningsaccel()
         {
                    return this->earningsaccel;
         }
         bool Setpe( float  value )
         {
                 this->pe = value;
	          return 1;
         }
         /* float */ float  Getpe()
         {
                    return this->pe;
         }
         bool Settradingvolume( float  value )
         {
                 this->tradingvolume = value;
	          return 1;
         }
         /* int */ float  Gettradingvolume()
         {
                    return this->tradingvolume;
         }
         bool Setinstitutioninterest( float  value )
         {
                 this->institutioninterest = value;
	          return 1;
         }
         /* int */ float  Getinstitutioninterest()
         {
                    return this->institutioninterest;
         }
         bool Setorderimbalance( char*  value )
         {
                 this->orderimbalance = value;
	          return 1;
         }
         /* tinyint */ char*  Getorderimbalance()
         {
                    return this->orderimbalance;
         }
         bool Setshortinterest( char*  value )
         {
                 this->shortinterest = value;
	          return 1;
         }
         /* tinyint */ char*  Getshortinterest()
         {
                    return this->shortinterest;
         }
         bool Setvolatility( float  value )
         {
                 this->volatility = value;
	          return 1;
         }
         /* float */ float  Getvolatility()
         {
                    return this->volatility;
         }
         bool Setcreateduser( char*  value )
         {
                 this->createduser = value;
	          return 1;
         }
         /* int */ char*  Getcreateduser()
         {
                    return this->createduser;
         }
         bool Setcreateddate( char*  value )
         {
                 this->createddate = value;
	          return 1;
         }
         /* datetime */ char*  Getcreateddate()
         {
                    return this->createddate;
         }
         bool Setupdateduser( char*  value )
         {
                 this->updateduser = value;
	          return 1;
         }
         /* int */ char*  Getupdateduser()
         {
                    return this->updateduser;
         }
         bool Setupdateddate( char*  value )
         {
                 this->updateddate = value;
	          return 1;
         }
         /* timestamp */ char*  Getupdateddate()
         {
                    return this->updateddate;
         }
         bool Setidstockinfo( float  value )
         {
                 this->idstockinfo = value;
	          return 1;
         }
         /* int */ float  Getidstockinfo()
         {
                    return this->idstockinfo;
         }
         bool Setdividendearningratio( float  value )
         {
                 this->dividendearningratio = value;
	          return 1;
         }
         /* float */ float  Getdividendearningratio()
         {
                    return this->dividendearningratio;
         }
         bool Setnewproductline( char*  value )
         {
                 this->newproductline = value;
	          return 1;
         }
         /* tinyint */ char*  Getnewproductline()
         {
                    return this->newproductline;
         }
         bool Setrestructuring( char*  value )
         {
                 this->restructuring = value;
	          return 1;
         }
         /* tinyint */ char*  Getrestructuring()
         {
                    return this->restructuring;
         }
         bool Setreengineering( char*  value )
         {
                 this->reengineering = value;
	          return 1;
         }
         /* tinyint */ char*  Getreengineering()
         {
                    return this->reengineering;
         }
         bool Setsharebuyback( char*  value )
         {
                 this->sharebuyback = value;
	          return 1;
         }
         /* tinyint */ char*  Getsharebuyback()
         {
                    return this->sharebuyback;
         }
         bool Setheadcountcuts( char*  value )
         {
                 this->headcountcuts = value;
	          return 1;
         }
         /* tinyint */ char*  Getheadcountcuts()
         {
                    return this->headcountcuts;
         }
         bool Setspinoffs( char*  value )
         {
                 this->spinoffs = value;
	          return 1;
         }
         /* tinyint */ char*  Getspinoffs()
         {
                    return this->spinoffs;
         }
         bool Setreducedrd( char*  value )
         {
                 this->reducedrd = value;
	          return 1;
         }
         /* tinyint */ char*  Getreducedrd()
         {
                    return this->reducedrd;
         }
         bool Setextracash( char*  value )
         {
                 this->extracash = value;
	          return 1;
         }
         /* tinyint */ char*  Getextracash()
         {
                    return this->extracash;
         }
         bool Setshareholderprofitgoal( char*  value )
         {
                 this->shareholderprofitgoal = value;
	          return 1;
         }
         /* tinyint */ char*  Getshareholderprofitgoal()
         {
                    return this->shareholderprofitgoal;
         }
         bool Setdividendincreases( char*  value )
         {
                 this->dividendincreases = value;
	          return 1;
         }
         /* tinyint */ char*  Getdividendincreases()
         {
                    return this->dividendincreases;
         }
         bool Setscore( float  value )
         {
                 this->score = value;
	          return 1;
         }
         /* int */ float  Getscore()
         {
                    return this->score;
         }
}; /* class investorplace */
