
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/cgenerator.php finance */

#include <string.h>
#include <stdlib.h>
#define SUCCESS 1
#define FAILURE -1
//module  iplace_calc

	char* pretty_name;
	char* pretty_plural;
	char* pageheader;
	char* pagefooter;
	char* observers;
	char* classname;
	char* querytablename;



		char* data; /*data passed in by other calls*/

/********************************************************
 *
 *	This section is the table columns
 *
 *******************************************************/
         /* int */ float fiplace_calc;
		 /*Index */
         /* tinyint */ char* pcearningsgrowth;
		 /*Are earnings growing */
         /* tinyint */ char* pcearningsaccel;
		 /*Are earnings growth accelerating */
         /* float */ float fpe;
		 /*Price to Earnings ratio */
         /* int */ float ftradingvolume;
		 /*Trading Volume */
         /* int */ float finstitutioninterest;
		 /*Percentage of shares owned by institutions */
         /* tinyint */ char* pcorderimbalance;
		 /*Balance of buy and sell orders */
         /* tinyint */ char* pcshortinterest;
		 /*Is there a lot of short options sold */
         /* float */ float fvolatility;
		 /*The volatility of the share */
         /* int */ char* pccreateduser;
		 /*Created By User */
         /* datetime */ char* pccreateddate;
		 /*Created Date */
         /* int */ char* pcupdateduser;
		 /*Updated by User */
         /* timestamp */ char* pcupdateddate;
		 /*Updated Date */
         /* int */ float fidstockinfo;
		 /*Company */
         /* float */ float fdividendearningratio;
		 /*Dividends per share divided by earnings per share */
         /* tinyint */ char* pcextracash;
		 /*Does the company have cash on hand */
         /* tinyint */ char* pcshareholderprofitgoal;
		 /*Management focused on shareholder profit */
         /* tinyint */ char* pcdividendincreases;
		 /*Track record of dividend increases */
         /* int */ float fscore;
		 /*Score of this filter */
/********************************************************
 *
 *	End of section table columns
 *
 *******************************************************/
         void iplace_calc( float  iplace_calc )
         {
         	int iPtrSize;
         	iPtrSize = strlen( "" );
         	pretty_name = (char*)malloc( iPtrSize + 1 );
         	memset( pretty_name, '0', iPtrSize + 1 );
         	strncpy( pretty_name, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	pretty_plural = (char*)malloc( iPtrSize + 1 );
         	memset( pretty_plural, '0', iPtrSize + 1 );
         	strncpy( pretty_plural, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	pageheader = (char*)malloc( iPtrSize + 1 );
         	memset( pageheader, '0', iPtrSize + 1 );
         	strncpy( pageheader, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	pagefooter = (char*)malloc( iPtrSize + 1 );
         	memset( pagefooter, '0', iPtrSize + 1 );
         	strncpy( pagefooter, "", iPtrSize );

         	Setquerytablename( "iplace_calc" );
         	Setclassname( "iplace_calc" );
         	Setiplace_calc( iplace_calc );
         	/* primary key: 'iplace_calc' */
         	return;
         }
          bool Setdata( char* data )
         {
         	data = data;
	         return SUCCESS;
         }
          bool Setquerytablename( char* querytablename )
         {
         	querytablename = querytablename;
	         return SUCCESS;
         }
          bool Setclassname( char* classname )
         {
         	classname = classname;
	         return SUCCESS;
         }
         bool ObserverRegister( char* observer, int event )
         {
	         return FAILURE;
         }
         bool ObserverDeRegister( char *observer )
         {
                 /*observers[] = array_diff( $this->observers, array( $observer) );*/
	         return FAILURE;
         }
         bool ObserverNotify( int event, char *msg )
         {
	         return FAILURE;
         }
         bool notify( void *object )
         {
                 //Called when another object we are observing sends us a notification
	         return FAILURE;
         }
         bool Setiplace_calc( float  value )
         {
                 fiplace_calc = value;
	          return 1;
         }
         /* int */ float  Getiplace_calc()
         {
                    return fiplace_calc;
         }
         bool Validateiplace_calc()
         {
         }
         bool Setearningsgrowth( char*  value )
         {
                 pcearningsgrowth = value;
	          return 1;
         }
         /* tinyint */ char*  Getearningsgrowth()
         {
                    return pcearningsgrowth;
         }
         bool Validateearningsgrowth()
         {
         }
         bool Setearningsaccel( char*  value )
         {
                 pcearningsaccel = value;
	          return 1;
         }
         /* tinyint */ char*  Getearningsaccel()
         {
                    return pcearningsaccel;
         }
         bool Validateearningsaccel()
         {
         }
         bool Setpe( float  value )
         {
                 fpe = value;
	          return 1;
         }
         /* float */ float  Getpe()
         {
                    return fpe;
         }
         bool Validatepe()
         {
         }
         bool Settradingvolume( float  value )
         {
                 ftradingvolume = value;
	          return 1;
         }
         /* int */ float  Gettradingvolume()
         {
                    return ftradingvolume;
         }
         bool Validatetradingvolume()
         {
         }
         bool Setinstitutioninterest( float  value )
         {
                 finstitutioninterest = value;
	          return 1;
         }
         /* int */ float  Getinstitutioninterest()
         {
                    return finstitutioninterest;
         }
         bool Validateinstitutioninterest()
         {
         }
         bool Setorderimbalance( char*  value )
         {
                 pcorderimbalance = value;
	          return 1;
         }
         /* tinyint */ char*  Getorderimbalance()
         {
                    return pcorderimbalance;
         }
         bool Validateorderimbalance()
         {
         }
         bool Setshortinterest( char*  value )
         {
                 pcshortinterest = value;
	          return 1;
         }
         /* tinyint */ char*  Getshortinterest()
         {
                    return pcshortinterest;
         }
         bool Validateshortinterest()
         {
         }
         bool Setvolatility( float  value )
         {
                 fvolatility = value;
	          return 1;
         }
         /* float */ float  Getvolatility()
         {
                    return fvolatility;
         }
         bool Validatevolatility()
         {
         }
         bool Setcreateduser( char*  value )
         {
                 pccreateduser = value;
	          return 1;
         }
         /* int */ char*  Getcreateduser()
         {
                    return pccreateduser;
         }
         bool Validatecreateduser()
         {
         }
         bool Setcreateddate( char*  value )
         {
                 pccreateddate = value;
	          return 1;
         }
         /* datetime */ char*  Getcreateddate()
         {
                    return pccreateddate;
         }
         bool Validatecreateddate()
         {
         }
         bool Setupdateduser( char*  value )
         {
                 pcupdateduser = value;
	          return 1;
         }
         /* int */ char*  Getupdateduser()
         {
                    return pcupdateduser;
         }
         bool Validateupdateduser()
         {
         }
         bool Setupdateddate( char*  value )
         {
                 pcupdateddate = value;
	          return 1;
         }
         /* timestamp */ char*  Getupdateddate()
         {
                    return pcupdateddate;
         }
         bool Validateupdateddate()
         {
         }
         bool Setidstockinfo( float  value )
         {
                 fidstockinfo = value;
	          return 1;
         }
         /* int */ float  Getidstockinfo()
         {
                    return fidstockinfo;
         }
         bool Validateidstockinfo()
         {
         }
         bool Setdividendearningratio( float  value )
         {
                 fdividendearningratio = value;
	          return 1;
         }
         /* float */ float  Getdividendearningratio()
         {
                    return fdividendearningratio;
         }
         bool Validatedividendearningratio()
         {
         }
         bool Setextracash( char*  value )
         {
                 pcextracash = value;
	          return 1;
         }
         /* tinyint */ char*  Getextracash()
         {
                    return pcextracash;
         }
         bool Validateextracash()
         {
         }
         bool Setshareholderprofitgoal( char*  value )
         {
                 pcshareholderprofitgoal = value;
	          return 1;
         }
         /* tinyint */ char*  Getshareholderprofitgoal()
         {
                    return pcshareholderprofitgoal;
         }
         bool Validateshareholderprofitgoal()
         {
         }
         bool Setdividendincreases( char*  value )
         {
                 pcdividendincreases = value;
	          return 1;
         }
         /* tinyint */ char*  Getdividendincreases()
         {
                    return pcdividendincreases;
         }
         bool Validatedividendincreases()
         {
         }
         bool Setscore( float  value )
         {
                 fscore = value;
	          return 1;
         }
         /* int */ float  Getscore()
         {
                    return fscore;
         }
         bool Validatescore()
         {
         }
}; /* class iplace_calc */
