
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/cgenerator.php finance */

#include <string.h>
#include <stdlib.h>
#define SUCCESS 1
#define FAILURE -1
//module  scriptlog

	char* pretty_name;
	char* pretty_plural;
	char* pageheader;
	char* pagefooter;
	char* observers;
	char* classname;
	char* querytablename;



		char* data; /*data passed in by other calls*/

/********************************************************
 *
 *	This section is the table columns
 *
 *******************************************************/
         /* int */ float fidscriptlog;
		 /* */
         /* timestamp */ char* pcdate;
		 /* */
         /* varchar */ char* pcscriptname;
		 /* */
         /* varchar */ char* pcscriptstep;
		 /* */
/********************************************************
 *
 *	End of section table columns
 *
 *******************************************************/
         void scriptlog( float  idscriptlog )
         {
         	int iPtrSize;
         	iPtrSize = strlen( "" );
         	pretty_name = (char*)malloc( iPtrSize + 1 );
         	memset( pretty_name, '0', iPtrSize + 1 );
         	strncpy( pretty_name, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	pretty_plural = (char*)malloc( iPtrSize + 1 );
         	memset( pretty_plural, '0', iPtrSize + 1 );
         	strncpy( pretty_plural, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	pageheader = (char*)malloc( iPtrSize + 1 );
         	memset( pageheader, '0', iPtrSize + 1 );
         	strncpy( pageheader, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	pagefooter = (char*)malloc( iPtrSize + 1 );
         	memset( pagefooter, '0', iPtrSize + 1 );
         	strncpy( pagefooter, "", iPtrSize );

         	Setquerytablename( "scriptlog" );
         	Setclassname( "scriptlog" );
         	Setidscriptlog( idscriptlog );
         	/* primary key: 'idscriptlog' */
         	return;
         }
          bool Setdata( char* data )
         {
         	data = data;
	         return SUCCESS;
         }
          bool Setquerytablename( char* querytablename )
         {
         	querytablename = querytablename;
	         return SUCCESS;
         }
          bool Setclassname( char* classname )
         {
         	classname = classname;
	         return SUCCESS;
         }
         bool ObserverRegister( char* observer, int event )
         {
	         return FAILURE;
         }
         bool ObserverDeRegister( char *observer )
         {
                 /*observers[] = array_diff( $this->observers, array( $observer) );*/
	         return FAILURE;
         }
         bool ObserverNotify( int event, char *msg )
         {
	         return FAILURE;
         }
         bool notify( void *object )
         {
                 //Called when another object we are observing sends us a notification
	         return FAILURE;
         }
         bool Setidscriptlog( float  value )
         {
                 fidscriptlog = value;
	          return 1;
         }
         /* int */ float  Getidscriptlog()
         {
                    return fidscriptlog;
         }
         bool Validateidscriptlog()
         {
         }
         bool Setdate( char*  value )
         {
                 pcdate = value;
	          return 1;
         }
         /* timestamp */ char*  Getdate()
         {
                    return pcdate;
         }
         bool Validatedate()
         {
         }
         bool Setscriptname( char*  value )
         {
                 pcscriptname = value;
	          return 1;
         }
         /* varchar */ char*  Getscriptname()
         {
                    return pcscriptname;
         }
         bool Validatescriptname()
         {
         }
         bool Setscriptstep( char*  value )
         {
                 pcscriptstep = value;
	          return 1;
         }
         /* varchar */ char*  Getscriptstep()
         {
                    return pcscriptstep;
         }
         bool Validatescriptstep()
         {
         }
}; /* class scriptlog */
