
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/cgenerator.php finance */

#include <string.h>
#include <stdlib.h>
#define SUCCESS 1
#define FAILURE -1
class stockexchange
{
         char* pretty_name;
         char* pretty_plural;
         char* pageheader;
         char* pagefooter;
         private: char* observers;
                  char* classname;
                  char* querytablename;



		char* data; /*data passed in by other calls*/

/********************************************************
 *
 *	This section is the table columns
 *
 *******************************************************/
         /* integer */ float idstockexchange;
		 /*Stock Exchange index */
         /* varchar */ char* exchange;
		 /*Exchange Name */
         /* varchar */ char* YahooSymbol;
		 /*Yahoo Finance Symbol */
         /* varchar */ char* GlobeInvestorSymbol;
		 /*Globe Investor Symbol */
/********************************************************
 *
 *	End of section table columns
 *
 *******************************************************/
         void __construct( float  idstockexchange )
         {
         	int iPtrSize;
         	iPtrSize = strlen( "" );
         	this->pretty_name = (char*)malloc( iPtrSize + 1 );
         	memset( this->pretty_name, '0', iPtrSize + 1 );
         	strncpy( this->pretty_name, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pretty_plural = (char*)malloc( iPtrSize + 1 );
         	memset( this->pretty_plural, '0', iPtrSize + 1 );
         	strncpy( this->pretty_plural, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pageheader = (char*)malloc( iPtrSize + 1 );
         	memset( this->pageheader, '0', iPtrSize + 1 );
         	strncpy( this->pageheader, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pagefooter = (char*)malloc( iPtrSize + 1 );
         	memset( this->pagefooter, '0', iPtrSize + 1 );
         	strncpy( this->pagefooter, "", iPtrSize );

         	this->Setquerytablename( "stockexchange" );
         	this->Setclassname( "stockexchange" );
         	this->Setidstockexchange( idstockexchange );
         	/* primary key: 'idstockexchange' */
         	return;
         }
          bool Setdata( char* data )
         {
         	this->data = data;
	         return SUCCESS;
         }
          bool Setquerytablename( char* querytablename )
         {
         	this->querytablename = querytablename;
	         return SUCCESS;
         }
          bool Setclassname( char* classname )
         {
         	this->classname = classname;
	         return SUCCESS;
         }
         bool ObserverRegister( char* observer, int event )
         {
	         return FAILURE;
         }
         bool ObserverDeRegister( char *observer )
         {
                 /*this->observers[] = array_diff( $this->observers, array( $observer) );*/
	         return FAILURE;
         }
         bool ObserverNotify( int event, char *msg )
         {
	         return FAILURE;
         }
         bool notify( void *object )
         {
                 //Called when another object we are observing sends us a notification
	         return FAILURE;
         }
         bool Setidstockexchange( float  value )
         {
                 this->idstockexchange = value;
	          return 1;
         }
         /* integer */ float  Getidstockexchange()
         {
                    return this->idstockexchange;
         }
         bool Setexchange( char*  value )
         {
                 this->exchange = value;
	          return 1;
         }
         /* varchar */ char*  Getexchange()
         {
                    return this->exchange;
         }
         bool SetYahooSymbol( char*  value )
         {
                 this->YahooSymbol = value;
	          return 1;
         }
         /* varchar */ char*  GetYahooSymbol()
         {
                    return this->YahooSymbol;
         }
         bool SetGlobeInvestorSymbol( char*  value )
         {
                 this->GlobeInvestorSymbol = value;
	          return 1;
         }
         /* varchar */ char*  GetGlobeInvestorSymbol()
         {
                    return this->GlobeInvestorSymbol;
         }
}; /* class stockexchange */
