
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/cgenerator.php finance */

#include <string.h>
#include <stdlib.h>
#define SUCCESS 1
#define FAILURE -1
class technicalanalysis
{
         char* pretty_name;
         char* pretty_plural;
         char* pageheader;
         char* pagefooter;
         private: char* observers;
                  char* classname;
                  char* querytablename;



		char* data; /*data passed in by other calls*/

/********************************************************
 *
 *	This section is the table columns
 *
 *******************************************************/
         /* int */ float idtechnicalanalysis;
		 /*Index */
         /* datetime */ char* createddate;
		 /*Record Created Date */
         /* int */ float createduser;
		 /*Record Created by User */
         /* timestamp */ char* updateddate;
		 /*Record updated date */
         /* int */ float updateduser;
		 /*Record Updated by user */
         /* varchar */ char* symbol;
		 /*Stock Symbol */
         /* date */ char* date;
		 /*Date in stockprices */
         /* float */ float day_close;
		 /*The daily closing price */
         /* float */ float typicalprice;
		 /*The Typical Price is the high plus low plus close divided by 3 */
         /* float */ float movingaverage50;
		 /*50 Day Moving Average */
         /* float */ float movingaverage200;
		 /*200 Day Moving Average */
         /* varchar */ char* candlestick;
		 /*Candlestick Identified for this date */
         /* float */ float expmovingaverage9;
		 /*9 Day exponential Moving Average */
         /* float */ float expmovingaverage12;
		 /*12 Day exponential Moving Average */
         /* float */ float expmovingaverage26;
		 /*26 Day exponential Moving Average */
         /* varchar */ char* macd;
		 /*Moving Average ConvergenceDivergence describes the rate of changes in EMAs */
         /* float */ float momentumoscillator;
		 /*The Longer EMA subtracted from the shorter EMA usually 12 and 26 */
         /* float */ float mamomentum;
		 /*MACD momentum rising positive is bullish increasing */
         /* int */ float macrossover;
		 /*MA crossover True or False */
         /* int */ float macenterlinecrossover;
		 /*Is this a centerline crossover of the MA */
         /* float */ float priceoscillator;
		 /*Shows the percentage difference between 2 MAs 12 minus 26 div 26 */
         /* float */ float macd_histogram;
		 /*Difference between MACD and trigger line (ma9) */
         /* float */ float linearregression;
		 /*Linear Regression */
         /* float */ float linearregressionangle;
		 /*Angle of Linear Regression */
         /* float */ float linearregressionslope;
		 /*Slope of Linear Regression */
         /* float */ float linearregressionintercept;
		 /*Intercept of Linear Regression */
         /* float */ float stochastic;
		 /*Stochastic Indicator */
         /* float */ float relativestrenghtindex;
		 /*Relative Strength Index */
         /* float */ float rsioscillator;
		 /*Relative Strength Oscillator is a leading indicator */
         /* float */ float commoditychannelindex;
		 /*Commodity Channel Index */
         /* float */ float pricechangepercent;
		 /*The percentage change of the close price compared to yesterdays close price */
         /* int */ float volume12;
		 /*Average Volume for the last 12 days */
         /* int */ float volume26;
		 /*Average volume for the last 26 days */
         /* int */ float volume90;
		 /*Average volume for the last 90 days */
         /* float */ float support12;
		 /*Support level last 12 days */
         /* float */ float support26;
		 /*Support level last 26 days */
         /* float */ float resistance12;
		 /*Resistance level last 12 days */
         /* float */ float resistance26;
		 /*resistance level last 26 days */
         /* float */ float bollingerbandmiddle;
		 /*The middle bollinger band */
         /* float */ float bollingerbandupper;
		 /*The upper bollinger band */
         /* float */ float bollingerbandlower;
		 /*The lower bollinger band */
         /* float */ float bollingerpercentb;
		 /*The bollinger percent b indicator */
         /* float */ float bollingerbandwidth;
		 /*The bollinger bandwidth addresses the spread of the values */
         /* float */ float coefficientofvariation;
		 /*The coefficient of variation is 1/4 of the bandwidth */
         /* float */ float movingaverage260;
		 /*Moving Average for 260 days (1 trading year) */
         /* float */ float standarddeviation260;
		 /*Standard Deviation 260 One trading year */
         /* float */ float annualreturn;
		 /*The price appreciation in the last year */
         /* float */ float annualrisk;
		 /*The annual risk standard dev divided by annual return */
         /* float */ float truerange;
		 /* MAX( High0-Low0, High0-Close1, Close1 - Low0 ) */
         /* float */ float expmovingaverage90;
		 /*90 day price EMA  */
         /* varchar */ char* voltrendind90;
		 /*90 day Volume trend indicator */
         /* varchar */ char* voltrendind26;
		 /*26 day Volume Trend indicator */
         /* float */ float volume260;
		 /*One year's volume average */
         /* varchar */ char* voltrendind260;
		 /*Year's volume trend indicator */
/********************************************************
 *
 *	End of section table columns
 *
 *******************************************************/
         void __construct( float  idtechnicalanalysis )
         {
         	int iPtrSize;
         	iPtrSize = strlen( "" );
         	this->pretty_name = (char*)malloc( iPtrSize + 1 );
         	memset( this->pretty_name, '0', iPtrSize + 1 );
         	strncpy( this->pretty_name, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pretty_plural = (char*)malloc( iPtrSize + 1 );
         	memset( this->pretty_plural, '0', iPtrSize + 1 );
         	strncpy( this->pretty_plural, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pageheader = (char*)malloc( iPtrSize + 1 );
         	memset( this->pageheader, '0', iPtrSize + 1 );
         	strncpy( this->pageheader, "", iPtrSize );

         	iPtrSize = strlen( "" );
         	this->pagefooter = (char*)malloc( iPtrSize + 1 );
         	memset( this->pagefooter, '0', iPtrSize + 1 );
         	strncpy( this->pagefooter, "", iPtrSize );

         	this->Setquerytablename( "technicalanalysis" );
         	this->Setclassname( "technicalanalysis" );
         	this->Setidtechnicalanalysis( idtechnicalanalysis );
         	/* primary key: 'idtechnicalanalysis' */
         	return;
         }
          bool Setdata( char* data )
         {
         	this->data = data;
	         return SUCCESS;
         }
          bool Setquerytablename( char* querytablename )
         {
         	this->querytablename = querytablename;
	         return SUCCESS;
         }
          bool Setclassname( char* classname )
         {
         	this->classname = classname;
	         return SUCCESS;
         }
         bool ObserverRegister( char* observer, int event )
         {
	         return FAILURE;
         }
         bool ObserverDeRegister( char *observer )
         {
                 /*this->observers[] = array_diff( $this->observers, array( $observer) );*/
	         return FAILURE;
         }
         bool ObserverNotify( int event, char *msg )
         {
	         return FAILURE;
         }
         bool notify( void *object )
         {
                 //Called when another object we are observing sends us a notification
	         return FAILURE;
         }
         bool Setidtechnicalanalysis( float  value )
         {
                 this->idtechnicalanalysis = value;
	          return 1;
         }
         /* int */ float  Getidtechnicalanalysis()
         {
                    return this->idtechnicalanalysis;
         }
         bool Setcreateddate( char*  value )
         {
                 this->createddate = value;
	          return 1;
         }
         /* datetime */ char*  Getcreateddate()
         {
                    return this->createddate;
         }
         bool Setcreateduser( float  value )
         {
                 this->createduser = value;
	          return 1;
         }
         /* int */ float  Getcreateduser()
         {
                    return this->createduser;
         }
         bool Setupdateddate( char*  value )
         {
                 this->updateddate = value;
	          return 1;
         }
         /* timestamp */ char*  Getupdateddate()
         {
                    return this->updateddate;
         }
         bool Setupdateduser( float  value )
         {
                 this->updateduser = value;
	          return 1;
         }
         /* int */ float  Getupdateduser()
         {
                    return this->updateduser;
         }
         bool Setsymbol( char*  value )
         {
                 this->symbol = value;
	          return 1;
         }
         /* varchar */ char*  Getsymbol()
         {
                    return this->symbol;
         }
         bool Setdate( char*  value )
         {
                 this->date = value;
	          return 1;
         }
         /* date */ char*  Getdate()
         {
                    return this->date;
         }
         bool Setday_close( float  value )
         {
                 this->day_close = value;
	          return 1;
         }
         /* float */ float  Getday_close()
         {
                    return this->day_close;
         }
         bool Settypicalprice( float  value )
         {
                 this->typicalprice = value;
	          return 1;
         }
         /* float */ float  Gettypicalprice()
         {
                    return this->typicalprice;
         }
         bool Setmovingaverage50( float  value )
         {
                 this->movingaverage50 = value;
	          return 1;
         }
         /* float */ float  Getmovingaverage50()
         {
                    return this->movingaverage50;
         }
         bool Setmovingaverage200( float  value )
         {
                 this->movingaverage200 = value;
	          return 1;
         }
         /* float */ float  Getmovingaverage200()
         {
                    return this->movingaverage200;
         }
         bool Setcandlestick( char*  value )
         {
                 this->candlestick = value;
	          return 1;
         }
         /* varchar */ char*  Getcandlestick()
         {
                    return this->candlestick;
         }
         bool Setexpmovingaverage9( float  value )
         {
                 this->expmovingaverage9 = value;
	          return 1;
         }
         /* float */ float  Getexpmovingaverage9()
         {
                    return this->expmovingaverage9;
         }
         bool Setexpmovingaverage12( float  value )
         {
                 this->expmovingaverage12 = value;
	          return 1;
         }
         /* float */ float  Getexpmovingaverage12()
         {
                    return this->expmovingaverage12;
         }
         bool Setexpmovingaverage26( float  value )
         {
                 this->expmovingaverage26 = value;
	          return 1;
         }
         /* float */ float  Getexpmovingaverage26()
         {
                    return this->expmovingaverage26;
         }
         bool Setmacd( char*  value )
         {
                 this->macd = value;
	          return 1;
         }
         /* varchar */ char*  Getmacd()
         {
                    return this->macd;
         }
         bool Setmomentumoscillator( float  value )
         {
                 this->momentumoscillator = value;
	          return 1;
         }
         /* float */ float  Getmomentumoscillator()
         {
                    return this->momentumoscillator;
         }
         bool Setmamomentum( float  value )
         {
                 this->mamomentum = value;
	          return 1;
         }
         /* float */ float  Getmamomentum()
         {
                    return this->mamomentum;
         }
         bool Setmacrossover( float  value )
         {
                 this->macrossover = value;
	          return 1;
         }
         /* int */ float  Getmacrossover()
         {
                    return this->macrossover;
         }
         bool Setmacenterlinecrossover( float  value )
         {
                 this->macenterlinecrossover = value;
	          return 1;
         }
         /* int */ float  Getmacenterlinecrossover()
         {
                    return this->macenterlinecrossover;
         }
         bool Setpriceoscillator( float  value )
         {
                 this->priceoscillator = value;
	          return 1;
         }
         /* float */ float  Getpriceoscillator()
         {
                    return this->priceoscillator;
         }
         bool Setmacd_histogram( float  value )
         {
                 this->macd_histogram = value;
	          return 1;
         }
         /* float */ float  Getmacd_histogram()
         {
                    return this->macd_histogram;
         }
         bool Setlinearregression( float  value )
         {
                 this->linearregression = value;
	          return 1;
         }
         /* float */ float  Getlinearregression()
         {
                    return this->linearregression;
         }
         bool Setlinearregressionangle( float  value )
         {
                 this->linearregressionangle = value;
	          return 1;
         }
         /* float */ float  Getlinearregressionangle()
         {
                    return this->linearregressionangle;
         }
         bool Setlinearregressionslope( float  value )
         {
                 this->linearregressionslope = value;
	          return 1;
         }
         /* float */ float  Getlinearregressionslope()
         {
                    return this->linearregressionslope;
         }
         bool Setlinearregressionintercept( float  value )
         {
                 this->linearregressionintercept = value;
	          return 1;
         }
         /* float */ float  Getlinearregressionintercept()
         {
                    return this->linearregressionintercept;
         }
         bool Setstochastic( float  value )
         {
                 this->stochastic = value;
	          return 1;
         }
         /* float */ float  Getstochastic()
         {
                    return this->stochastic;
         }
         bool Setrelativestrenghtindex( float  value )
         {
                 this->relativestrenghtindex = value;
	          return 1;
         }
         /* float */ float  Getrelativestrenghtindex()
         {
                    return this->relativestrenghtindex;
         }
         bool Setrsioscillator( float  value )
         {
                 this->rsioscillator = value;
	          return 1;
         }
         /* float */ float  Getrsioscillator()
         {
                    return this->rsioscillator;
         }
         bool Setcommoditychannelindex( float  value )
         {
                 this->commoditychannelindex = value;
	          return 1;
         }
         /* float */ float  Getcommoditychannelindex()
         {
                    return this->commoditychannelindex;
         }
         bool Setpricechangepercent( float  value )
         {
                 this->pricechangepercent = value;
	          return 1;
         }
         /* float */ float  Getpricechangepercent()
         {
                    return this->pricechangepercent;
         }
         bool Setvolume12( float  value )
         {
                 this->volume12 = value;
	          return 1;
         }
         /* int */ float  Getvolume12()
         {
                    return this->volume12;
         }
         bool Setvolume26( float  value )
         {
                 this->volume26 = value;
	          return 1;
         }
         /* int */ float  Getvolume26()
         {
                    return this->volume26;
         }
         bool Setvolume90( float  value )
         {
                 this->volume90 = value;
	          return 1;
         }
         /* int */ float  Getvolume90()
         {
                    return this->volume90;
         }
         bool Setsupport12( float  value )
         {
                 this->support12 = value;
	          return 1;
         }
         /* float */ float  Getsupport12()
         {
                    return this->support12;
         }
         bool Setsupport26( float  value )
         {
                 this->support26 = value;
	          return 1;
         }
         /* float */ float  Getsupport26()
         {
                    return this->support26;
         }
         bool Setresistance12( float  value )
         {
                 this->resistance12 = value;
	          return 1;
         }
         /* float */ float  Getresistance12()
         {
                    return this->resistance12;
         }
         bool Setresistance26( float  value )
         {
                 this->resistance26 = value;
	          return 1;
         }
         /* float */ float  Getresistance26()
         {
                    return this->resistance26;
         }
         bool Setbollingerbandmiddle( float  value )
         {
                 this->bollingerbandmiddle = value;
	          return 1;
         }
         /* float */ float  Getbollingerbandmiddle()
         {
                    return this->bollingerbandmiddle;
         }
         bool Setbollingerbandupper( float  value )
         {
                 this->bollingerbandupper = value;
	          return 1;
         }
         /* float */ float  Getbollingerbandupper()
         {
                    return this->bollingerbandupper;
         }
         bool Setbollingerbandlower( float  value )
         {
                 this->bollingerbandlower = value;
	          return 1;
         }
         /* float */ float  Getbollingerbandlower()
         {
                    return this->bollingerbandlower;
         }
         bool Setbollingerpercentb( float  value )
         {
                 this->bollingerpercentb = value;
	          return 1;
         }
         /* float */ float  Getbollingerpercentb()
         {
                    return this->bollingerpercentb;
         }
         bool Setbollingerbandwidth( float  value )
         {
                 this->bollingerbandwidth = value;
	          return 1;
         }
         /* float */ float  Getbollingerbandwidth()
         {
                    return this->bollingerbandwidth;
         }
         bool Setcoefficientofvariation( float  value )
         {
                 this->coefficientofvariation = value;
	          return 1;
         }
         /* float */ float  Getcoefficientofvariation()
         {
                    return this->coefficientofvariation;
         }
         bool Setmovingaverage260( float  value )
         {
                 this->movingaverage260 = value;
	          return 1;
         }
         /* float */ float  Getmovingaverage260()
         {
                    return this->movingaverage260;
         }
         bool Setstandarddeviation260( float  value )
         {
                 this->standarddeviation260 = value;
	          return 1;
         }
         /* float */ float  Getstandarddeviation260()
         {
                    return this->standarddeviation260;
         }
         bool Setannualreturn( float  value )
         {
                 this->annualreturn = value;
	          return 1;
         }
         /* float */ float  Getannualreturn()
         {
                    return this->annualreturn;
         }
         bool Setannualrisk( float  value )
         {
                 this->annualrisk = value;
	          return 1;
         }
         /* float */ float  Getannualrisk()
         {
                    return this->annualrisk;
         }
         bool Settruerange( float  value )
         {
                 this->truerange = value;
	          return 1;
         }
         /* float */ float  Gettruerange()
         {
                    return this->truerange;
         }
         bool Setexpmovingaverage90( float  value )
         {
                 this->expmovingaverage90 = value;
	          return 1;
         }
         /* float */ float  Getexpmovingaverage90()
         {
                    return this->expmovingaverage90;
         }
         bool Setvoltrendind90( char*  value )
         {
                 this->voltrendind90 = value;
	          return 1;
         }
         /* varchar */ char*  Getvoltrendind90()
         {
                    return this->voltrendind90;
         }
         bool Setvoltrendind26( char*  value )
         {
                 this->voltrendind26 = value;
	          return 1;
         }
         /* varchar */ char*  Getvoltrendind26()
         {
                    return this->voltrendind26;
         }
         bool Setvolume260( float  value )
         {
                 this->volume260 = value;
	          return 1;
         }
         /* float */ float  Getvolume260()
         {
                    return this->volume260;
         }
         bool Setvoltrendind260( char*  value )
         {
                 this->voltrendind260 = value;
	          return 1;
         }
         /* varchar */ char*  Getvoltrendind260()
         {
                    return this->voltrendind260;
         }
}; /* class technicalanalysis */
