CREATE TABLE `quarter_statement` (
  `idfin_statement` int(11) NOT NULL auto_increment,
  `idstockinfo` int(11) NOT NULL default '0',
  `netincome` float NOT NULL default '0',
  `depreciation` float NOT NULL default '0',
  `depletion` float NOT NULL default '0',
  `amortization` float NOT NULL default '0',
  `capitalexpenses` float NOT NULL default '0',
  `workingcapital` float NOT NULL default '0',
  `lasteval` timestamp NOT NULL default CURRENT_TIMESTAMP,
  `user` varchar(45) NOT NULL default '',
  `outstandingshares` int(10) unsigned NOT NULL default '0',
  `incomegrowth` float NOT NULL default '0',
  `ownerearnings` float NOT NULL default '0',
  `totalasset` float NOT NULL default '0',
  `totalliability` float NOT NULL default '0',
  `totalequity` float NOT NULL default '0',
  `totaldebt` float NOT NULL default '0',
  `dividendpershare` float NOT NULL default '0',
  `earningpershare` float NOT NULL default '0' COMMENT 'Annual Earnings per share',
  `revenue` float NOT NULL default '0' COMMENT 'Revenue from Income Statement',
  `retainedearnings` float NOT NULL default '0' COMMENT 'Retained Earnings',
  `revenuegrowth` float NOT NULL default '0' COMMENT 'Growth in revenue compared to previous year',
  `revenuegrowth2` float NOT NULL default '0' COMMENT 'Revenue Growth compared to 2 years ago',
  `revenuegrowth3` float NOT NULL default '0' COMMENT 'Revenue Growth compared to 3 years ago',
  PRIMARY KEY  (`idfin_statement`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
