<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class cash */

/*	view/QuickFormIncludes and TabbedPages.php are in the skel-app/view if required	*/
require_once( 'view/QuickFormIncludes.php' );;
require_once( 'view/TabbedPages.php' );;

class cash_Page1 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('cash page 1');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('submit', 'empty.gif');
		$this->addGlobalSubmit();
		$name = $fs->addElement('text', 'name', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
			->addFilter( 'trim' )
;
		$value = $fs->addElement('text', 'value', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
;
		$currency = $fs->addElement('text', 'currency', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
			->addFilter( 'trim' )
;
		$type = $fs->addElement('text', 'type', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
			->addFilter( 'trim' )
;
		$owner = $fs->addElement('text', 'owner', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
			->addFilter( 'trim' )
;
		$cost = $fs->addElement('text', 'cost', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
;
		$f_date = date("Y-m-d" );
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'date' => $f_date ) ) );
		$date = $fs->addElement('text', 'date', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
			->addFilter( 'trim' )
;
	}
}
?>