<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class evalvalue */

/*	view/QuickFormIncludes and TabbedPages.php are in the skel-app/view if required	*/
require_once( 'view/QuickFormIncludes.php' );;
require_once( 'view/TabbedPages.php' );;

class evalvalue_Page1 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('evalvalue page 1');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('submit', 'empty.gif');
		$this->addGlobalSubmit();
		$idevalvalue = $fs->addElement('text', 'idevalvalue', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
;
		$ownerearnings = $fs->addElement('text', 'ownerearnings', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
		$discountrate = $fs->addElement('text', 'discountrate', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
;
		$incomegrowth = $fs->addElement('text', 'incomegrowth', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'year over year growth percentage' )
;
		$value = $fs->addElement('text', 'value', array('size' => 11, 'maxlength' => 11) )
			->setLabel( '' )
;
		$kellyoptimization = $fs->addElement('text', 'kellyoptimization', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
		$riskprobability = $fs->addElement('text', 'riskprobability', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
		$debtratio = $fs->addElement('text', 'debtratio', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
		$acceptabledebt = $fs->addElement('text', 'acceptabledebt', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
		$netincome = $fs->addElement('text', 'netincome', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
		$depreciation = $fs->addElement('text', 'depreciation', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
		$depletion = $fs->addElement('text', 'depletion', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
		$amortization = $fs->addElement('text', 'amortization', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
		$capitalexpenses = $fs->addElement('text', 'capitalexpenses', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
		$workingcapital = $fs->addElement('text', 'workingcapital', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
		$marketcap = $fs->addElement('text', 'marketcap', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
		$marginsafety = $fs->addElement('text', 'marginsafety', array('size' => 10, 'maxlength' => 10) )
			->setLabel( '' )
;
	}
}
?>