<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class portfolio */

/*	view/QuickFormIncludes and TabbedPages.php are in the skel-app/view if required	*/
require_once( 'view/QuickFormIncludes.php' );;
require_once( 'view/TabbedPages.php' );;

class portfolio_Page1 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('portfolio page 1');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('submit', 'empty.gif');
		$this->addGlobalSubmit();
		$idportfolio = $fs->addElement('text', 'idportfolio', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Index' )
;
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'username' => $_SERVER['PHP_AUTH_USER'] ) ) );
		$username = $fs->addElement('text', 'username', array('size' => 45, 'maxlength' => 45) )
			->setLabel( 'User' )
			->addFilter( 'trim' )
;
		$account = $fs->addElement('text', 'account', array('size' => 45, 'maxlength' => 45) )
			->setLabel( 'Account' )
			->addFilter( 'trim' )
			->addFilter( 'strtoupper' )
			->addRule('required', 'account Field Required' );
		$numbershares = $fs->addElement('text', 'numbershares', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Number of Shares Owned' )
;
		$bookvalue = $fs->addElement('text', 'bookvalue', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Book Value' )
;
		$dividendbookvalue = $fs->addElement('text', 'dividendbookvalue', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Dividend Adjusted Book Value' )
;
		$marketvalue = $fs->addElement('text', 'marketvalue', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Market Value' )
;
		$profitloss = $fs->addElement('text', 'profitloss', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Profit or Loss' )
;
		$marketbook = $fs->addElement('text', 'marketbook', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Market Value to Book Value' )
;
		$yield = $fs->addElement('text', 'yield', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Price Yield' )
;
		$currentprice = $fs->addElement('text', 'currentprice', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Current Price' )
;
		$annualdividendpershare = $fs->addElement('text', 'annualdividendpershare', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Annual Dividend per Share' )
;
		$annualdividend = $fs->addElement('text', 'annualdividend', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Annual Dividend' )
;
		$dividendpercentbookvalue = $fs->addElement('text', 'dividendpercentbookvalue', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Dividend Percent of Book Value' )
;
		$dividendpercentmarketvalue = $fs->addElement('text', 'dividendpercentmarketvalue', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Dividend Percent of Market Value' )
;
		$dividendyield = $fs->addElement('text', 'dividendyield', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Dividend Yield' )
;
		$percenttotalmarketvalue = $fs->addElement('text', 'percenttotalmarketvalue', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'MV Percentage of Portfolio Market Value' )
;
		$percenttotalbookvalue = $fs->addElement('text', 'percenttotalbookvalue', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'BV Percentage of Portfolio Book Value' )
;
		$percenttotaldividend = $fs->addElement('text', 'percenttotaldividend', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Div Percentage of Portfolio Dividend Value' )
;
		$f_date = date("Y-m-d H:i:s" );
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'lastupdate' => $f_date ) ) );
		$lastupdate = $fs->addElement('text', 'lastupdate', array('size' => 16, 'maxlength' => 16) )
			->setLabel( 'Last Update' )
			->addFilter( 'trim' )
;
	}
}
?>