<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class stockexchange */

/*	view/QuickFormIncludes and TabbedPages.php are in the skel-app/view if required	*/
require_once( 'view/QuickFormIncludes.php' );;
require_once( 'view/TabbedPages.php' );;

class stockexchange_Page1 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('stockexchange page 1');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('submit', 'empty.gif');
		$this->addGlobalSubmit();
		$idstockexchange = $fs->addElement('text', 'idstockexchange', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Stock Exchange index' )
;
		$exchange = $fs->addElement('text', 'exchange', array('size' => 45, 'maxlength' => 45) )
			->setLabel( 'Exchange Name' )
			->addFilter( 'trim' )
			->addFilter( 'strtoupper' )
			->addRule('required', 'exchange Field Required' );
		$YahooSymbol = $fs->addElement('text', 'YahooSymbol', array('size' => 45, 'maxlength' => 45) )
			->setLabel( 'Yahoo Finance Symbol' )
			->addFilter( 'trim' )
			->addFilter( 'strtoupper' )
			->addRule('required', 'YahooSymbol Field Required' );
		$GlobeInvestorSymbol = $fs->addElement('text', 'GlobeInvestorSymbol', array('size' => 45, 'maxlength' => 45) )
			->setLabel( 'Globe Investor Symbol' )
			->addFilter( 'trim' )
			->addFilter( 'strtoupper' )
;
	}
}
?>