<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class stock90highlow */

/*	view/QuickFormIncludes and TabbedPages.php are in the skel-app/view if required	*/
require_once( 'view/QuickFormIncludes.php' );;
require_once( 'view/TabbedPages.php' );;

class stock90highlow_Page1 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('stock90highlow page 1');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('submit', 'empty.gif');
		$this->addGlobalSubmit();
		$idstock90highlow = $fs->addElement('text', 'idstock90highlow', array('size' => 10, 'maxlength' => 10) )
			->setLabel( 'Index' )
;
		$stocksymbol = $fs->addElement('text', 'stocksymbol', array('size' => 10, 'maxlength' => 10) )
			->setLabel( 'Stock Symbol' )
;
		$high = $fs->addElement('text', 'high', array('size' => 32, 'maxlength' => 32) )
			->setLabel( '' )
;
		$low = $fs->addElement('text', 'low', array('size' => 32, 'maxlength' => 32) )
			->setLabel( '' )
;
		$currentprice = $fs->addElement('text', 'currentprice', array('size' => 32, 'maxlength' => 32) )
			->setLabel( '' )
;
		$active = $fs->addElement('text', 'active', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Is this symbol still active' )
;
		$cik = $fs->addElement('text', 'cik', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'SEC's CIK value for the company' )
			->addFilter( 'trim' )
;
	$KEY = $fs->addElement('text', 'KEY', array() )
	->setLabel( '' )
	->addFilter( 'trim' )
;
	}
}
?>