<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class taxstatus */

/*	view/QuickFormIncludes and TabbedPages.php are in the skel-app/view if required	*/
require_once( 'view/QuickFormIncludes.php' );;
require_once( 'view/TabbedPages.php' );;

class taxstatus_Page1 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('taxstatus page 1');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('next', 'empty.gif');
		$this->addGlobalSubmit();
		$idtaxstatus = $fs->addElement('text', 'idtaxstatus', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Index' )
;
		$taxstatus = $fs->addElement('text', 'taxstatus', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Tax Status' )
			->addFilter( 'trim' )
;
		$notes = $fs->addElement('text', 'notes', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Notes' )
			->addFilter( 'trim' )
;
	$createduser = $fs->addElement('text', 'createduser', array() )
	->setLabel( 'Created By User' )
	->addFilter( 'trim' )
;
		$createddate = $fs->addElement('text', 'createddate', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Created Date' )
			->addFilter( 'trim' )
;
		$updateduser = $fs->addElement('text', 'updateduser', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Updated by User' )
			->addFilter( 'trim' )
;
	}
}

class taxstatus_Page2 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('taxstatus page 2');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('next', 'empty.gif');
		$this->addGlobalSubmit();
	}
}

class taxstatus_Page3 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('taxstatus page 3');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('submit', 'empty.gif');
		$this->addGlobalSubmit();
		$f_date = date("Y-m-d H:i:s" );
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'updateddate' => $f_date ) ) );
		$updateddate = $fs->addElement('text', 'updateddate', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Updated by User' )
			->addFilter( 'trim' )
;
	}
}
?>