<?php 
/*This file was generated by calling php /mnt/2/development/var/www/html/skel-app/generator.php finance php */

//this script may only be included - so its better to die if called directly.
if ( strpos( $_SERVER["SCRIPT_NAME"], basename(__FILE__) ) !== false ) {
  header( "location: ../index.php" );
  exit;
}

 /* class transaction */

/*	view/QuickFormIncludes and TabbedPages.php are in the skel-app/view if required	*/
require_once( 'view/QuickFormIncludes.php' );;
require_once( 'view/TabbedPages.php' );;

class transaction_Page1 extends TabbedPage
{
	 protected function populateForm()
	{
		$this->addTabs();
		$fs = $this->form->addElement('fieldset')->setLabel('transaction page 1');
		$buttonGroup = $fs->addElement('group'); 
		$buttonGroup->addElement('submit', $this->getButtonName('back'), array('value' => '<< Back')); 
		$buttonGroup->addElement('submit', $this->getButtonName('submit'), array('value' => 'Finish')); 
		$buttonGroup->addElement('submit', $this->getButtonName('next'), array('value' => 'Next >>')); 
		$this->setDefaultAction('submit', 'empty.gif');
		$this->addGlobalSubmit();
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'idusers' => $_SERVER['PHP_AUTH_USER'] ) ) );
		$idusers = $fs->addElement('text', 'idusers', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'User' )
			->addFilter( 'trim' )
;
		$account = $fs->addElement('text', 'account', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Which account is this transaction in (TRADE/RRSP/TFSA) ' )
			->addFilter( 'trim' )
;
		$currency = $fs->addElement('text', 'currency', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Home Currency' )
			->addFilter( 'trim' )
;
		$foreigncurrency = $fs->addElement('text', 'foreigncurrency', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Foreign Currency' )
			->addFilter( 'trim' )
;
		$f_date = date("Y-m-d" );
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'transactiondate' => $f_date ) ) );
		$transactiondate = $fs->addElement('text', 'transactiondate', array('size' => 10, 'maxlength' => 10) )
			->setLabel( 'Transaction Date' )
			->addFilter( 'trim' )
;
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'createduser' => $_SERVER['PHP_AUTH_USER'] ) ) );
		$createduser = $fs->addElement('text', 'createduser', array('size' => 10, 'maxlength' => 10) )
			->setLabel( 'Created User' )
			->addFilter( 'trim' )
;
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'createddate' => date("Y-m-d") ) ) );
		$createddate = $fs->addElement('text', 'createddate', array('size' => 10, 'maxlength' => 10) )
			->setLabel( 'Created Date' )
			->addFilter( 'trim' )
;
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'reviseduser' => $_SERVER['PHP_AUTH_USER'] ) ) );
		$reviseduser = $fs->addElement('text', 'reviseduser', array('size' => 10, 'maxlength' => 10) )
			->setLabel( 'Last Update User' )
			->addFilter( 'trim' )
;
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'reviseddate' => date("Y-m-d") ) ) );
		$reviseddate = $fs->addElement('text', 'reviseddate', array('size' => 10, 'maxlength' => 10) )
			->setLabel( 'Last Update Date' )
			->addFilter( 'trim' )
;
		$sequence = $fs->addElement('text', 'sequence', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Sequence' )
;
		$this->form->addDataSource(new HTML_QuickForm2_DataSource_Array(array( 'username' => $_SERVER['PHP_AUTH_USER'] ) ) );
		$username = $fs->addElement('text', 'username', array('size' => 45, 'maxlength' => 45) )
			->setLabel( 'User' )
			->addFilter( 'trim' )
			->addRule('required', 'username Field Required' );
		$numbershares = $fs->addElement('text', 'numbershares', array('size' => 11, 'maxlength' => 11) )
			->setLabel( 'Number' )
			->addRule('required', 'numbershares Field Required' );
		$dollar = $fs->addElement('text', 'dollar', array('size' => 45, 'maxlength' => 45) )
			->setLabel( 'Dollars' )
			->addRule('required', 'dollar Field Required' );
	}
}
?>